import Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement
import Asp0.Services.Internal.Strong.Asp0aspect._2019_06.AspectManagement
import Asp0.Services.Strong.Asp0aspect._2015_07.AspectManagement
import System
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model.Strong
import typing

class AspectManagementRestBindingStub(AspectManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateAspectSearchExpressions(self, ExprInputs: list[Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement.AspectSearchExpressionIn]) -> Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement.AspectSearchExpressionResponse: ...
    @typing.overload
    def ExpandAspects(self, AspectExpandInfo: list[Asp0.Services.Strong.Asp0aspect._2015_07.AspectManagement.ExpandAspectsInfo], ConfigContext: Teamcenter.Soa.Client.Model.Strong.ConfigurationContext) -> Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement.ExpandAspectsResponse: ...
    @typing.overload
    def ExpandAspects(self, AspectExpandInfos: list[Asp0.Services.Internal.Strong.Asp0aspect._2019_06.AspectManagement.ExpandAspectsInfo], ConfigContext: Teamcenter.Soa.Client.Model.Strong.ConfigurationContext) -> Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement.ExpandAspectsResponse: ...

class AspectManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> AspectManagementService: ...
    def CreateAspectSearchExpressions(self, ExprInputs: list[Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement.AspectSearchExpressionIn]) -> Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement.AspectSearchExpressionResponse: ...
    @typing.overload
    def ExpandAspects(self, AspectExpandInfo: list[Asp0.Services.Strong.Asp0aspect._2015_07.AspectManagement.ExpandAspectsInfo], ConfigContext: Teamcenter.Soa.Client.Model.Strong.ConfigurationContext) -> Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement.ExpandAspectsResponse: ...
    @typing.overload
    def ExpandAspects(self, AspectExpandInfos: list[Asp0.Services.Internal.Strong.Asp0aspect._2019_06.AspectManagement.ExpandAspectsInfo], ConfigContext: Teamcenter.Soa.Client.Model.Strong.ConfigurationContext) -> Asp0.Services.Internal.Strong.Asp0aspect._2018_06.AspectManagement.ExpandAspectsResponse: ...

