import System.Collections

class BasicTcSSOCookieManager:
    def __init__(self, ) -> None: ...
    def processFormChallenge(self, destUrl: str, tcSSOLoginUrl: str, requestHeaders: System.Collections.IDictionary, replyHeaders: System.Collections.IDictionary) -> System.Collections.IList: ...
    def setCookies(self, destUrl: str, newCookies: System.Collections.IList) -> None: ...
    def getCookies(self, destUrl: str) -> System.Collections.IList: ...

