import System
import System.Collections.Generic
import System.Net
import typing

class SessionAgentJsonHttpBinding:
    def __init__(self, URLstr: str) -> None: ...
    @typing.overload
    def Init(self, URLstr: str) -> None: ...
    @typing.overload
    def Init(self, URLstr: str, creator: IWebRequestCreator) -> None: ...
    def SendRequest(self, payload: dict[str, typing.Any]) -> dict[str, typing.Any]: ...

class IWebRequestCreator:
    def __init__(self , *args: typing.Any) -> None: ...
    def CreateWebRequest(self, uri: System.Uri) -> System.Net.WebRequest: ...

class DefaultWebRequestCreator:
    def __init__(self, ) -> None: ...
    def CreateWebRequest(self, uri: System.Uri) -> System.Net.WebRequest: ...

