import System
import Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate
import Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.PublishByLink
import Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.Restructure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2007_12.BrokenLinks
import Teamcenter.Services.Internal.Strong.Structuremanagement._2008_03.Structure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2008_05.Restructure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2008_05.Structure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2009_10.EffectivitiesManagement
import Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup
import Teamcenter.Services.Internal.Strong.Structuremanagement._2010_09.Structure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange
import Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.VariantManagement
import Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification
import Teamcenter.Services.Internal.Strong.Structuremanagement._2012_09.StructureVerification
import Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite
import Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite
import Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.BrokenLinks
import Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.Restructure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification
import Teamcenter.Services.Internal.Strong.Structuremanagement._2015_10.VariantManagement
import Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification
import Teamcenter.Services.Internal.Strong.Structuremanagement._2016_10.Effectivity
import Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite
import Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureLiteConversion
import Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification
import Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.MassUpdate
import Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification
import Teamcenter.Services.Internal.Strong.Structuremanagement._2020_05.RevisionRuleAdministration
import Teamcenter.Services.Internal.Strong.Structuremanagement._2021_12.EffectivitiesManagement
import Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure
import Teamcenter.Services.Internal.Strong.Structuremanagement._2023_06.RevisionRuleAdministration
import Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification
import Teamcenter.Services.Strong.Structuremanagement._2012_10.StructureVerification
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong
import typing

class BOMMarkupRestBindingStub(BOMMarkupService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ApplyBOMMarkup(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup.ApplyBOMMarkupParam]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def CreateBOMMarkup(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup.CreateBOMMarkupParam]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup.CreateBOMMarkupResponse: ...
    def SavePendingEditsAsMarkup(self, Window: Teamcenter.Soa.Client.Model.Strong.BOMWindow) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup.CreateBOMMarkupResponse: ...

class BOMMarkupService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> BOMMarkupService: ...
    def ApplyBOMMarkup(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup.ApplyBOMMarkupParam]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def CreateBOMMarkup(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup.CreateBOMMarkupParam]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup.CreateBOMMarkupResponse: ...
    def SavePendingEditsAsMarkup(self, Window: Teamcenter.Soa.Client.Model.Strong.BOMWindow) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2010_04.BOMMarkup.CreateBOMMarkupResponse: ...

class BrokenLinksRestBindingStub(BrokenLinksService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetBrokenLinkInfoWithFixOpt(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_12.BrokenLinks.FindAndFixInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_12.BrokenLinks.FindCandidatesResponse: ...
    def RepairBrokenLinks(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_12.BrokenLinks.RepairBrokenLinksParam]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetBrokenLinkAndReplacements(self, BrokenLinkInput: Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.BrokenLinks.BrokenLinkSearchInput) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.BrokenLinks.BrokenLinkReplacementResponse: ...

class BrokenLinksService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> BrokenLinksService: ...
    def GetBrokenLinkInfoWithFixOpt(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_12.BrokenLinks.FindAndFixInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_12.BrokenLinks.FindCandidatesResponse: ...
    def RepairBrokenLinks(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_12.BrokenLinks.RepairBrokenLinksParam]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetBrokenLinkAndReplacements(self, BrokenLinkInput: Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.BrokenLinks.BrokenLinkSearchInput) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.BrokenLinks.BrokenLinkReplacementResponse: ...

class EffectivitiesManagementRestBindingStub(EffectivitiesManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def SetEndItemEffectivityGroups(self, EffectivityGrpInput: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2009_10.EffectivitiesManagement.EffectivityGroupInputInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def CreateOrUpdateEffectivites(self, EffectivitiesInfo: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2009_10.EffectivitiesManagement.EffectivitiesInputInfo], EffectivityGroupRevision: Teamcenter.Soa.Client.Model.Strong.ItemRevision) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetEffectivityGrpRevList(self, BomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2009_10.EffectivitiesManagement.GetEffectivityGrpListResponse: ...
    def CreateOrUpdateDateEffectivities(self, EffectivitiesInfo: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2021_12.EffectivitiesManagement.EffectivitiesInputInfo2], EffectivityGroupRevision: Teamcenter.Soa.Client.Model.Strong.ItemRevision) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class EffectivitiesManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> EffectivitiesManagementService: ...
    def SetEndItemEffectivityGroups(self, EffectivityGrpInput: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2009_10.EffectivitiesManagement.EffectivityGroupInputInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def CreateOrUpdateEffectivites(self, EffectivitiesInfo: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2009_10.EffectivitiesManagement.EffectivitiesInputInfo], EffectivityGroupRevision: Teamcenter.Soa.Client.Model.Strong.ItemRevision) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetEffectivityGrpRevList(self, BomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2009_10.EffectivitiesManagement.GetEffectivityGrpListResponse: ...
    def CreateOrUpdateDateEffectivities(self, EffectivitiesInfo: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2021_12.EffectivitiesManagement.EffectivitiesInputInfo2], EffectivityGroupRevision: Teamcenter.Soa.Client.Model.Strong.ItemRevision) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class EffectivityRestBindingStub(EffectivityService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CutbackUnitOccurrenceEffectivity(self, OccEffCutbacks: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2016_10.Effectivity.OccEffCutbackInfo]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2016_10.Effectivity.CutbackUnitEffectivityResponse: ...
    def GetUnitNetOccurrenceEffectivity(self, Bomlines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2016_10.Effectivity.NetEffectivityResponse: ...

class EffectivityService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> EffectivityService: ...
    def CutbackUnitOccurrenceEffectivity(self, OccEffCutbacks: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2016_10.Effectivity.OccEffCutbackInfo]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2016_10.Effectivity.CutbackUnitEffectivityResponse: ...
    def GetUnitNetOccurrenceEffectivity(self, Bomlines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2016_10.Effectivity.NetEffectivityResponse: ...

class GlobalAlternateRestBindingStub(GlobalAlternateService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def AddRelatedGlobalAlternates(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateListInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateResponse: ...
    def RemoveRelatedGlobalAlternates(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateListInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateResponse: ...
    def SetPreferredGlobalAlternate(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.PreferredGlobalAlternateInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ListGlobalAlternates(self, Items: list[Teamcenter.Soa.Client.Model.Strong.Item]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateResponse: ...

class GlobalAlternateService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> GlobalAlternateService: ...
    def AddRelatedGlobalAlternates(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateListInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateResponse: ...
    def RemoveRelatedGlobalAlternates(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateListInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateResponse: ...
    def SetPreferredGlobalAlternate(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.PreferredGlobalAlternateInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ListGlobalAlternates(self, Items: list[Teamcenter.Soa.Client.Model.Strong.Item]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.GlobalAlternate.GlobalAlternateResponse: ...

class IncrementalChangeRestBindingStub(IncrementalChangeService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetAttachmentChanges(self, Attachmentlines: list[Teamcenter.Soa.Client.Model.Strong.MECfgLine], FRefresh: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttachmentChangeResponse: ...
    def GetAttributeChanges(self, AttributeOccLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], FRefresh: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttributeChangeResponse: ...
    def GetParentAndChildComponents(self, IcRevision: Teamcenter.Soa.Client.Model.Strong.ItemRevision) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.ParentAndChildComponentsResponse: ...
    def GetPredecessorChanges(self, PredecessorLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], FRefresh: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.PredecessorChangeResponse: ...
    def GetStructureChanges(self, Bomlines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], FRefresh: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.StructureChangeResponse: ...

class IncrementalChangeService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> IncrementalChangeService: ...
    def GetAttachmentChanges(self, Attachmentlines: list[Teamcenter.Soa.Client.Model.Strong.MECfgLine], FRefresh: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttachmentChangeResponse: ...
    def GetAttributeChanges(self, AttributeOccLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], FRefresh: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.AttributeChangeResponse: ...
    def GetParentAndChildComponents(self, IcRevision: Teamcenter.Soa.Client.Model.Strong.ItemRevision) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.ParentAndChildComponentsResponse: ...
    def GetPredecessorChanges(self, PredecessorLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], FRefresh: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.PredecessorChangeResponse: ...
    def GetStructureChanges(self, Bomlines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], FRefresh: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.IncrementalChange.StructureChangeResponse: ...

class MassUpdateRestBindingStub(MassUpdateService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def HasActiveMarkupAssociated(self, ChangeObject: Teamcenter.Soa.Client.Model.Strong.ItemRevision) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.MassUpdate.HasActiveMarkupAssociatedOut: ...
    def SaveImpactedAssemblies(self, ChangeObject: Teamcenter.Soa.Client.Model.Strong.ItemRevision, ImpactedObjectsInfo: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.MassUpdate.SaveImpactedAssembliesIn]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class MassUpdateService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> MassUpdateService: ...
    def HasActiveMarkupAssociated(self, ChangeObject: Teamcenter.Soa.Client.Model.Strong.ItemRevision) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.MassUpdate.HasActiveMarkupAssociatedOut: ...
    def SaveImpactedAssemblies(self, ChangeObject: Teamcenter.Soa.Client.Model.Strong.ItemRevision, ImpactedObjectsInfo: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.MassUpdate.SaveImpactedAssembliesIn]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class PublishByLinkRestBindingStub(PublishByLinkService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateIDCWindowForDesignAsm(self, Comps: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.PublishByLink.CreateIDCWindowResponse: ...

class PublishByLinkService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> PublishByLinkService: ...
    def CreateIDCWindowForDesignAsm(self, Comps: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.PublishByLink.CreateIDCWindowResponse: ...

class RedliningRestBindingStub(RedliningService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def RevertAllPendingEdits(self, Windows: list[Teamcenter.Soa.Client.Model.Strong.BOMWindow]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def RevertPendingEdits(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class RedliningService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> RedliningService: ...
    def RevertAllPendingEdits(self, Windows: list[Teamcenter.Soa.Client.Model.Strong.BOMWindow]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def RevertPendingEdits(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class RestructureRestBindingStub(RestructureService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def InsertLevel(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.Restructure.InsertLevelParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def MoveNode(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.Restructure.MoveNodeParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SplitOccurrence(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.Restructure.SplitOccurrenceParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def RemoveLevel(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ReplaceInContext(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2008_05.Restructure.ReplaceInContextParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ReplaceItems(self, ReplaceInputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.Restructure.ReplaceItemsParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class RestructureService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> RestructureService: ...
    def InsertLevel(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.Restructure.InsertLevelParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def MoveNode(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.Restructure.MoveNodeParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SplitOccurrence(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2007_06.Restructure.SplitOccurrenceParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def RemoveLevel(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ReplaceInContext(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2008_05.Restructure.ReplaceInContextParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ReplaceItems(self, ReplaceInputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.Restructure.ReplaceItemsParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class RevisionRuleAdministrationRestBindingStub(RevisionRuleAdministrationService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateOrUpdateRevisionRule(self, InputData: Teamcenter.Services.Internal.Strong.Structuremanagement._2020_05.RevisionRuleAdministration.CreateUpdateRevRuleInput) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2020_05.RevisionRuleAdministration.CreateOrUpdateRevRuleResp: ...
    def GetRevisionRuleInfo(self, RevRule: str) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2020_05.RevisionRuleAdministration.RevRuleInfoResponse: ...
    def CreateOrUpdateRevisionRule2(self, InputData: Teamcenter.Services.Internal.Strong.Structuremanagement._2023_06.RevisionRuleAdministration.CreateOrUpdateRevRuleInput2) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2023_06.RevisionRuleAdministration.CreateOrUpdateRevRuleResp2: ...
    def GetRevisionRuleInfo2(self, RevRule: str) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2023_06.RevisionRuleAdministration.RevRuleInfoResponse2: ...

class RevisionRuleAdministrationService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> RevisionRuleAdministrationService: ...
    def CreateOrUpdateRevisionRule(self, InputData: Teamcenter.Services.Internal.Strong.Structuremanagement._2020_05.RevisionRuleAdministration.CreateUpdateRevRuleInput) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2020_05.RevisionRuleAdministration.CreateOrUpdateRevRuleResp: ...
    def GetRevisionRuleInfo(self, RevRule: str) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2020_05.RevisionRuleAdministration.RevRuleInfoResponse: ...
    def CreateOrUpdateRevisionRule2(self, InputData: Teamcenter.Services.Internal.Strong.Structuremanagement._2023_06.RevisionRuleAdministration.CreateOrUpdateRevRuleInput2) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2023_06.RevisionRuleAdministration.CreateOrUpdateRevRuleResp2: ...
    def GetRevisionRuleInfo2(self, RevRule: str) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2023_06.RevisionRuleAdministration.RevRuleInfoResponse2: ...

class StructureExpansionLiteRestBindingStub(StructureExpansionLiteService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ExpandBasedOnOccurrenceList(self, LinePaths: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.LineAndPaths], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.PartialExpansionControls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.ExpansionResponse: ...
    def ExpandNext(self, LinesToExpand: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.Controls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.ExpansionResponse: ...
    def GetUndelivered(self, UndeliveredLineUids: list[str], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.Controls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.ExpansionResponse: ...
    def UnloadBelow(self, Lines: list[Teamcenter.Soa.Client.Model.Strong.Fnd0BOMLineLite]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ExpandBasedOnOccurrenceList2(self, LinePaths: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.LineAndPaths], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.PartialExpansionControls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.ExpansionResponse2: ...
    def ExpandNext2(self, LinesToExpand: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.Controls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.ExpansionResponse2: ...
    def GetUndelivered2(self, UndeliveredLineUids: list[str], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.Controls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.ExpansionResponse2: ...
    def UnloadBelow2(self, Lines: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ExpandNext3(self, LinesToExpand: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite.Controls2) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite.ExpansionResponse3: ...
    def GetUndelivered3(self, UndeliveredLineUids: list[str], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite.Controls3) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite.ExpansionResponse3: ...

class StructureExpansionLiteService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureExpansionLiteService: ...
    def ExpandBasedOnOccurrenceList(self, LinePaths: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.LineAndPaths], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.PartialExpansionControls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.ExpansionResponse: ...
    def ExpandNext(self, LinesToExpand: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.Controls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.ExpansionResponse: ...
    def GetUndelivered(self, UndeliveredLineUids: list[str], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.Controls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.ExpansionResponse: ...
    def UnloadBelow(self, Lines: list[Teamcenter.Soa.Client.Model.Strong.Fnd0BOMLineLite]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ExpandBasedOnOccurrenceList2(self, LinePaths: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.LineAndPaths], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.PartialExpansionControls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.ExpansionResponse2: ...
    def ExpandNext2(self, LinesToExpand: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.Controls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.ExpansionResponse2: ...
    def GetUndelivered2(self, UndeliveredLineUids: list[str], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2013_05.StructureExpansionLite.Controls) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2013_12.StructureExpansionLite.ExpansionResponse2: ...
    def UnloadBelow2(self, Lines: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ExpandNext3(self, LinesToExpand: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite.Controls2) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite.ExpansionResponse3: ...
    def GetUndelivered3(self, UndeliveredLineUids: list[str], Controls: Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite.Controls3) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureExpansionLite.ExpansionResponse3: ...

class StructureLiteConversionRestBindingStub(StructureLiteConversionService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def LiteBOMLinesToBOMLines(self, LinesToConvert: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureLiteConversion.ConversionResponse: ...

class StructureLiteConversionService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureLiteConversionService: ...
    def LiteBOMLinesToBOMLines(self, LinesToConvert: list[Teamcenter.Soa.Client.Model.Strong.RuntimeBusinessObject]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureLiteConversion.ConversionResponse: ...

class StructureRestBindingStub(StructureService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    @typing.overload
    def Resequence(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2008_03.Structure.ReSequenceParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    @typing.overload
    def Resequence(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2010_09.Structure.ReSequenceParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SyncAlignedOccurrences(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2008_05.Structure.BOMLinePair]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def FindHighestFindNumberInExpand(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.FindHighestFindNumInExpandInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.FindHighestFindNumberInExpandResponse: ...
    def CopyRecursively(self, ObjectToClone: Teamcenter.Soa.Client.Model.Strong.WorkspaceObject, CopyActionRulesKey: str, TemplateBOMWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow, WindowOfSelectedLine: Teamcenter.Soa.Client.Model.Strong.BOMWindow, NewName: str, NewDescription: str, NewId: str, NewRevId: str, CopyFutureEffectivities: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.CopyRecursivelyResponse: ...
    def CreateOrSavePSBOMViewRevision(self, CreateOrSavePSBOMViewRevisionInputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure.CreateOrSaveAsPSBOMViewRevisionInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure.CreateOrSaveAsPSBOMViewRevisionResponse: ...
    def GetAvailableViewTypes(self, GetAvailableViewTypesInputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure.GetAllAvailableViewTypesInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure.GetAvailableViewTypesResponse: ...
    def CreateOrUpdateOccAttrObjects(self, Inputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure.CreateOrUpdateOccAttrObjectsIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure.CreateOrUpdateOccAttrObjectsResp: ...
    def GetOccAttrsObjects(self, Inputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure.GetOccAttrsObjectsIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure.GetOccAttrsObjectsResponse: ...

class StructureService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureService: ...
    @typing.overload
    def Resequence(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2008_03.Structure.ReSequenceParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    @typing.overload
    def Resequence(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2010_09.Structure.ReSequenceParameter]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SyncAlignedOccurrences(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2008_05.Structure.BOMLinePair]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def FindHighestFindNumberInExpand(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.FindHighestFindNumInExpandInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.FindHighestFindNumberInExpandResponse: ...
    def CopyRecursively(self, ObjectToClone: Teamcenter.Soa.Client.Model.Strong.WorkspaceObject, CopyActionRulesKey: str, TemplateBOMWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow, WindowOfSelectedLine: Teamcenter.Soa.Client.Model.Strong.BOMWindow, NewName: str, NewDescription: str, NewId: str, NewRevId: str, CopyFutureEffectivities: bool) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2008_06.Structure.CopyRecursivelyResponse: ...
    def CreateOrSavePSBOMViewRevision(self, CreateOrSavePSBOMViewRevisionInputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure.CreateOrSaveAsPSBOMViewRevisionInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure.CreateOrSaveAsPSBOMViewRevisionResponse: ...
    def GetAvailableViewTypes(self, GetAvailableViewTypesInputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure.GetAllAvailableViewTypesInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.Structure.GetAvailableViewTypesResponse: ...
    def CreateOrUpdateOccAttrObjects(self, Inputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure.CreateOrUpdateOccAttrObjectsIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure.CreateOrUpdateOccAttrObjectsResp: ...
    def GetOccAttrsObjects(self, Inputs: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure.GetOccAttrsObjectsIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2022_12.Structure.GetOccAttrsObjectsResponse: ...

class StructureVerificationRestBindingStub(StructureVerificationService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetActivitiesComparisonDetails(self, EquivalentObjects: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification.EquivalentLines2], ComparisonCriteria: Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification.PartialMatchCriteria2) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification.GetActivitiesComparisonDetailsResponse: ...
    def GetToolRequirementComparisonDetails(self, SourceObjects: list[Teamcenter.Soa.Client.Model.ModelObject], TargetObjects: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification.ToolRequirementComparisonResult: ...
    def GetValidCriteria(self, Inputscope: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2012_09.StructureVerification.ValidCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2012_09.StructureVerification.GetValidCriteriaResponse: ...
    def CreateOrUpdatePropagationDetails(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.CreateOrUpdatePropagationDetailsIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.CreateOrUpdatePropagationDetailsResp: ...
    def CreateOrUpdateReviewStatus(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.CreateOrUpdateReviewStatusIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.CreateOrUpdateReviewStatusResponse: ...
    def FindReviewStatus(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.FindReviewStatusIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.FindReviewStatusResponse: ...
    def GetPropertyPropagationStatusDetails(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.GetPropPropagationStatusDetailsIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.GetPropPropagationStatusDetailsResp: ...
    def GetStructureChangeDetails(self, DetailsElements: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.StructureChangeDetailsElement]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.GetStructureChangeDetailsResponse: ...
    def GetStructureChangeImpactedLines(self, ImpactedLinesCriteria: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.ImpactedLinesCriteria]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.GetStructureChangeImpactedLinesResponse: ...
    def AlignMatchedCandidates(self, InputObjects: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.AlignMatchedCandidateElem], AdditionalInfo: Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.AdditionalData) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.AlignMatchedCandidatesResp: ...
    def FindMatchingCandidates(self, InputObjects: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.SearchCandidateElems], AdditionalInfo: Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.AdditionalData) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.FindMatchingCandidatesResp: ...
    def GetAttachmentComparisonDetails(self, EquivalentObjects: list[Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.EquivalentLines], PartialMatchCriteria: list[Teamcenter.Services.Strong.Structuremanagement._2012_10.StructureVerification.StringToPartialMatchCriteria]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification.AttachmentComparisonDetailsResponse: ...
    def GetMountAttachComparisonDetails(self, EquivalentObjects: list[Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.EquivalentLines], PartialMatchCriteria: list[Teamcenter.Services.Strong.Structuremanagement._2012_10.StructureVerification.StringToPartialMatchCriteria]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification.MountAttachComparisonsResponse: ...

class StructureVerificationService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureVerificationService: ...
    def GetActivitiesComparisonDetails(self, EquivalentObjects: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification.EquivalentLines2], ComparisonCriteria: Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification.PartialMatchCriteria2) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification.GetActivitiesComparisonDetailsResponse: ...
    def GetToolRequirementComparisonDetails(self, SourceObjects: list[Teamcenter.Soa.Client.Model.ModelObject], TargetObjects: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2012_02.StructureVerification.ToolRequirementComparisonResult: ...
    def GetValidCriteria(self, Inputscope: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2012_09.StructureVerification.ValidCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2012_09.StructureVerification.GetValidCriteriaResponse: ...
    def CreateOrUpdatePropagationDetails(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.CreateOrUpdatePropagationDetailsIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.CreateOrUpdatePropagationDetailsResp: ...
    def CreateOrUpdateReviewStatus(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.CreateOrUpdateReviewStatusIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.CreateOrUpdateReviewStatusResponse: ...
    def FindReviewStatus(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.FindReviewStatusIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.FindReviewStatusResponse: ...
    def GetPropertyPropagationStatusDetails(self, Input: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.GetPropPropagationStatusDetailsIn]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.GetPropPropagationStatusDetailsResp: ...
    def GetStructureChangeDetails(self, DetailsElements: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.StructureChangeDetailsElement]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.GetStructureChangeDetailsResponse: ...
    def GetStructureChangeImpactedLines(self, ImpactedLinesCriteria: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.ImpactedLinesCriteria]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2014_12.StructureVerification.GetStructureChangeImpactedLinesResponse: ...
    def AlignMatchedCandidates(self, InputObjects: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.AlignMatchedCandidateElem], AdditionalInfo: Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.AdditionalData) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.AlignMatchedCandidatesResp: ...
    def FindMatchingCandidates(self, InputObjects: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.SearchCandidateElems], AdditionalInfo: Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.AdditionalData) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2016_03.StructureVerification.FindMatchingCandidatesResp: ...
    def GetAttachmentComparisonDetails(self, EquivalentObjects: list[Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.EquivalentLines], PartialMatchCriteria: list[Teamcenter.Services.Strong.Structuremanagement._2012_10.StructureVerification.StringToPartialMatchCriteria]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2017_05.StructureVerification.AttachmentComparisonDetailsResponse: ...
    def GetMountAttachComparisonDetails(self, EquivalentObjects: list[Teamcenter.Services.Strong.Structuremanagement._2012_02.StructureVerification.EquivalentLines], PartialMatchCriteria: list[Teamcenter.Services.Strong.Structuremanagement._2012_10.StructureVerification.StringToPartialMatchCriteria]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2018_11.StructureVerification.MountAttachComparisonsResponse: ...

class VariantManagementRestBindingStub(VariantManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetModularOptionsForBom(self, Modules: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.VariantManagement.ModularOptionsInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.VariantManagement.ModularOptionsForBomResponse: ...
    def GetBOMVariantConfigOptions(self, BomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow, BomLine: Teamcenter.Soa.Client.Model.Strong.BOMLine) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.VariantManagement.BOMVariantConfigOptionResponse: ...
    def ApplyVariantConfiguration(self, Window: Teamcenter.Soa.Client.Model.Strong.BOMWindow, VariantConfigurationCriteria: Teamcenter.Services.Internal.Strong.Structuremanagement._2015_10.VariantManagement.VariantConfigurationCriteria) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ApplyRollupVariantConfiguration(self, Bomlines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], ConsiderWindowSVR: bool) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class VariantManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> VariantManagementService: ...
    def GetModularOptionsForBom(self, Modules: list[Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.VariantManagement.ModularOptionsInput]) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.VariantManagement.ModularOptionsForBomResponse: ...
    def GetBOMVariantConfigOptions(self, BomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow, BomLine: Teamcenter.Soa.Client.Model.Strong.BOMLine) -> Teamcenter.Services.Internal.Strong.Structuremanagement._2011_06.VariantManagement.BOMVariantConfigOptionResponse: ...
    def ApplyVariantConfiguration(self, Window: Teamcenter.Soa.Client.Model.Strong.BOMWindow, VariantConfigurationCriteria: Teamcenter.Services.Internal.Strong.Structuremanagement._2015_10.VariantManagement.VariantConfigurationCriteria) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ApplyRollupVariantConfiguration(self, Bomlines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], ConsiderWindowSVR: bool) -> Teamcenter.Soa.Client.Model.ServiceData: ...

