import System
import System.Collections

class ActionReference:
    def __init__(self, ) -> None: ...
    Exprt: bool
    IsExprtSet: bool
    ReferenceName: str
    def get_Exprt(self) -> bool: ...
    def set_Exprt(self, value: bool) -> None: ...
    def getExprt(self) -> bool: ...
    def setExprt(self, val: bool) -> None: ...
    def get_IsExprtSet(self) -> bool: ...
    def get_ReferenceName(self) -> str: ...
    def set_ReferenceName(self, value: str) -> None: ...
    def getReferenceName(self) -> str: ...
    def setReferenceName(self, val: str) -> None: ...

class AttachedLov:
    def __init__(self, ) -> None: ...
    ConditionName: str
    LovUid: str
    def get_ConditionName(self) -> str: ...
    def set_ConditionName(self, value: str) -> None: ...
    def getConditionName(self) -> str: ...
    def setConditionName(self, val: str) -> None: ...
    def get_LovUid(self) -> str: ...
    def set_LovUid(self, value: str) -> None: ...
    def getLovUid(self) -> str: ...
    def setLovUid(self, val: str) -> None: ...

class BasedOn:
    def __init__(self, ) -> None: ...
    SourceProperty: str
    IsSourcePropertySet: bool
    SourceType: str
    IsSourceTypeSet: bool
    def get_SourceProperty(self) -> str: ...
    def set_SourceProperty(self, value: str) -> None: ...
    def getSourceProperty(self) -> str: ...
    def setSourceProperty(self, val: str) -> None: ...
    def get_IsSourcePropertySet(self) -> bool: ...
    def get_SourceType(self) -> str: ...
    def set_SourceType(self, value: str) -> None: ...
    def getSourceType(self) -> str: ...
    def setSourceType(self, val: str) -> None: ...
    def get_IsSourceTypeSet(self) -> bool: ...

class Bounds:
    def __init__(self, ) -> None: ...
    UpperBound: str
    LowerBound: str
    def get_UpperBound(self) -> str: ...
    def set_UpperBound(self, value: str) -> None: ...
    def getUpperBound(self) -> str: ...
    def setUpperBound(self, val: str) -> None: ...
    def get_LowerBound(self) -> str: ...
    def set_LowerBound(self, value: str) -> None: ...
    def getLowerBound(self) -> str: ...
    def setLowerBound(self, val: str) -> None: ...

class Constant:
    def __init__(self, ) -> None: ...
    Name: str
    Value: str
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Value(self) -> str: ...
    def set_Value(self, value: str) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, val: str) -> None: ...

class DatasetAction:
    def __init__(self, ) -> None: ...
    ToolName: str
    Action: str
    ActionReferences: list[ActionReference]
    def get_ToolName(self) -> str: ...
    def set_ToolName(self, value: str) -> None: ...
    def getToolName(self) -> str: ...
    def setToolName(self, val: str) -> None: ...
    def get_Action(self) -> str: ...
    def set_Action(self, value: str) -> None: ...
    def getAction(self) -> str: ...
    def setAction(self, val: str) -> None: ...
    def get_ActionReferences(self) -> list[ActionReference]: ...
    def set_ActionReferences(self, value: list[ActionReference]) -> None: ...
    def getActionReferences(self) -> System.Collections.ArrayList: ...
    def setActionReferences(self, val: System.Collections.ArrayList) -> None: ...

class DatasetReferenceInfo:
    def __init__(self, ) -> None: ...
    Tmplate: str
    Format: str
    def get_Tmplate(self) -> str: ...
    def set_Tmplate(self, value: str) -> None: ...
    def getTmplate(self) -> str: ...
    def setTmplate(self, val: str) -> None: ...
    def get_Format(self) -> str: ...
    def set_Format(self, value: str) -> None: ...
    def getFormat(self) -> str: ...
    def setFormat(self, val: str) -> None: ...

class DatasetReference:
    def __init__(self, ) -> None: ...
    Name: str
    Info: list[DatasetReferenceInfo]
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Info(self) -> list[DatasetReferenceInfo]: ...
    def set_Info(self, value: list[DatasetReferenceInfo]) -> None: ...
    def getInfo(self) -> System.Collections.ArrayList: ...
    def setInfo(self, val: System.Collections.ArrayList) -> None: ...

class DatasetType(ModelType):
    def __init__(self, ) -> None: ...
    EditTools: list[str]
    ViewTools: list[str]
    References: list[DatasetReference]
    Actions: list[DatasetAction]
    def get_EditTools(self) -> list[str]: ...
    def set_EditTools(self, value: list[str]) -> None: ...
    def getEditTools(self) -> System.Collections.ArrayList: ...
    def setEditTools(self, val: System.Collections.ArrayList) -> None: ...
    def get_ViewTools(self) -> list[str]: ...
    def set_ViewTools(self, value: list[str]) -> None: ...
    def getViewTools(self) -> System.Collections.ArrayList: ...
    def setViewTools(self, val: System.Collections.ArrayList) -> None: ...
    def get_References(self) -> list[DatasetReference]: ...
    def set_References(self, value: list[DatasetReference]) -> None: ...
    def getReferences(self) -> System.Collections.ArrayList: ...
    def setReferences(self, val: System.Collections.ArrayList) -> None: ...
    def get_Actions(self) -> list[DatasetAction]: ...
    def set_Actions(self, value: list[DatasetAction]) -> None: ...
    def getActions(self) -> System.Collections.ArrayList: ...
    def setActions(self, val: System.Collections.ArrayList) -> None: ...

class Index:
    def __init__(self, ) -> None: ...
    Pairs: list[KeyValue]
    def get_Pairs(self) -> list[KeyValue]: ...
    def set_Pairs(self, value: list[KeyValue]) -> None: ...
    def getPairs(self) -> System.Collections.ArrayList: ...
    def setPairs(self, val: System.Collections.ArrayList) -> None: ...

class KeyValue:
    def __init__(self, ) -> None: ...
    Name: str
    Value: str
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Value(self) -> str: ...
    def set_Value(self, value: str) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, val: str) -> None: ...

class L10NData:
    def __init__(self, ) -> None: ...
    Date: str
    IsDateSet: bool
    TcVersion: str
    IsTcVersionSet: bool
    Types: list[TypeL10N]
    Lovs: list[LovL10N]
    def get_Date(self) -> str: ...
    def set_Date(self, value: str) -> None: ...
    def getDate(self) -> str: ...
    def setDate(self, val: str) -> None: ...
    def get_IsDateSet(self) -> bool: ...
    def get_TcVersion(self) -> str: ...
    def set_TcVersion(self, value: str) -> None: ...
    def getTcVersion(self) -> str: ...
    def setTcVersion(self, val: str) -> None: ...
    def get_IsTcVersionSet(self) -> bool: ...
    def get_Types(self) -> list[TypeL10N]: ...
    def set_Types(self, value: list[TypeL10N]) -> None: ...
    def getTypes(self) -> System.Collections.ArrayList: ...
    def setTypes(self, val: System.Collections.ArrayList) -> None: ...
    def get_Lovs(self) -> list[LovL10N]: ...
    def set_Lovs(self, value: list[LovL10N]) -> None: ...
    def getLovs(self) -> System.Collections.ArrayList: ...
    def setLovs(self, val: System.Collections.ArrayList) -> None: ...

class LovData:
    def __init__(self, ) -> None: ...
    Lovs: list[LovInfo]
    def get_Lovs(self) -> list[LovInfo]: ...
    def set_Lovs(self, value: list[LovInfo]) -> None: ...
    def getLovs(self) -> System.Collections.ArrayList: ...
    def setLovs(self, val: System.Collections.ArrayList) -> None: ...

class LovInfo:
    def __init__(self, ) -> None: ...
    Name: str
    AttachedProps: str
    IsAttachedPropsSet: bool
    Uid: str
    AttachedSpecs: str
    IsAttachedSpecsSet: bool
    Usage: str
    BasedOnType: str
    IsBasedOnTypeSet: bool
    TypeName: str
    Description: str
    AttachedTypes: str
    IsAttachedTypesSet: bool
    Values: list[LovValue]
    Range: Bounds
    IsRangeSet: bool
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_AttachedProps(self) -> str: ...
    def set_AttachedProps(self, value: str) -> None: ...
    def getAttachedProps(self) -> str: ...
    def setAttachedProps(self, val: str) -> None: ...
    def get_IsAttachedPropsSet(self) -> bool: ...
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...
    def get_AttachedSpecs(self) -> str: ...
    def set_AttachedSpecs(self, value: str) -> None: ...
    def getAttachedSpecs(self) -> str: ...
    def setAttachedSpecs(self, val: str) -> None: ...
    def get_IsAttachedSpecsSet(self) -> bool: ...
    def get_Usage(self) -> str: ...
    def set_Usage(self, value: str) -> None: ...
    def getUsage(self) -> str: ...
    def setUsage(self, val: str) -> None: ...
    def get_BasedOnType(self) -> str: ...
    def set_BasedOnType(self, value: str) -> None: ...
    def getBasedOnType(self) -> str: ...
    def setBasedOnType(self, val: str) -> None: ...
    def get_IsBasedOnTypeSet(self) -> bool: ...
    def get_TypeName(self) -> str: ...
    def set_TypeName(self, value: str) -> None: ...
    def getTypeName(self) -> str: ...
    def setTypeName(self, val: str) -> None: ...
    def get_Description(self) -> str: ...
    def set_Description(self, value: str) -> None: ...
    def getDescription(self) -> str: ...
    def setDescription(self, val: str) -> None: ...
    def get_AttachedTypes(self) -> str: ...
    def set_AttachedTypes(self, value: str) -> None: ...
    def getAttachedTypes(self) -> str: ...
    def setAttachedTypes(self, val: str) -> None: ...
    def get_IsAttachedTypesSet(self) -> bool: ...
    def get_Values(self) -> list[LovValue]: ...
    def set_Values(self, value: list[LovValue]) -> None: ...
    def getValues(self) -> System.Collections.ArrayList: ...
    def setValues(self, val: System.Collections.ArrayList) -> None: ...
    def get_Range(self) -> Bounds: ...
    def set_Range(self, value: Bounds) -> None: ...
    def getRange(self) -> Bounds: ...
    def setRange(self, val: Bounds) -> None: ...
    def get_IsRangeSet(self) -> bool: ...

class LovL10N:
    def __init__(self, ) -> None: ...
    Uid: str
    UiDescription: str
    IsUiDescriptionSet: bool
    UiName: str
    IsUiNameSet: bool
    Values: list[LovValueL10N]
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...
    def get_UiDescription(self) -> str: ...
    def set_UiDescription(self, value: str) -> None: ...
    def getUiDescription(self) -> str: ...
    def setUiDescription(self, val: str) -> None: ...
    def get_IsUiDescriptionSet(self) -> bool: ...
    def get_UiName(self) -> str: ...
    def set_UiName(self, value: str) -> None: ...
    def getUiName(self) -> str: ...
    def setUiName(self, val: str) -> None: ...
    def get_IsUiNameSet(self) -> bool: ...
    def get_Values(self) -> list[LovValueL10N]: ...
    def set_Values(self, value: list[LovValueL10N]) -> None: ...
    def getValues(self) -> System.Collections.ArrayList: ...
    def setValues(self, val: System.Collections.ArrayList) -> None: ...

class LovReference:
    def __init__(self, ) -> None: ...
    LovTypeUid: str
    IsLovTypeUidSet: bool
    Specifier: str
    ConditionName: str
    Style: str
    LovUid: str
    PropDependents: str
    def get_LovTypeUid(self) -> str: ...
    def set_LovTypeUid(self, value: str) -> None: ...
    def getLovTypeUid(self) -> str: ...
    def setLovTypeUid(self, val: str) -> None: ...
    def get_IsLovTypeUidSet(self) -> bool: ...
    def get_Specifier(self) -> str: ...
    def set_Specifier(self, value: str) -> None: ...
    def getSpecifier(self) -> str: ...
    def setSpecifier(self, val: str) -> None: ...
    def get_ConditionName(self) -> str: ...
    def set_ConditionName(self, value: str) -> None: ...
    def getConditionName(self) -> str: ...
    def setConditionName(self, val: str) -> None: ...
    def get_Style(self) -> str: ...
    def set_Style(self, value: str) -> None: ...
    def getStyle(self) -> str: ...
    def setStyle(self, val: str) -> None: ...
    def get_LovUid(self) -> str: ...
    def set_LovUid(self, value: str) -> None: ...
    def getLovUid(self) -> str: ...
    def setLovUid(self, val: str) -> None: ...
    def get_PropDependents(self) -> str: ...
    def set_PropDependents(self, value: str) -> None: ...
    def getPropDependents(self) -> str: ...
    def setPropDependents(self, val: str) -> None: ...

class LovValueL10N:
    def __init__(self, ) -> None: ...
    Value: str
    UiValue: str
    IsUiValueSet: bool
    def get_Value(self) -> str: ...
    def set_Value(self, value: str) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, val: str) -> None: ...
    def get_UiValue(self) -> str: ...
    def set_UiValue(self, value: str) -> None: ...
    def getUiValue(self) -> str: ...
    def setUiValue(self, val: str) -> None: ...
    def get_IsUiValueSet(self) -> bool: ...

class LovValue:
    def __init__(self, ) -> None: ...
    ConditionName: str
    Description: str
    IsDescriptionSet: bool
    Value: str
    AttachedLov: list[AttachedLov]
    def get_ConditionName(self) -> str: ...
    def set_ConditionName(self, value: str) -> None: ...
    def getConditionName(self) -> str: ...
    def setConditionName(self, val: str) -> None: ...
    def get_Description(self) -> str: ...
    def set_Description(self, value: str) -> None: ...
    def getDescription(self) -> str: ...
    def setDescription(self, val: str) -> None: ...
    def get_IsDescriptionSet(self) -> bool: ...
    def get_Value(self) -> str: ...
    def set_Value(self, value: str) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, val: str) -> None: ...
    def get_AttachedLov(self) -> list[AttachedLov]: ...
    def set_AttachedLov(self, value: list[AttachedLov]) -> None: ...
    def getAttachedLov(self) -> System.Collections.ArrayList: ...
    def setAttachedLov(self, val: System.Collections.ArrayList) -> None: ...

class ModelSchema:
    def __init__(self, ) -> None: ...
    Types: list[ModelType]
    def get_Types(self) -> list[ModelType]: ...
    def set_Types(self, value: list[ModelType]) -> None: ...
    def getTypes(self) -> System.Collections.ArrayList: ...
    def setTypes(self, val: System.Collections.ArrayList) -> None: ...

class ModelType:
    def __init__(self, ) -> None: ...
    OwningType: str
    IsOwningTypeSet: bool
    Name: str
    ParentTypeName: str
    Primary: bool
    IsPrimarySet: bool
    TypeUid: str
    Uid: str
    ClassName: str
    TypeHierarchy: str
    IsTypeHierarchySet: bool
    Abstract: bool
    IsAbstractSet: bool
    DisplayName: str
    IsDisplayNameSet: bool
    PropertyDescriptors: list[PropertyDescriptor]
    Constants: list[Constant]
    RevNameRules: list[RevNameRule]
    Children: list[str]
    def get_OwningType(self) -> str: ...
    def set_OwningType(self, value: str) -> None: ...
    def getOwningType(self) -> str: ...
    def setOwningType(self, val: str) -> None: ...
    def get_IsOwningTypeSet(self) -> bool: ...
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_ParentTypeName(self) -> str: ...
    def set_ParentTypeName(self, value: str) -> None: ...
    def getParentTypeName(self) -> str: ...
    def setParentTypeName(self, val: str) -> None: ...
    def get_Primary(self) -> bool: ...
    def set_Primary(self, value: bool) -> None: ...
    def getPrimary(self) -> bool: ...
    def setPrimary(self, val: bool) -> None: ...
    def get_IsPrimarySet(self) -> bool: ...
    def get_TypeUid(self) -> str: ...
    def set_TypeUid(self, value: str) -> None: ...
    def getTypeUid(self) -> str: ...
    def setTypeUid(self, val: str) -> None: ...
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...
    def get_ClassName(self) -> str: ...
    def set_ClassName(self, value: str) -> None: ...
    def getClassName(self) -> str: ...
    def setClassName(self, val: str) -> None: ...
    def get_TypeHierarchy(self) -> str: ...
    def set_TypeHierarchy(self, value: str) -> None: ...
    def getTypeHierarchy(self) -> str: ...
    def setTypeHierarchy(self, val: str) -> None: ...
    def get_IsTypeHierarchySet(self) -> bool: ...
    def get_Abstract(self) -> bool: ...
    def set_Abstract(self, value: bool) -> None: ...
    def getAbstract(self) -> bool: ...
    def setAbstract(self, val: bool) -> None: ...
    def get_IsAbstractSet(self) -> bool: ...
    def get_DisplayName(self) -> str: ...
    def set_DisplayName(self, value: str) -> None: ...
    def getDisplayName(self) -> str: ...
    def setDisplayName(self, val: str) -> None: ...
    def get_IsDisplayNameSet(self) -> bool: ...
    def get_PropertyDescriptors(self) -> list[PropertyDescriptor]: ...
    def set_PropertyDescriptors(self, value: list[PropertyDescriptor]) -> None: ...
    def getPropertyDescriptors(self) -> System.Collections.ArrayList: ...
    def setPropertyDescriptors(self, val: System.Collections.ArrayList) -> None: ...
    def get_Constants(self) -> list[Constant]: ...
    def set_Constants(self, value: list[Constant]) -> None: ...
    def getConstants(self) -> System.Collections.ArrayList: ...
    def setConstants(self, val: System.Collections.ArrayList) -> None: ...
    def get_RevNameRules(self) -> list[RevNameRule]: ...
    def set_RevNameRules(self, value: list[RevNameRule]) -> None: ...
    def getRevNameRules(self) -> System.Collections.ArrayList: ...
    def setRevNameRules(self, val: System.Collections.ArrayList) -> None: ...
    def get_Children(self) -> list[str]: ...
    def set_Children(self, value: list[str]) -> None: ...
    def getChildren(self) -> System.Collections.ArrayList: ...
    def setChildren(self, val: System.Collections.ArrayList) -> None: ...

class NamingRule:
    def __init__(self, ) -> None: ...
    ConditionName: str
    Caze: str
    Pattern: str
    RulePatterns: list[RulePattern]
    def get_ConditionName(self) -> str: ...
    def set_ConditionName(self, value: str) -> None: ...
    def getConditionName(self) -> str: ...
    def setConditionName(self, val: str) -> None: ...
    def get_Caze(self) -> str: ...
    def set_Caze(self, value: str) -> None: ...
    def getCaze(self) -> str: ...
    def setCaze(self, val: str) -> None: ...
    def get_Pattern(self) -> str: ...
    def set_Pattern(self, value: str) -> None: ...
    def getPattern(self) -> str: ...
    def setPattern(self, val: str) -> None: ...
    def get_RulePatterns(self) -> list[RulePattern]: ...
    def set_RulePatterns(self, value: list[RulePattern]) -> None: ...
    def getRulePatterns(self) -> System.Collections.ArrayList: ...
    def setRulePatterns(self, val: System.Collections.ArrayList) -> None: ...

class PropertyDescriptor:
    def __init__(self, ) -> None: ...
    Name: str
    MaxLength: int
    IsMaxLengthSet: bool
    PropertyType: int
    LovCategory: int
    CompoundObjType: str
    IsCompoundObjTypeSet: bool
    ValueType: int
    MaxArraySize: int
    IsMaxArraySizeSet: bool
    FieldType: int
    IsFieldTypeSet: bool
    MaxValue: str
    IsMaxValueSet: bool
    AnArray: bool
    MinValue: str
    IsMinValueSet: bool
    DisplayName: str
    IsDisplayNameSet: bool
    PropertyType2: int
    IsPropertyType2Set: bool
    Lovs: list[LovReference]
    NamingRules: list[NamingRule]
    BasedOn: BasedOn
    IsBasedOnSet: bool
    Constants: list[Constant]
    Renderers: list[Renderer]
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_MaxLength(self) -> int: ...
    def set_MaxLength(self, value: int) -> None: ...
    def getMaxLength(self) -> int: ...
    def setMaxLength(self, val: int) -> None: ...
    def get_IsMaxLengthSet(self) -> bool: ...
    def get_PropertyType(self) -> int: ...
    def set_PropertyType(self, value: int) -> None: ...
    def getPropertyType(self) -> int: ...
    def setPropertyType(self, val: int) -> None: ...
    def get_LovCategory(self) -> int: ...
    def set_LovCategory(self, value: int) -> None: ...
    def getLovCategory(self) -> int: ...
    def setLovCategory(self, val: int) -> None: ...
    def get_CompoundObjType(self) -> str: ...
    def set_CompoundObjType(self, value: str) -> None: ...
    def getCompoundObjType(self) -> str: ...
    def setCompoundObjType(self, val: str) -> None: ...
    def get_IsCompoundObjTypeSet(self) -> bool: ...
    def get_ValueType(self) -> int: ...
    def set_ValueType(self, value: int) -> None: ...
    def getValueType(self) -> int: ...
    def setValueType(self, val: int) -> None: ...
    def get_MaxArraySize(self) -> int: ...
    def set_MaxArraySize(self, value: int) -> None: ...
    def getMaxArraySize(self) -> int: ...
    def setMaxArraySize(self, val: int) -> None: ...
    def get_IsMaxArraySizeSet(self) -> bool: ...
    def get_FieldType(self) -> int: ...
    def set_FieldType(self, value: int) -> None: ...
    def getFieldType(self) -> int: ...
    def setFieldType(self, val: int) -> None: ...
    def get_IsFieldTypeSet(self) -> bool: ...
    def get_MaxValue(self) -> str: ...
    def set_MaxValue(self, value: str) -> None: ...
    def getMaxValue(self) -> str: ...
    def setMaxValue(self, val: str) -> None: ...
    def get_IsMaxValueSet(self) -> bool: ...
    def get_AnArray(self) -> bool: ...
    def set_AnArray(self, value: bool) -> None: ...
    def getAnArray(self) -> bool: ...
    def setAnArray(self, val: bool) -> None: ...
    def get_MinValue(self) -> str: ...
    def set_MinValue(self, value: str) -> None: ...
    def getMinValue(self) -> str: ...
    def setMinValue(self, val: str) -> None: ...
    def get_IsMinValueSet(self) -> bool: ...
    def get_DisplayName(self) -> str: ...
    def set_DisplayName(self, value: str) -> None: ...
    def getDisplayName(self) -> str: ...
    def setDisplayName(self, val: str) -> None: ...
    def get_IsDisplayNameSet(self) -> bool: ...
    def get_PropertyType2(self) -> int: ...
    def set_PropertyType2(self, value: int) -> None: ...
    def getPropertyType2(self) -> int: ...
    def setPropertyType2(self, val: int) -> None: ...
    def get_IsPropertyType2Set(self) -> bool: ...
    def get_Lovs(self) -> list[LovReference]: ...
    def set_Lovs(self, value: list[LovReference]) -> None: ...
    def getLovs(self) -> System.Collections.ArrayList: ...
    def setLovs(self, val: System.Collections.ArrayList) -> None: ...
    def get_NamingRules(self) -> list[NamingRule]: ...
    def set_NamingRules(self, value: list[NamingRule]) -> None: ...
    def getNamingRules(self) -> System.Collections.ArrayList: ...
    def setNamingRules(self, val: System.Collections.ArrayList) -> None: ...
    def get_BasedOn(self) -> BasedOn: ...
    def set_BasedOn(self, value: BasedOn) -> None: ...
    def getBasedOn(self) -> BasedOn: ...
    def setBasedOn(self, val: BasedOn) -> None: ...
    def get_IsBasedOnSet(self) -> bool: ...
    def get_Constants(self) -> list[Constant]: ...
    def set_Constants(self, value: list[Constant]) -> None: ...
    def getConstants(self) -> System.Collections.ArrayList: ...
    def setConstants(self, val: System.Collections.ArrayList) -> None: ...
    def get_Renderers(self) -> list[Renderer]: ...
    def set_Renderers(self, value: list[Renderer]) -> None: ...
    def getRenderers(self) -> System.Collections.ArrayList: ...
    def setRenderers(self, val: System.Collections.ArrayList) -> None: ...

class PropertyL10N:
    def __init__(self, ) -> None: ...
    Name: str
    UiName: str
    IsUiNameSet: bool
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_UiName(self) -> str: ...
    def set_UiName(self, value: str) -> None: ...
    def getUiName(self) -> str: ...
    def setUiName(self, val: str) -> None: ...
    def get_IsUiNameSet(self) -> bool: ...

class Renderer:
    def __init__(self, ) -> None: ...
    ConditionName: str
    RenderData: str
    def get_ConditionName(self) -> str: ...
    def set_ConditionName(self, value: str) -> None: ...
    def getConditionName(self) -> str: ...
    def setConditionName(self, val: str) -> None: ...
    def get_RenderData(self) -> str: ...
    def set_RenderData(self, value: str) -> None: ...
    def getRenderData(self) -> str: ...
    def setRenderData(self, val: str) -> None: ...

class RevNameRule:
    def __init__(self, ) -> None: ...
    ExcludeSkipLetters: bool
    Name: str
    SupplementalType: int
    IsSupplementalTypeSet: bool
    SecondaryDescription: str
    IsSecondaryDescriptionSet: bool
    SecondaryStartRevision: str
    IsSecondaryStartRevisionSet: bool
    SkipLetters: str
    IsSkipLettersSet: bool
    StartRevision: str
    Type: int
    SecondaryType: int
    IsSecondaryTypeSet: bool
    AlphabecticCase: int
    IsAlphabecticCaseSet: bool
    ConditionName: str
    Description: str
    IsDescriptionSet: bool
    def get_ExcludeSkipLetters(self) -> bool: ...
    def set_ExcludeSkipLetters(self, value: bool) -> None: ...
    def getExcludeSkipLetters(self) -> bool: ...
    def setExcludeSkipLetters(self, val: bool) -> None: ...
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_SupplementalType(self) -> int: ...
    def set_SupplementalType(self, value: int) -> None: ...
    def getSupplementalType(self) -> int: ...
    def setSupplementalType(self, val: int) -> None: ...
    def get_IsSupplementalTypeSet(self) -> bool: ...
    def get_SecondaryDescription(self) -> str: ...
    def set_SecondaryDescription(self, value: str) -> None: ...
    def getSecondaryDescription(self) -> str: ...
    def setSecondaryDescription(self, val: str) -> None: ...
    def get_IsSecondaryDescriptionSet(self) -> bool: ...
    def get_SecondaryStartRevision(self) -> str: ...
    def set_SecondaryStartRevision(self, value: str) -> None: ...
    def getSecondaryStartRevision(self) -> str: ...
    def setSecondaryStartRevision(self, val: str) -> None: ...
    def get_IsSecondaryStartRevisionSet(self) -> bool: ...
    def get_SkipLetters(self) -> str: ...
    def set_SkipLetters(self, value: str) -> None: ...
    def getSkipLetters(self) -> str: ...
    def setSkipLetters(self, val: str) -> None: ...
    def get_IsSkipLettersSet(self) -> bool: ...
    def get_StartRevision(self) -> str: ...
    def set_StartRevision(self, value: str) -> None: ...
    def getStartRevision(self) -> str: ...
    def setStartRevision(self, val: str) -> None: ...
    def get_Type(self) -> int: ...
    def set_Type(self, value: int) -> None: ...
    def getType(self) -> int: ...
    def setType(self, val: int) -> None: ...
    def get_SecondaryType(self) -> int: ...
    def set_SecondaryType(self, value: int) -> None: ...
    def getSecondaryType(self) -> int: ...
    def setSecondaryType(self, val: int) -> None: ...
    def get_IsSecondaryTypeSet(self) -> bool: ...
    def get_AlphabecticCase(self) -> int: ...
    def set_AlphabecticCase(self, value: int) -> None: ...
    def getAlphabecticCase(self) -> int: ...
    def setAlphabecticCase(self, val: int) -> None: ...
    def get_IsAlphabecticCaseSet(self) -> bool: ...
    def get_ConditionName(self) -> str: ...
    def set_ConditionName(self, value: str) -> None: ...
    def getConditionName(self) -> str: ...
    def setConditionName(self, val: str) -> None: ...
    def get_Description(self) -> str: ...
    def set_Description(self, value: str) -> None: ...
    def getDescription(self) -> str: ...
    def setDescription(self, val: str) -> None: ...
    def get_IsDescriptionSet(self) -> bool: ...

class RulePattern:
    def __init__(self, ) -> None: ...
    InitialValue: int
    Autogenerated: bool
    Pattern: str
    MaxValue: int
    def get_InitialValue(self) -> int: ...
    def set_InitialValue(self, value: int) -> None: ...
    def getInitialValue(self) -> int: ...
    def setInitialValue(self, val: int) -> None: ...
    def get_Autogenerated(self) -> bool: ...
    def set_Autogenerated(self, value: bool) -> None: ...
    def getAutogenerated(self) -> bool: ...
    def setAutogenerated(self, val: bool) -> None: ...
    def get_Pattern(self) -> str: ...
    def set_Pattern(self, value: str) -> None: ...
    def getPattern(self) -> str: ...
    def setPattern(self, val: str) -> None: ...
    def get_MaxValue(self) -> int: ...
    def set_MaxValue(self, value: int) -> None: ...
    def getMaxValue(self) -> int: ...
    def setMaxValue(self, val: int) -> None: ...

class ToolData:
    def __init__(self, ) -> None: ...
    Date: str
    IsDateSet: bool
    TcVersion: str
    IsTcVersionSet: bool
    Tools: list[Tool]
    def get_Date(self) -> str: ...
    def set_Date(self, value: str) -> None: ...
    def getDate(self) -> str: ...
    def setDate(self, val: str) -> None: ...
    def get_IsDateSet(self) -> bool: ...
    def get_TcVersion(self) -> str: ...
    def set_TcVersion(self, value: str) -> None: ...
    def getTcVersion(self) -> str: ...
    def setTcVersion(self, val: str) -> None: ...
    def get_IsTcVersionSet(self) -> bool: ...
    def get_Tools(self) -> list[Tool]: ...
    def set_Tools(self, value: list[Tool]) -> None: ...
    def getTools(self) -> System.Collections.ArrayList: ...
    def setTools(self, val: System.Collections.ArrayList) -> None: ...

class Tool:
    def __init__(self, ) -> None: ...
    Version: str
    IsVersionSet: bool
    MimeType: str
    IsMimeTypeSet: bool
    CallbackEnabled: bool
    IsCallbackEnabledSet: bool
    LaunchCommandMac: str
    IsLaunchCommandMacSet: bool
    LaunchCommandWin: str
    IsLaunchCommandWinSet: bool
    VviRequired: bool
    IsVviRequiredSet: bool
    ToolUid: str
    IsToolUidSet: bool
    DownloadRequired: bool
    IsDownloadRequiredSet: bool
    VendorName: str
    IsVendorNameSet: bool
    PackageName: str
    IsPackageNameSet: bool
    Symbol: str
    Description: str
    IsDescriptionSet: bool
    MarkupCapable: bool
    IsMarkupCapableSet: bool
    ReleaseDate: str
    IsReleaseDateSet: bool
    ViewCapable: bool
    IsViewCapableSet: bool
    DigitalSignatureCapable: bool
    IsDigitalSignatureCapableSet: bool
    EmbedApplication: bool
    IsEmbedApplicationSet: bool
    Name: str
    InputFormats: list[str]
    OutputFormats: list[str]
    def get_Version(self) -> str: ...
    def set_Version(self, value: str) -> None: ...
    def getVersion(self) -> str: ...
    def setVersion(self, val: str) -> None: ...
    def get_IsVersionSet(self) -> bool: ...
    def get_MimeType(self) -> str: ...
    def set_MimeType(self, value: str) -> None: ...
    def getMimeType(self) -> str: ...
    def setMimeType(self, val: str) -> None: ...
    def get_IsMimeTypeSet(self) -> bool: ...
    def get_CallbackEnabled(self) -> bool: ...
    def set_CallbackEnabled(self, value: bool) -> None: ...
    def getCallbackEnabled(self) -> bool: ...
    def setCallbackEnabled(self, val: bool) -> None: ...
    def get_IsCallbackEnabledSet(self) -> bool: ...
    def get_LaunchCommandMac(self) -> str: ...
    def set_LaunchCommandMac(self, value: str) -> None: ...
    def getLaunchCommandMac(self) -> str: ...
    def setLaunchCommandMac(self, val: str) -> None: ...
    def get_IsLaunchCommandMacSet(self) -> bool: ...
    def get_LaunchCommandWin(self) -> str: ...
    def set_LaunchCommandWin(self, value: str) -> None: ...
    def getLaunchCommandWin(self) -> str: ...
    def setLaunchCommandWin(self, val: str) -> None: ...
    def get_IsLaunchCommandWinSet(self) -> bool: ...
    def get_VviRequired(self) -> bool: ...
    def set_VviRequired(self, value: bool) -> None: ...
    def getVviRequired(self) -> bool: ...
    def setVviRequired(self, val: bool) -> None: ...
    def get_IsVviRequiredSet(self) -> bool: ...
    def get_ToolUid(self) -> str: ...
    def set_ToolUid(self, value: str) -> None: ...
    def getToolUid(self) -> str: ...
    def setToolUid(self, val: str) -> None: ...
    def get_IsToolUidSet(self) -> bool: ...
    def get_DownloadRequired(self) -> bool: ...
    def set_DownloadRequired(self, value: bool) -> None: ...
    def getDownloadRequired(self) -> bool: ...
    def setDownloadRequired(self, val: bool) -> None: ...
    def get_IsDownloadRequiredSet(self) -> bool: ...
    def get_VendorName(self) -> str: ...
    def set_VendorName(self, value: str) -> None: ...
    def getVendorName(self) -> str: ...
    def setVendorName(self, val: str) -> None: ...
    def get_IsVendorNameSet(self) -> bool: ...
    def get_PackageName(self) -> str: ...
    def set_PackageName(self, value: str) -> None: ...
    def getPackageName(self) -> str: ...
    def setPackageName(self, val: str) -> None: ...
    def get_IsPackageNameSet(self) -> bool: ...
    def get_Symbol(self) -> str: ...
    def set_Symbol(self, value: str) -> None: ...
    def getSymbol(self) -> str: ...
    def setSymbol(self, val: str) -> None: ...
    def get_Description(self) -> str: ...
    def set_Description(self, value: str) -> None: ...
    def getDescription(self) -> str: ...
    def setDescription(self, val: str) -> None: ...
    def get_IsDescriptionSet(self) -> bool: ...
    def get_MarkupCapable(self) -> bool: ...
    def set_MarkupCapable(self, value: bool) -> None: ...
    def getMarkupCapable(self) -> bool: ...
    def setMarkupCapable(self, val: bool) -> None: ...
    def get_IsMarkupCapableSet(self) -> bool: ...
    def get_ReleaseDate(self) -> str: ...
    def set_ReleaseDate(self, value: str) -> None: ...
    def getReleaseDate(self) -> str: ...
    def setReleaseDate(self, val: str) -> None: ...
    def get_IsReleaseDateSet(self) -> bool: ...
    def get_ViewCapable(self) -> bool: ...
    def set_ViewCapable(self, value: bool) -> None: ...
    def getViewCapable(self) -> bool: ...
    def setViewCapable(self, val: bool) -> None: ...
    def get_IsViewCapableSet(self) -> bool: ...
    def get_DigitalSignatureCapable(self) -> bool: ...
    def set_DigitalSignatureCapable(self, value: bool) -> None: ...
    def getDigitalSignatureCapable(self) -> bool: ...
    def setDigitalSignatureCapable(self, val: bool) -> None: ...
    def get_IsDigitalSignatureCapableSet(self) -> bool: ...
    def get_EmbedApplication(self) -> bool: ...
    def set_EmbedApplication(self, value: bool) -> None: ...
    def getEmbedApplication(self) -> bool: ...
    def setEmbedApplication(self, val: bool) -> None: ...
    def get_IsEmbedApplicationSet(self) -> bool: ...
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_InputFormats(self) -> list[str]: ...
    def set_InputFormats(self, value: list[str]) -> None: ...
    def getInputFormats(self) -> System.Collections.ArrayList: ...
    def setInputFormats(self, val: System.Collections.ArrayList) -> None: ...
    def get_OutputFormats(self) -> list[str]: ...
    def set_OutputFormats(self, value: list[str]) -> None: ...
    def getOutputFormats(self) -> System.Collections.ArrayList: ...
    def setOutputFormats(self, val: System.Collections.ArrayList) -> None: ...

class TypeL10N:
    def __init__(self, ) -> None: ...
    Name: str
    UiName: str
    IsUiNameSet: bool
    PropertyDescriptors: list[PropertyL10N]
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_UiName(self) -> str: ...
    def set_UiName(self, value: str) -> None: ...
    def getUiName(self) -> str: ...
    def setUiName(self, val: str) -> None: ...
    def get_IsUiNameSet(self) -> bool: ...
    def get_PropertyDescriptors(self) -> list[PropertyL10N]: ...
    def set_PropertyDescriptors(self, value: list[PropertyL10N]) -> None: ...
    def getPropertyDescriptors(self) -> System.Collections.ArrayList: ...
    def setPropertyDescriptors(self, val: System.Collections.ArrayList) -> None: ...

class TypeSchema:
    def __init__(self, ) -> None: ...
    Types: list[ModelType]
    Lovs: list[LovInfo]
    Tools: list[Tool]
    def get_Types(self) -> list[ModelType]: ...
    def set_Types(self, value: list[ModelType]) -> None: ...
    def getTypes(self) -> System.Collections.ArrayList: ...
    def setTypes(self, val: System.Collections.ArrayList) -> None: ...
    def get_Lovs(self) -> list[LovInfo]: ...
    def set_Lovs(self, value: list[LovInfo]) -> None: ...
    def getLovs(self) -> System.Collections.ArrayList: ...
    def setLovs(self, val: System.Collections.ArrayList) -> None: ...
    def get_Tools(self) -> list[Tool]: ...
    def set_Tools(self, value: list[Tool]) -> None: ...
    def getTools(self) -> System.Collections.ArrayList: ...
    def setTools(self, val: System.Collections.ArrayList) -> None: ...

