import Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement
import Smc0.Services.Internal.Strong.Structuremanagement._2021_06.SolutionVariantManagement
import Smc0.Services.Internal.Strong.Structuremanagement._2023_06.SolutionVariantManagement
import System
import System.Collections
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong

class SolutionVariantManagementRestBindingStub(SolutionVariantManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateMultilevelSolutionVariants(self, CreateMultilevelSVInputList: list[Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateMultilevelSVInput], CreateMultilevelSVConfigParam: Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateMultilevelSVConfigParam) -> Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateMultilevelSVResponse: ...
    def CreateSolutionVariantItems(self, CreateSVItemInputList: list[Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateSVItemInput], ConfigCriteria: Teamcenter.Soa.Client.Model.Strong.Cfg0AbsConfiguratorCriteria) -> Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateSVItemResponse: ...
    def LoadSolutionVariantItems(self, SvItemObjectsToBeLoadedList: System.Collections.Hashtable) -> Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.LoadSVItemResponse: ...
    def SearchSolutionVariantItems(self, SourceBOMLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], SearchParameter: Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.SearchParameter) -> Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.SearchSVItemsResponse: ...
    def CreateBOMLineVariantRule(self, BomLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, Validate: bool, CheckCompleteness: bool, SaveVariantRule: bool, VariantRuleName: str, RequestPreferences: System.Collections.Hashtable) -> Smc0.Services.Internal.Strong.Structuremanagement._2021_06.SolutionVariantManagement.CreateBOMLineVariantRuleResponse: ...
    def FindOrCreateSolutionVariantUsages(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], RunInBackground: bool) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetVariantRulesAndSolVariants(self, Input: Smc0.Services.Internal.Strong.Structuremanagement._2023_06.SolutionVariantManagement.VariantRulesAndSolVariantsInput) -> Smc0.Services.Internal.Strong.Structuremanagement._2023_06.SolutionVariantManagement.VariantRulesAndSolVariantsOutput: ...

class SolutionVariantManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> SolutionVariantManagementService: ...
    def CreateMultilevelSolutionVariants(self, CreateMultilevelSVInputList: list[Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateMultilevelSVInput], CreateMultilevelSVConfigParam: Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateMultilevelSVConfigParam) -> Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateMultilevelSVResponse: ...
    def CreateSolutionVariantItems(self, CreateSVItemInputList: list[Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateSVItemInput], ConfigCriteria: Teamcenter.Soa.Client.Model.Strong.Cfg0AbsConfiguratorCriteria) -> Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.CreateSVItemResponse: ...
    def LoadSolutionVariantItems(self, SvItemObjectsToBeLoadedList: System.Collections.Hashtable) -> Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.LoadSVItemResponse: ...
    def SearchSolutionVariantItems(self, SourceBOMLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], SearchParameter: Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.SearchParameter) -> Smc0.Services.Internal.Strong.Structuremanagement._2018_06.SolutionVariantManagement.SearchSVItemsResponse: ...
    def CreateBOMLineVariantRule(self, BomLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, Validate: bool, CheckCompleteness: bool, SaveVariantRule: bool, VariantRuleName: str, RequestPreferences: System.Collections.Hashtable) -> Smc0.Services.Internal.Strong.Structuremanagement._2021_06.SolutionVariantManagement.CreateBOMLineVariantRuleResponse: ...
    def FindOrCreateSolutionVariantUsages(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], RunInBackground: bool) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetVariantRulesAndSolVariants(self, Input: Smc0.Services.Internal.Strong.Structuremanagement._2023_06.SolutionVariantManagement.VariantRulesAndSolVariantsInput) -> Smc0.Services.Internal.Strong.Structuremanagement._2023_06.SolutionVariantManagement.VariantRulesAndSolVariantsOutput: ...

