import Serilog.Formatting
import System
import System.Collections.Generic
import System.Net
import System.Net.Security
import System.Threading.Tasks

class EmailConnectionInfo:
    def __init__(self, ) -> None: ...
    DefaultSubject: str
    NetworkCredentials: System.Net.ICredentialsByHost
    Port: int
    FromEmail: str
    ToEmail: str
    EmailSubject: str
    EnableSsl: bool
    ServerCertificateValidationCallback: System.Net.Security.RemoteCertificateValidationCallback
    MailServer: str
    IsBodyHtml: bool
    def get_NetworkCredentials(self) -> System.Net.ICredentialsByHost: ...
    def set_NetworkCredentials(self, value: System.Net.ICredentialsByHost) -> None: ...
    def get_Port(self) -> int: ...
    def set_Port(self, value: int) -> None: ...
    def get_FromEmail(self) -> str: ...
    def set_FromEmail(self, value: str) -> None: ...
    def get_ToEmail(self) -> str: ...
    def set_ToEmail(self, value: str) -> None: ...
    def get_EmailSubject(self) -> str: ...
    def set_EmailSubject(self, value: str) -> None: ...
    def get_EnableSsl(self) -> bool: ...
    def set_EnableSsl(self, value: bool) -> None: ...
    def get_ServerCertificateValidationCallback(self) -> System.Net.Security.RemoteCertificateValidationCallback: ...
    def set_ServerCertificateValidationCallback(self, value: System.Net.Security.RemoteCertificateValidationCallback) -> None: ...
    def get_MailServer(self) -> str: ...
    def set_MailServer(self, value: str) -> None: ...
    def get_IsBodyHtml(self) -> bool: ...
    def set_IsBodyHtml(self, value: bool) -> None: ...

class EmailSink:
    def __init__(self, connectionInfo: EmailConnectionInfo, textFormatter: Serilog.Formatting.ITextFormatter, subjectLineFormatter: Serilog.Formatting.ITextFormatter) -> None: ...
    def Dispose(self) -> None: ...
    def EmitBatchAsync(self, events: list[Serilog.Events.LogEvent]) -> System.Threading.Tasks.Task: ...
    def OnEmptyBatchAsync(self) -> System.Threading.Tasks.Task: ...

class <>c:
    def __init__(self, ) -> None: ...
    <>9: <>c
    <>9__7_0: dict[Serilog.Events.LogEvent, Serilog.Events.LogEventLevel]

