import System
import Teamcenter.Services.Strong.Query._2007_09.SavedQuery
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong
import typing

class QueryInput:
    """
    
The information about each Saved Query to be processed is provided  by way of
this
data structure.
    """
    def __init__(self, ) -> None: ...
    Query: Teamcenter.Soa.Client.Model.Strong.ImanQuery
    """The saved query object to be executed."""
    Entries: list[str]
    """
            The names of criteria. They are User Entry Name of the query seen in Query Builder, not User Entry L10N Key.
            To get User Entry Name in different local, use com.teamcenter.rac.kernel.TcTextService.getTextValue()
            for Teamcenter rich client customization, use com.teamcenter.services.strong.core._2008_06.Session.getDisplayStrings()
            for Teamcenter service customization.
            
"""
    Values: list[str]
    """The values of criteria."""
    LimitList: list[Teamcenter.Soa.Client.Model.ModelObject]
    """
            A list of objects (optional) against which the search is conducted, if the list is
            empty, search will be conducted against the database.
            """
    MaxNumToReturn: int
    """A specified maximum number of matches to be returned, 0 means no limit."""
    ResultsType: int
    """
            The type of results expected from this operation: 0 (top-level objects only), 1 (top-level
            objects plus children: Hierarchical/Indented results), 2 (default value as specified
            on the query object).
            """
    RequestId: str
    """
            Unique ID used to register the query execution task. This can be used by the caller
            to cancel the time consuming query, the value can be generated by any unique string
            generator.
            """
    ClientId: str
    """
            This unique ID is used to identify return data elements and partial errors associated
            with this input structure.
            """

class SavedQuery:
    """
    Interface SavedQuery
    """
    def __init__(self , *args: typing.Any) -> None: ...
    def ExecuteSavedQueries(self, Input: list[QueryInput]) -> Teamcenter.Services.Strong.Query._2007_09.SavedQuery.SavedQueriesResponse:
        """    
             Executes a set of saved queries of following type  QRY_RUN_BY_TC ( 0 ),QRY_RUN_BY_USER_QUERY
             ( 16 ), QRY_RUN_BY_KEYWORD_SEARCH ( 24 ).   The saved queries can be executed to
             yield results in 2 modes:  - Flat mode: In this traditional execution mode, only
             the first-level  objects (corresponding to the queried class) satisfying the query
             are returned  - Hierarchical/Indented mode: This mode is only applicable for  saved
             queries that allow Hierarchical/Indented results. In this  execution mode, the first-level
             objects as well as any sub-level  objects satisfying the query criteria are returned.
             The hierarchy  level information is also returned so that result subsets can be
             re-constructed using the resulting objects.   This service will retun the matched
             object UIDs.   After fetching UIDs, client need to call DataManagementService.loadObjects
             operation  to load objects by pages.  See the QueryInput and QueryResults data structures
             for  usage details.
             

Teamcenter Component:

             Search - The capabilities to allow searching objects using the business object symantics
             that have been persisted via the persistence management.
             
        :param Input: 
                         A set of QueryInput data structures.
             
        :return: contains (1) a set of QueryResults  data structures and (2) a ServiceData.  Partial
             errors are stored and referenced by input vector indexes.
        """
        ...

