import Ods0.Services.Internal.Strong.Objectdataservices._2020_04.ObjectDataServices
import Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices
import System
import Teamcenter.Soa.Client

class ObjectDataServicesRestBindingStub(ObjectDataServicesService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def FindObjects(self, Input: list[Ods0.Services.Internal.Strong.Objectdataservices._2020_04.ObjectDataServices.Operand]) -> Ods0.Services.Internal.Strong.Objectdataservices._2020_04.ObjectDataServices.ReturnObjects: ...
    def FindObjects2(self, Input: list[Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.OperandAndOperator]) -> Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.ReturnObjects2: ...

class ObjectDataServicesService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ObjectDataServicesService: ...
    def FindObjects(self, Input: list[Ods0.Services.Internal.Strong.Objectdataservices._2020_04.ObjectDataServices.Operand]) -> Ods0.Services.Internal.Strong.Objectdataservices._2020_04.ObjectDataServices.ReturnObjects: ...
    def FindObjects2(self, Input: list[Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.OperandAndOperator]) -> Ods0.Services.Internal.Strong.Objectdataservices._2020_12.ObjectDataServices.ReturnObjects2: ...

