import System
import System.Collections

class SharedClientIDs:
    def __init__(self, ) -> None: ...
    SharedClients: list[str]
    def get_SharedClients(self) -> list[str]: ...
    def set_SharedClients(self, value: list[str]) -> None: ...
    def getSharedClients(self) -> System.Collections.ArrayList: ...
    def setSharedClients(self, val: System.Collections.ArrayList) -> None: ...

class SharedClientIDs:
    def __init__(self, ) -> None: ...
    SharedClients: list[str]
    def get_SharedClients(self) -> list[str]: ...
    def set_SharedClients(self, value: list[str]) -> None: ...
    def getSharedClients(self) -> System.Collections.ArrayList: ...
    def setSharedClients(self, val: System.Collections.ArrayList) -> None: ...

