import System
import Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained
import Teamcenter.Soa.Client

class AsMaintainedRestBindingStub(AsMaintainedService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def AsmBomCompare(self, Info: list[Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.ASMBomCompareInfo]) -> Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.ASMBomCompareResponse: ...
    def CreateMROBOMWindows(self, Info: list[Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.CreateMROBOMWindowsInfo]) -> Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.CreateMROBOMWindowsResponse: ...
    def GetAllAsmOpenUsage(self, UsageInput: list[Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.GetAllAsmOpenUsageInputInfo]) -> Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.GetAllAsmOpenUsageResponse: ...

class AsMaintainedService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> AsMaintainedService: ...
    def AsmBomCompare(self, Info: list[Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.ASMBomCompareInfo]) -> Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.ASMBomCompareResponse: ...
    def CreateMROBOMWindows(self, Info: list[Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.CreateMROBOMWindowsInfo]) -> Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.CreateMROBOMWindowsResponse: ...
    def GetAllAsmOpenUsage(self, UsageInput: list[Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.GetAllAsmOpenUsageInputInfo]) -> Teamcenter.Services.Internal.Strong.Asmaintained._2009_06.AsMaintained.GetAllAsmOpenUsageResponse: ...

