import System
import Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement
import Teamcenter.Services.Internal.Strong.Cad._2008_05.DataManagement
import Teamcenter.Services.Internal.Strong.Cad._2008_06.DataManagement
import Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement
import Teamcenter.Services.Internal.Strong.Cad._2013_05.DataManagement
import Teamcenter.Services.Internal.Strong.Cad._2017_05.StructureManagement
import Teamcenter.Services.Strong.Cad._2008_03.DataManagement
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class DataManagementRestBindingStub(DataManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateAppUidObjects(self, Count: int) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ExportConfiguredNXAssembly(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement.ExportConfiguredNXAssemblyInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement.ExportConfiguredNXAssemblyResponse: ...
    def ResolveAttrMappingsForNX(self, Info: list[Teamcenter.Services.Strong.Cad._2008_03.DataManagement.ResolveAttrMappingsInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2008_05.DataManagement.ResolveAttrMappingsForNXResponse: ...
    def QueryRelatedFeatures(self, FeatureQueryInfos: list[Teamcenter.Services.Internal.Strong.Cad._2008_06.DataManagement.FeatureQueryInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2008_06.DataManagement.QueryRelatedFeaturesResponse: ...
    def Revise(self, Info: list[Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement.ReviseInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement.ReviseResponse: ...
    def SaveAsNewItem(self, Info: list[Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement.SaveAsNewItemInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement.SaveAsNewItemResponse: ...
    def QueryPartRelatedFeatures(self, FeatureQueryInfo: list[Teamcenter.Services.Internal.Strong.Cad._2013_05.DataManagement.FeatureQueryInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2013_05.DataManagement.QueryPartRelatedFeaturesResponse: ...

class DataManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> DataManagementService: ...
    def CreateAppUidObjects(self, Count: int) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ExportConfiguredNXAssembly(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement.ExportConfiguredNXAssemblyInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2008_03.DataManagement.ExportConfiguredNXAssemblyResponse: ...
    def ResolveAttrMappingsForNX(self, Info: list[Teamcenter.Services.Strong.Cad._2008_03.DataManagement.ResolveAttrMappingsInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2008_05.DataManagement.ResolveAttrMappingsForNXResponse: ...
    def QueryRelatedFeatures(self, FeatureQueryInfos: list[Teamcenter.Services.Internal.Strong.Cad._2008_06.DataManagement.FeatureQueryInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2008_06.DataManagement.QueryRelatedFeaturesResponse: ...
    def Revise(self, Info: list[Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement.ReviseInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement.ReviseResponse: ...
    def SaveAsNewItem(self, Info: list[Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement.SaveAsNewItemInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2010_04.DataManagement.SaveAsNewItemResponse: ...
    def QueryPartRelatedFeatures(self, FeatureQueryInfo: list[Teamcenter.Services.Internal.Strong.Cad._2013_05.DataManagement.FeatureQueryInfo]) -> Teamcenter.Services.Internal.Strong.Cad._2013_05.DataManagement.QueryPartRelatedFeaturesResponse: ...

class StructureManagementRestBindingStub(StructureManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetProductStructureArrangements(self, PsArrInput: list[Teamcenter.Services.Internal.Strong.Cad._2017_05.StructureManagement.ProductStructureArrangementInput]) -> Teamcenter.Services.Internal.Strong.Cad._2017_05.StructureManagement.GetProductStructureArrangementsResp: ...

class StructureManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureManagementService: ...
    def GetProductStructureArrangements(self, PsArrInput: list[Teamcenter.Services.Internal.Strong.Cad._2017_05.StructureManagement.ProductStructureArrangementInput]) -> Teamcenter.Services.Internal.Strong.Cad._2017_05.StructureManagement.GetProductStructureArrangementsResp: ...

