import Rlz0.Services.Internal.Strong.Realization._2016_05.Search
import Rlz0.Services.Internal.Strong.Realization._2016_10.RealizationManagement
import System
import Teamcenter.Soa.Client

class RealizationManagementRestBindingStub(RealizationManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateRelations(self, Input: list[Rlz0.Services.Internal.Strong.Realization._2016_10.RealizationManagement.Relationship]) -> Rlz0.Services.Internal.Strong.Realization._2016_10.RealizationManagement.CreateRelationsResponse: ...

class RealizationManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> RealizationManagementService: ...
    def CreateRelations(self, Input: list[Rlz0.Services.Internal.Strong.Realization._2016_10.RealizationManagement.Relationship]) -> Rlz0.Services.Internal.Strong.Realization._2016_10.RealizationManagement.CreateRelationsResponse: ...

class SearchRestBindingStub(SearchService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ExecuteSearchInComposition(self, Recipe: Rlz0.Services.Internal.Strong.Realization._2016_05.Search.SearchRecipe, Options: Rlz0.Services.Internal.Strong.Realization._2016_05.Search.SearchOptions) -> Rlz0.Services.Internal.Strong.Realization._2016_05.Search.SearchResponse: ...

class SearchService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> SearchService: ...
    def ExecuteSearchInComposition(self, Recipe: Rlz0.Services.Internal.Strong.Realization._2016_05.Search.SearchRecipe, Options: Rlz0.Services.Internal.Strong.Realization._2016_05.Search.SearchOptions) -> Rlz0.Services.Internal.Strong.Realization._2016_05.Search.SearchResponse: ...

