import System
import Teamcenter.Soa.Client.Model
import typing

class GetAvailableServicesResponse:
    def __init__(self, ) -> None: ...
    ServiceNames: list[str]

class GetGroupMembershipResponse:
    def __init__(self, ) -> None: ...
    GroupMembers: list[Teamcenter.Soa.Client.Model.ModelObject]
    ServiceData: Teamcenter.Soa.Client.Model.ServiceData

class GetSessionGroupMemberResponse:
    def __init__(self, ) -> None: ...
    GroupMember: Teamcenter.Soa.Client.Model.ModelObject
    ServiceData: Teamcenter.Soa.Client.Model.ServiceData

class LoginResponse:
    def __init__(self, ) -> None: ...
    User: Teamcenter.Soa.Client.Model.ModelObject
    GroupMember: Teamcenter.Soa.Client.Model.ModelObject
    ServiceData: Teamcenter.Soa.Client.Model.ServiceData

class PreferencesResponse:
    def __init__(self, ) -> None: ...
    Preferences: Teamcenter.Soa.Client.Model.Preferences
    ServiceData: Teamcenter.Soa.Client.Model.ServiceData

class PrefSetting:
    def __init__(self, ) -> None: ...
    PrefScope: str
    PrefName: str
    PrefValues: list[str]

class Session:
    def __init__(self , *args: typing.Any) -> None: ...
    def GetPreferences(self, PrefScope: str, PrefNames: list[str]) -> PreferencesResponse: ...
    def SetPreferences(self, Settings: list[PrefSetting]) -> PreferencesResponse: ...
    def GetAvailableServices(self) -> GetAvailableServicesResponse: ...
    def GetGroupMembership(self) -> GetGroupMembershipResponse: ...
    def GetSessionGroupMember(self) -> GetSessionGroupMemberResponse: ...
    def Login(self, Username: str, Password: str, Group: str, Role: str, SessionDiscriminator: str) -> LoginResponse: ...
    def LoginSSO(self, Username: str, SsoCredentials: str, Group: str, Role: str, SessionDiscriminator: str) -> LoginResponse: ...
    def Logout(self) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SetSessionGroupMember(self, GroupMember: Teamcenter.Soa.Client.Model.ModelObject) -> Teamcenter.Soa.Client.Model.ServiceData: ...

