import System
import Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement
import Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_02.RequirementsManagement
import Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_10.RequirementsManagement
import Teamcenter.Soa.Client
import typing

class RequirementsManagementRestBindingStub(RequirementsManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ImportUnmanagedData(self, RelativeStructParent: list[Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement.RelativeStructureParentInfo], ImportOptions: list[str]) -> Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement.ImportUnmanagedDataResponse: ...
    @typing.overload
    def GetTraceabilityMatrix(self, Inputs: list[Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_02.RequirementsManagement.TraceabilityMatrixInfo]) -> Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_02.RequirementsManagement.TraceabilityMatrixResponse: ...
    @typing.overload
    def GetTraceabilityMatrix(self, Inputs: list[Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_10.RequirementsManagement.TraceabilityMatrixInfo1]) -> Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_02.RequirementsManagement.TraceabilityMatrixResponse: ...
    def GetMatchingLines(self, Inputs: list[Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_10.RequirementsManagement.MatchLineInputData]) -> Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_10.RequirementsManagement.MatchedLineResponse: ...

class RequirementsManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> RequirementsManagementService: ...
    def ImportUnmanagedData(self, RelativeStructParent: list[Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement.RelativeStructureParentInfo], ImportOptions: list[str]) -> Teamcenter.Services.Internal.Strong.Requirementsmanagement._2009_10.RequirementsManagement.ImportUnmanagedDataResponse: ...
    @typing.overload
    def GetTraceabilityMatrix(self, Inputs: list[Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_02.RequirementsManagement.TraceabilityMatrixInfo]) -> Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_02.RequirementsManagement.TraceabilityMatrixResponse: ...
    @typing.overload
    def GetTraceabilityMatrix(self, Inputs: list[Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_10.RequirementsManagement.TraceabilityMatrixInfo1]) -> Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_02.RequirementsManagement.TraceabilityMatrixResponse: ...
    def GetMatchingLines(self, Inputs: list[Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_10.RequirementsManagement.MatchLineInputData]) -> Teamcenter.Services.Internal.Strong.Requirementsmanagement._2012_10.RequirementsManagement.MatchedLineResponse: ...

