import System
import Teamcenter.Services.Internal.Strong.Projectmanagement._2007_01.ScheduleManagement
import Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement
import Teamcenter.Services.Internal.Strong.Projectmanagement._2008_06.ScheduleManagement
import Teamcenter.Services.Internal.Strong.Projectmanagement._2009_10.ScheduleManagement
import Teamcenter.Services.Internal.Strong.Projectmanagement._2010_04.ScheduleManagement
import Teamcenter.Services.Internal.Strong.Projectmanagement._2011_06.ScheduleManagement
import Teamcenter.Services.Internal.Strong.Projectmanagement._2012_02.ScheduleManagement
import Teamcenter.Services.Internal.Strong.Projectmanagement._2014_10.ScheduleManagement
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong
import typing

class ScheduleManagementRestBindingStub(ScheduleManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def LoadSchedule(self, Schedule: list[str]) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2007_01.ScheduleManagement.MultipleScheduleLoadResponse: ...
    @typing.overload
    def ModifySchedule(self, ScheduleChangeContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2007_01.ScheduleManagement.ScheduleChangeContainer) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    @typing.overload
    def ModifySchedule(self, ScheduleModifyContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.ScheduleModifyContainer) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    @typing.overload
    def ModifySchedule(self, ScheduleModifyContainers: list[Teamcenter.Services.Internal.Strong.Projectmanagement._2008_06.ScheduleManagement.ScheduleModifyContainer]) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2008_06.ScheduleManagement.ScheduleModifyResponses: ...
    @typing.overload
    def LoadProgramView(self, LoadProgramViewContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.LoadProgramViewContainer) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.LoadProgramViewResponse: ...
    @typing.overload
    def LoadProgramView(self, LoadProgramViewContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2011_06.ScheduleManagement.LoadProgramViewContainer) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.LoadProgramViewResponse: ...
    def LoadResourceAssignments(self, LoadResourceAssignmentContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.LoadResourceAssignmentContainer) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.ResourceAssignmentLoadResponse: ...
    def LoadSchedules(self, Schedule: list[str]) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2008_06.ScheduleManagement.MultipleScheduleLoadResponses: ...
    def GetSchedulesToinsert(self, MasterSchedule: Teamcenter.Soa.Client.Model.Strong.Schedule) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def TranslateOne(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2009_10.ScheduleManagement.TranslatorResponseContainer: ...
    def TranslateThree(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2009_10.ScheduleManagement.TranslationDataContainer: ...
    def TranslateTwo(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2009_10.ScheduleManagement.TranslatorResponseScheduleModifyContainer: ...
    def TranslateFour(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2010_04.ScheduleManagement.TranslationDataContainer: ...
    def ModifySchedules(self, ScheduleModifyContainers: list[Teamcenter.Services.Internal.Strong.Projectmanagement._2011_06.ScheduleManagement.ScheduleModifyContainer]) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2011_06.ScheduleManagement.ScheduleModifyResponses: ...
    def TranslateFive(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2012_02.ScheduleManagement.TranslatorResponseScheduleModifyContainer: ...
    def DeferredSave(self, DeferredOption: Teamcenter.Services.Internal.Strong.Projectmanagement._2014_10.ScheduleManagement.DeferredSaveOption) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2014_10.ScheduleManagement.DeferredSaveResponse: ...
    def PasteTasks(self, Inputs: list[Teamcenter.Services.Internal.Strong.Projectmanagement._2014_10.ScheduleManagement.PasteTaskContainer]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class ScheduleManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ScheduleManagementService: ...
    def LoadSchedule(self, Schedule: list[str]) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2007_01.ScheduleManagement.MultipleScheduleLoadResponse: ...
    @typing.overload
    def ModifySchedule(self, ScheduleChangeContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2007_01.ScheduleManagement.ScheduleChangeContainer) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    @typing.overload
    def ModifySchedule(self, ScheduleModifyContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.ScheduleModifyContainer) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    @typing.overload
    def ModifySchedule(self, ScheduleModifyContainers: list[Teamcenter.Services.Internal.Strong.Projectmanagement._2008_06.ScheduleManagement.ScheduleModifyContainer]) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2008_06.ScheduleManagement.ScheduleModifyResponses: ...
    @typing.overload
    def LoadProgramView(self, LoadProgramViewContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.LoadProgramViewContainer) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.LoadProgramViewResponse: ...
    @typing.overload
    def LoadProgramView(self, LoadProgramViewContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2011_06.ScheduleManagement.LoadProgramViewContainer) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.LoadProgramViewResponse: ...
    def LoadResourceAssignments(self, LoadResourceAssignmentContainer: Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.LoadResourceAssignmentContainer) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2007_06.ScheduleManagement.ResourceAssignmentLoadResponse: ...
    def LoadSchedules(self, Schedule: list[str]) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2008_06.ScheduleManagement.MultipleScheduleLoadResponses: ...
    def GetSchedulesToinsert(self, MasterSchedule: Teamcenter.Soa.Client.Model.Strong.Schedule) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def TranslateOne(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2009_10.ScheduleManagement.TranslatorResponseContainer: ...
    def TranslateThree(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2009_10.ScheduleManagement.TranslationDataContainer: ...
    def TranslateTwo(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2009_10.ScheduleManagement.TranslatorResponseScheduleModifyContainer: ...
    def TranslateFour(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2010_04.ScheduleManagement.TranslationDataContainer: ...
    def ModifySchedules(self, ScheduleModifyContainers: list[Teamcenter.Services.Internal.Strong.Projectmanagement._2011_06.ScheduleManagement.ScheduleModifyContainer]) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2011_06.ScheduleManagement.ScheduleModifyResponses: ...
    def TranslateFive(self, ScheduleUid: str) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2012_02.ScheduleManagement.TranslatorResponseScheduleModifyContainer: ...
    def DeferredSave(self, DeferredOption: Teamcenter.Services.Internal.Strong.Projectmanagement._2014_10.ScheduleManagement.DeferredSaveOption) -> Teamcenter.Services.Internal.Strong.Projectmanagement._2014_10.ScheduleManagement.DeferredSaveResponse: ...
    def PasteTasks(self, Inputs: list[Teamcenter.Services.Internal.Strong.Projectmanagement._2014_10.ScheduleManagement.PasteTaskContainer]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

