import System
import Teamcenter.Services.Internal.Strong.Ai._2008_06.Ai
import Teamcenter.Services.Internal.Strong.Ai._2016_03.Ai
import Teamcenter.Services.Internal.Strong.Ai._2016_04.Ai
import Teamcenter.Services.Strong.Ai._2006_03.Ai
import Teamcenter.Services.Strong.Ai._2007_12.Ai
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class AiRestBindingStub(AiService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def BeginGenerateMonolithicJt(self, StartingNode: Teamcenter.Services.Strong.Ai._2006_03.Ai.ApplicationRef, ItemId: str, RevId: str, Config: Teamcenter.Services.Strong.Ai._2007_12.Ai.Configuration2, Options: Teamcenter.Services.Internal.Strong.Ai._2008_06.Ai.GenerateMonolithicJtOptions, ServerMode: int) -> Teamcenter.Services.Internal.Strong.Ai._2008_06.Ai.BeginGenerateMonolithicJtResponse: ...
    def EndGenerateMonolithicJt(self, Request: Teamcenter.Soa.Client.Model.ModelObject, ServerMode: int) -> Teamcenter.Services.Internal.Strong.Ai._2008_06.Ai.EndGenerateMonolithicJtResponse: ...
    def Invoke(self, MethodName: str, StrIn: str) -> str: ...
    def GetApplicationInterfaceTypes(self, SpecificTypeNames: list[str]) -> Teamcenter.Services.Internal.Strong.Ai._2016_03.Ai.GetAITypesResponse: ...
    def Invoke2(self, MethodName: str, XmlIn: str) -> Teamcenter.Services.Internal.Strong.Ai._2016_04.Ai.InvokeResponse: ...

class AiService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> AiService: ...
    def BeginGenerateMonolithicJt(self, StartingNode: Teamcenter.Services.Strong.Ai._2006_03.Ai.ApplicationRef, ItemId: str, RevId: str, Config: Teamcenter.Services.Strong.Ai._2007_12.Ai.Configuration2, Options: Teamcenter.Services.Internal.Strong.Ai._2008_06.Ai.GenerateMonolithicJtOptions, ServerMode: int) -> Teamcenter.Services.Internal.Strong.Ai._2008_06.Ai.BeginGenerateMonolithicJtResponse: ...
    def EndGenerateMonolithicJt(self, Request: Teamcenter.Soa.Client.Model.ModelObject, ServerMode: int) -> Teamcenter.Services.Internal.Strong.Ai._2008_06.Ai.EndGenerateMonolithicJtResponse: ...
    def Invoke(self, MethodName: str, StrIn: str) -> str: ...
    def GetApplicationInterfaceTypes(self, SpecificTypeNames: list[str]) -> Teamcenter.Services.Internal.Strong.Ai._2016_03.Ai.GetAITypesResponse: ...
    def Invoke2(self, MethodName: str, XmlIn: str) -> Teamcenter.Services.Internal.Strong.Ai._2016_04.Ai.InvokeResponse: ...

