import System
import System.Collections.Generic
import System.IO

class AnsiConsoleTheme(ConsoleTheme):
    def __init__(self, styles: dict[ConsoleThemeStyle, str]) -> None: ...
    Code: AnsiConsoleTheme
    Grayscale: AnsiConsoleTheme
    Literate: AnsiConsoleTheme
    CanBuffer: bool
    @staticmethod
    def get_Code() -> AnsiConsoleTheme: ...
    @staticmethod
    def get_Grayscale() -> AnsiConsoleTheme: ...
    @staticmethod
    def get_Literate() -> AnsiConsoleTheme: ...
    def get_CanBuffer(self) -> bool: ...
    def Set(self, output: System.IO.TextWriter, style: ConsoleThemeStyle) -> int: ...
    def Reset(self, output: System.IO.TextWriter) -> None: ...

class AnsiConsoleThemes:
    Literate: AnsiConsoleTheme
    Grayscale: AnsiConsoleTheme
    Code: AnsiConsoleTheme
    @staticmethod
    def get_Literate() -> AnsiConsoleTheme: ...
    @staticmethod
    def get_Grayscale() -> AnsiConsoleTheme: ...
    @staticmethod
    def get_Code() -> AnsiConsoleTheme: ...

class ConsoleTheme:
    None: ConsoleTheme
    CanBuffer: bool
    @staticmethod
    def get_None() -> ConsoleTheme: ...
    def get_CanBuffer(self) -> bool: ...
    def Set(self, output: System.IO.TextWriter, style: ConsoleThemeStyle) -> int: ...
    def Reset(self, output: System.IO.TextWriter) -> None: ...

class ConsoleThemeStyle(System.Enum, int):
    Text: ConsoleThemeStyle = ...
    SecondaryText: ConsoleThemeStyle = ...
    TertiaryText: ConsoleThemeStyle = ...
    Invalid: ConsoleThemeStyle = ...
    Null: ConsoleThemeStyle = ...
    Name: ConsoleThemeStyle = ...
    String: ConsoleThemeStyle = ...
    Number: ConsoleThemeStyle = ...
    Boolean: ConsoleThemeStyle = ...
    Scalar: ConsoleThemeStyle = ...
    Object: ConsoleThemeStyle = ...
    LevelVerbose: ConsoleThemeStyle = ...
    LevelDebug: ConsoleThemeStyle = ...
    LevelInformation: ConsoleThemeStyle = ...
    LevelWarning: ConsoleThemeStyle = ...
    LevelError: ConsoleThemeStyle = ...
    LevelFatal: ConsoleThemeStyle = ...

class EmptyConsoleTheme(ConsoleTheme):
    def __init__(self, ) -> None: ...
    CanBuffer: bool
    def get_CanBuffer(self) -> bool: ...
    def Set(self, output: System.IO.TextWriter, style: ConsoleThemeStyle) -> int: ...
    def Reset(self, output: System.IO.TextWriter) -> None: ...

class SystemConsoleTheme(ConsoleTheme):
    def __init__(self, styles: dict[ConsoleThemeStyle, SystemConsoleThemeStyle]) -> None: ...
    Grayscale: SystemConsoleTheme
    Literate: SystemConsoleTheme
    Colored: SystemConsoleTheme
    Styles: dict[ConsoleThemeStyle, SystemConsoleThemeStyle]
    CanBuffer: bool
    @staticmethod
    def get_Grayscale() -> SystemConsoleTheme: ...
    @staticmethod
    def get_Literate() -> SystemConsoleTheme: ...
    @staticmethod
    def get_Colored() -> SystemConsoleTheme: ...
    def get_Styles(self) -> dict[ConsoleThemeStyle, SystemConsoleThemeStyle]: ...
    def get_CanBuffer(self) -> bool: ...
    def Set(self, output: System.IO.TextWriter, style: ConsoleThemeStyle) -> int: ...
    def Reset(self, output: System.IO.TextWriter) -> None: ...

class SystemConsoleThemes:
    Literate: SystemConsoleTheme
    Grayscale: SystemConsoleTheme
    Colored: SystemConsoleTheme
    @staticmethod
    def get_Literate() -> SystemConsoleTheme: ...
    @staticmethod
    def get_Grayscale() -> SystemConsoleTheme: ...
    @staticmethod
    def get_Colored() -> SystemConsoleTheme: ...

class <>c:
    def __init__(self, ) -> None: ...
    <>9: <>c
    <>9__11_0: dict[dict[ConsoleThemeStyle, str], ConsoleThemeStyle]
    <>9__11_1: dict[dict[ConsoleThemeStyle, str], str]

class <>c:
    def __init__(self, ) -> None: ...
    <>9: <>c
    <>9__10_0: dict[dict[ConsoleThemeStyle, SystemConsoleThemeStyle], ConsoleThemeStyle]
    <>9__10_1: dict[dict[ConsoleThemeStyle, SystemConsoleThemeStyle], SystemConsoleThemeStyle]

