import System
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement
import Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement
import Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement
import Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement
import Tm0.Services.Strong.Testmanagement._2014_06.InstanceManagement
import typing

class ActivityManagementRestBindingStub(ActivityManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetTestResults(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement.TestResultsInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement.TestResultsResponse: ...

class ActivityManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ActivityManagementService: ...
    def GetTestResults(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement.TestResultsInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2014_12.ActivityManagement.TestResultsResponse: ...

class InstanceManagementRestBindingStub(InstanceManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateTestCases(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestCaseInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestCasesResponse: ...
    def CreateTestInstancesFromTestCase(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestInstFromTestCaseInfo]) -> Tm0.Services.Strong.Testmanagement._2014_06.InstanceManagement.TestInstancesResponse: ...
    def EditTestInstances(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.EditTestInstanceInfo]) -> Tm0.Services.Strong.Testmanagement._2014_06.InstanceManagement.TestInstancesResponse: ...
    def GetBOMLinesFromCloneStableIdChain(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.BOMLineCloneStableIdChainInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.BOMLineCloneStableIdChainResponse: ...
    @typing.overload
    def GetTestSteps(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestStepsInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestStepsResponse: ...
    @typing.overload
    def GetTestSteps(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TestStepsInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TestStepsResponse: ...
    def CreateObjects(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.CreateObjectInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.CreateObjectsResponse: ...
    def EditObjects(self, InputData: list[Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.EditObjectInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetTestInstances(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.TestInstancesSearchCriteria]) -> Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.TestInstancesSearchResponse: ...

class InstanceManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> InstanceManagementService: ...
    def CreateTestCases(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestCaseInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestCasesResponse: ...
    def CreateTestInstancesFromTestCase(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestInstFromTestCaseInfo]) -> Tm0.Services.Strong.Testmanagement._2014_06.InstanceManagement.TestInstancesResponse: ...
    def EditTestInstances(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.EditTestInstanceInfo]) -> Tm0.Services.Strong.Testmanagement._2014_06.InstanceManagement.TestInstancesResponse: ...
    def GetBOMLinesFromCloneStableIdChain(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.BOMLineCloneStableIdChainInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.BOMLineCloneStableIdChainResponse: ...
    @typing.overload
    def GetTestSteps(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestStepsInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2014_12.InstanceManagement.TestStepsResponse: ...
    @typing.overload
    def GetTestSteps(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TestStepsInputInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2015_10.InstanceManagement.TestStepsResponse: ...
    def CreateObjects(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.CreateObjectInfo]) -> Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.CreateObjectsResponse: ...
    def EditObjects(self, InputData: list[Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.EditObjectInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetTestInstances(self, Inputs: list[Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.TestInstancesSearchCriteria]) -> Tm0.Services.Internal.Strong.Testmanagement._2015_03.InstanceManagement.TestInstancesSearchResponse: ...

