import Cba1.Services.Internal.Strong.Cbaext._2013_05.PublishManagement
import Cba1.Services.Internal.Strong.Cbaext._2013_05.QueryManagement
import Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement
import Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement
import Cba1.Services.Internal.Strong.Cbaext._2015_10.QueryManagement
import Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement
import System
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong
import typing

class AlignmentManagementRestBindingStub(AlignmentManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def LinkDesignOccToACTLine(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], ActLines: list[Teamcenter.Soa.Client.Model.Strong.ACTLine]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def UnalignDesignOccsToACTLines(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], ActLines: list[Teamcenter.Soa.Client.Model.Strong.ACTLine]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def AlignCadOccsWithSolutions(self, AlignmentInput: Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.SolutionAlignmentInputType) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.AlignmentResponse: ...
    def AlignDesignsWithParts(self, AlignmentInput: Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.PartAlignmentInputType) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.AlignmentResponse: ...

class AlignmentManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> AlignmentManagementService: ...
    def LinkDesignOccToACTLine(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], ActLines: list[Teamcenter.Soa.Client.Model.Strong.ACTLine]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def UnalignDesignOccsToACTLines(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], ActLines: list[Teamcenter.Soa.Client.Model.Strong.ACTLine]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def AlignCadOccsWithSolutions(self, AlignmentInput: Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.SolutionAlignmentInputType) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.AlignmentResponse: ...
    def AlignDesignsWithParts(self, AlignmentInput: Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.PartAlignmentInputType) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.AlignmentManagement.AlignmentResponse: ...

class PublishManagementRestBindingStub(PublishManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def PublishCadOccurrences(self, PublishInfo: list[Cba1.Services.Internal.Strong.Cbaext._2013_05.PublishManagement.CADOccPublishInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def PublishItems(self, PublishInfo: list[Cba1.Services.Internal.Strong.Cbaext._2013_05.PublishManagement.ItemRevPublishInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class PublishManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> PublishManagementService: ...
    def PublishCadOccurrences(self, PublishInfo: list[Cba1.Services.Internal.Strong.Cbaext._2013_05.PublishManagement.CADOccPublishInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def PublishItems(self, PublishInfo: list[Cba1.Services.Internal.Strong.Cbaext._2013_05.PublishManagement.ItemRevPublishInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class QueryManagementRestBindingStub(QueryManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def FindAlignedACTForCAD(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], ActBomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow) -> Cba1.Services.Internal.Strong.Cbaext._2013_05.QueryManagement.FindAlignedACTResponse: ...
    def FindAlignedDesignsForACT(self, InputACTData: list[Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.ActLineInput]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedDesignsForACTResponse: ...
    @typing.overload
    def ExecuteSpatialSearch(self, Input: list[Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.SpatialSearchInput]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.SpatialSearchResponse: ...
    @typing.overload
    def ExecuteSpatialSearch(self, Input: list[Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement.SpatialSearchInput]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.SpatialSearchResponse: ...
    @typing.overload
    def FindAlignedACTLinesForDesigns(self, Designs: list[Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.BomLineType], PreciseEffectivityDetails: Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.PreciseEffectivityDetails) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedACTLinesForDesignsResponse: ...
    @typing.overload
    def FindAlignedACTLinesForDesigns(self, Bomlines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], PreciseEffectivityDetails: Cba1.Services.Internal.Strong.Cbaext._2015_10.QueryManagement.PreciseEffectivityDetails) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedACTLinesForDesignsResponse: ...
    def FindAlignedCADForPart(self, PmmParts: Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.RowColumn) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedDesignsResponse: ...
    def FindAlignedDesignsForSolutions(self, Solutions: Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.RowColumn) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedDesignsForSolutionsResponse: ...
    def FindAlignedDrawingForPart(self, PmmParts: Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.RowColumn) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedDesignsResponse: ...
    def FindAlignedPartForCAD(self, Designs: list[Teamcenter.Soa.Client.Model.Strong.ItemRevision]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedPartsResponse: ...
    def FindAlignedPartForDrawing(self, Designs: list[Teamcenter.Soa.Client.Model.Strong.ItemRevision]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedPartsResponse: ...
    def FindAlignedPartForDrawingProxy(self, DesignProxies: list[Teamcenter.Soa.Client.Model.Strong.TcUsageProxy]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedPartForProxyResponse: ...
    def FindAlignedSolutionsForDesigns(self, Designs: list[Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.BomLineType]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedSolutionsForDesignsResponse: ...

class QueryManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> QueryManagementService: ...
    def FindAlignedACTForCAD(self, BomLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], ActBomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow) -> Cba1.Services.Internal.Strong.Cbaext._2013_05.QueryManagement.FindAlignedACTResponse: ...
    def FindAlignedDesignsForACT(self, InputACTData: list[Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.ActLineInput]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedDesignsForACTResponse: ...
    @typing.overload
    def ExecuteSpatialSearch(self, Input: list[Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.SpatialSearchInput]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.SpatialSearchResponse: ...
    @typing.overload
    def ExecuteSpatialSearch(self, Input: list[Cba1.Services.Internal.Strong.Cbaext._2016_03.QueryManagement.SpatialSearchInput]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.SpatialSearchResponse: ...
    @typing.overload
    def FindAlignedACTLinesForDesigns(self, Designs: list[Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.BomLineType], PreciseEffectivityDetails: Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.PreciseEffectivityDetails) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedACTLinesForDesignsResponse: ...
    @typing.overload
    def FindAlignedACTLinesForDesigns(self, Bomlines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine], PreciseEffectivityDetails: Cba1.Services.Internal.Strong.Cbaext._2015_10.QueryManagement.PreciseEffectivityDetails) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedACTLinesForDesignsResponse: ...
    def FindAlignedCADForPart(self, PmmParts: Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.RowColumn) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedDesignsResponse: ...
    def FindAlignedDesignsForSolutions(self, Solutions: Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.RowColumn) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedDesignsForSolutionsResponse: ...
    def FindAlignedDrawingForPart(self, PmmParts: Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.RowColumn) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedDesignsResponse: ...
    def FindAlignedPartForCAD(self, Designs: list[Teamcenter.Soa.Client.Model.Strong.ItemRevision]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedPartsResponse: ...
    def FindAlignedPartForDrawing(self, Designs: list[Teamcenter.Soa.Client.Model.Strong.ItemRevision]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedPartsResponse: ...
    def FindAlignedPartForDrawingProxy(self, DesignProxies: list[Teamcenter.Soa.Client.Model.Strong.TcUsageProxy]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedPartForProxyResponse: ...
    def FindAlignedSolutionsForDesigns(self, Designs: list[Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.BomLineType]) -> Cba1.Services.Internal.Strong.Cbaext._2014_12.QueryManagement.FindAlignedSolutionsForDesignsResponse: ...

