import System
import Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore
import Teamcenter.Services.Internal.Strong.Mrocore._2009_06.MROCore
import Teamcenter.Services.Internal.Strong.Mrocore._2012_02.MROCore
import Teamcenter.Soa.Client

class MROCoreRestBindingStub(MROCoreService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def NameOccurrence(self, NameOccurrenceInputInfo: list[Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore.NameOccurrenceInputInfo]) -> Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore.NameOccurrenceResponse: ...
    def SetupDeviation(self, SetupDeviationPhysInput: list[Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore.SetupDeviationPhysInput]) -> Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore.SetupDeviationResponse: ...
    def DisplayUtilization(self, InputInfo: list[Teamcenter.Services.Internal.Strong.Mrocore._2009_06.MROCore.DisplayUtilizationInfo]) -> Teamcenter.Services.Internal.Strong.Mrocore._2009_06.MROCore.DisplayUtilizationResponse: ...
    def GetLotsforItem(self, Inputs: list[Teamcenter.Services.Internal.Strong.Mrocore._2012_02.MROCore.GetLotsforItemInputInfo]) -> Teamcenter.Services.Internal.Strong.Mrocore._2012_02.MROCore.GetLotsforItemResponse: ...

class MROCoreService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> MROCoreService: ...
    def NameOccurrence(self, NameOccurrenceInputInfo: list[Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore.NameOccurrenceInputInfo]) -> Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore.NameOccurrenceResponse: ...
    def SetupDeviation(self, SetupDeviationPhysInput: list[Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore.SetupDeviationPhysInput]) -> Teamcenter.Services.Internal.Strong.Mrocore._2008_06.MROCore.SetupDeviationResponse: ...
    def DisplayUtilization(self, InputInfo: list[Teamcenter.Services.Internal.Strong.Mrocore._2009_06.MROCore.DisplayUtilizationInfo]) -> Teamcenter.Services.Internal.Strong.Mrocore._2009_06.MROCore.DisplayUtilizationResponse: ...
    def GetLotsforItem(self, Inputs: list[Teamcenter.Services.Internal.Strong.Mrocore._2012_02.MROCore.GetLotsforItemInputInfo]) -> Teamcenter.Services.Internal.Strong.Mrocore._2012_02.MROCore.GetLotsforItemResponse: ...

