import System
import System.Collections
import System.Xml
import System.Xml.Serialization

class XmlSerializationWriter1(System.Xml.Serialization.XmlSerializationWriter):
    def __init__(self, ) -> None: ...
    def Write78_SoaConstants(self, o: typing.Any) -> None: ...
    def Write79_Monitor(self, o: typing.Any) -> None: ...
    def Write80_AnyCredentials(self, o: typing.Any) -> None: ...
    def Write81_NoDTDResolver(self, o: typing.Any) -> None: ...
    def Write82_AuthUtils(self, o: typing.Any) -> None: ...
    def Write83_PolicyMarshaller(self, o: typing.Any) -> None: ...
    def Write84_ExceptionMapper(self, o: typing.Any) -> None: ...
    def Write85_XmlBindingUtils(self, o: typing.Any) -> None: ...
    def Write86_ObjectPropertyPolicy(self, o: typing.Any) -> None: ...
    def Write87_ObjectType(self, o: typing.Any) -> None: ...
    def Write88_Property(self, o: typing.Any) -> None: ...
    def Write89_NameBooleanValue(self, o: typing.Any) -> None: ...
    def Write90_NameIntegerValue(self, o: typing.Any) -> None: ...
    def Write91_NameStringValue(self, o: typing.Any) -> None: ...
    def Write92_RequestBody(self, o: typing.Any) -> None: ...
    def Write93_RequestEnvelope(self, o: typing.Any) -> None: ...
    def Write94_RequestHeader(self, o: typing.Any) -> None: ...
    def Write95_ActionReference(self, o: typing.Any) -> None: ...
    def Write96_AttachedLov(self, o: typing.Any) -> None: ...
    def Write97_BasedOn(self, o: typing.Any) -> None: ...
    def Write98_Bounds(self, o: typing.Any) -> None: ...
    def Write99_Constant(self, o: typing.Any) -> None: ...
    def Write100_DatasetAction(self, o: typing.Any) -> None: ...
    def Write101_DatasetReferenceInfo(self, o: typing.Any) -> None: ...
    def Write102_DatasetReference(self, o: typing.Any) -> None: ...
    def Write103_DatasetType(self, o: typing.Any) -> None: ...
    def Write104_Index(self, o: typing.Any) -> None: ...
    def Write105_KeyValue(self, o: typing.Any) -> None: ...
    def Write106_L10NData(self, o: typing.Any) -> None: ...
    def Write107_LovData(self, o: typing.Any) -> None: ...
    def Write108_LovInfo(self, o: typing.Any) -> None: ...
    def Write109_LovL10N(self, o: typing.Any) -> None: ...
    def Write110_LovReference(self, o: typing.Any) -> None: ...
    def Write111_LovValueL10N(self, o: typing.Any) -> None: ...
    def Write112_LovValue(self, o: typing.Any) -> None: ...
    def Write113_ModelSchema(self, o: typing.Any) -> None: ...
    def Write114_ModelType(self, o: typing.Any) -> None: ...
    def Write115_NamingRule(self, o: typing.Any) -> None: ...
    def Write116_PropertyDescriptor(self, o: typing.Any) -> None: ...
    def Write117_PropertyL10N(self, o: typing.Any) -> None: ...
    def Write118_Renderer(self, o: typing.Any) -> None: ...
    def Write119_RevNameRule(self, o: typing.Any) -> None: ...
    def Write120_RulePattern(self, o: typing.Any) -> None: ...
    def Write121_ToolData(self, o: typing.Any) -> None: ...
    def Write122_Tool(self, o: typing.Any) -> None: ...
    def Write123_TypeL10N(self, o: typing.Any) -> None: ...
    def Write124_TypeSchema(self, o: typing.Any) -> None: ...
    def Write125_Attrib(self, o: typing.Any) -> None: ...
    def Write126_CompoundProperty(self, o: typing.Any) -> None: ...
    def Write127_CreateInput(self, o: typing.Any) -> None: ...
    def Write128_DisplayProperty(self, o: typing.Any) -> None: ...
    def Write129_ErrorStack(self, o: typing.Any) -> None: ...
    def Write130_ErrorValue(self, o: typing.Any) -> None: ...
    def Write131_ModelClass(self, o: typing.Any) -> None: ...
    def Write132_ModelObject(self, o: typing.Any) -> None: ...
    def Write133_ModelSchema(self, o: typing.Any) -> None: ...
    def Write134_ModelType(self, o: typing.Any) -> None: ...
    def Write135_Modifiers(self, o: typing.Any) -> None: ...
    def Write136_ObjectMap(self, o: typing.Any) -> None: ...
    def Write137_ObjectPropertyPolicy(self, o: typing.Any) -> None: ...
    def Write138_PartialErrors(self, o: typing.Any) -> None: ...
    def Write139_PolicyProperty(self, o: typing.Any) -> None: ...
    def Write140_PolicyType(self, o: typing.Any) -> None: ...
    def Write141_Preferences(self, o: typing.Any) -> None: ...
    def Write142_PreferenceValue(self, o: typing.Any) -> None: ...
    def Write143_Preference(self, o: typing.Any) -> None: ...
    def Write144_PropDependant(self, o: typing.Any) -> None: ...
    def Write145_PropDescriptor(self, o: typing.Any) -> None: ...
    def Write146_PropertyNameValues(self, o: typing.Any) -> None: ...
    def Write147_PropertyValue(self, o: typing.Any) -> None: ...
    def Write148_Property(self, o: typing.Any) -> None: ...
    def Write149_RefId(self, o: typing.Any) -> None: ...
    def Write150_ServiceData(self, o: typing.Any) -> None: ...
    def Write151_TextInfo(self, o: typing.Any) -> None: ...
    def Write152_XJPropertyValue(self, o: typing.Any) -> None: ...
    def Write153_XJProperty(self, o: typing.Any) -> None: ...

class XmlSerializationReader1(System.Xml.Serialization.XmlSerializationReader):
    def __init__(self, ) -> None: ...
    def Read78_SoaConstants(self) -> typing.Any: ...
    def Read79_Monitor(self) -> typing.Any: ...
    def Read80_AnyCredentials(self) -> typing.Any: ...
    def Read81_NoDTDResolver(self) -> typing.Any: ...
    def Read82_AuthUtils(self) -> typing.Any: ...
    def Read83_PolicyMarshaller(self) -> typing.Any: ...
    def Read84_ExceptionMapper(self) -> typing.Any: ...
    def Read85_XmlBindingUtils(self) -> typing.Any: ...
    def Read86_ObjectPropertyPolicy(self) -> typing.Any: ...
    def Read87_ObjectType(self) -> typing.Any: ...
    def Read88_Property(self) -> typing.Any: ...
    def Read89_NameBooleanValue(self) -> typing.Any: ...
    def Read90_NameIntegerValue(self) -> typing.Any: ...
    def Read91_NameStringValue(self) -> typing.Any: ...
    def Read92_RequestBody(self) -> typing.Any: ...
    def Read93_RequestEnvelope(self) -> typing.Any: ...
    def Read94_RequestHeader(self) -> typing.Any: ...
    def Read95_ActionReference(self) -> typing.Any: ...
    def Read96_AttachedLov(self) -> typing.Any: ...
    def Read97_BasedOn(self) -> typing.Any: ...
    def Read98_Bounds(self) -> typing.Any: ...
    def Read99_Constant(self) -> typing.Any: ...
    def Read100_DatasetAction(self) -> typing.Any: ...
    def Read101_DatasetReferenceInfo(self) -> typing.Any: ...
    def Read102_DatasetReference(self) -> typing.Any: ...
    def Read103_DatasetType(self) -> typing.Any: ...
    def Read104_Index(self) -> typing.Any: ...
    def Read105_KeyValue(self) -> typing.Any: ...
    def Read106_L10NData(self) -> typing.Any: ...
    def Read107_LovData(self) -> typing.Any: ...
    def Read108_LovInfo(self) -> typing.Any: ...
    def Read109_LovL10N(self) -> typing.Any: ...
    def Read110_LovReference(self) -> typing.Any: ...
    def Read111_LovValueL10N(self) -> typing.Any: ...
    def Read112_LovValue(self) -> typing.Any: ...
    def Read113_ModelSchema(self) -> typing.Any: ...
    def Read114_ModelType(self) -> typing.Any: ...
    def Read115_NamingRule(self) -> typing.Any: ...
    def Read116_PropertyDescriptor(self) -> typing.Any: ...
    def Read117_PropertyL10N(self) -> typing.Any: ...
    def Read118_Renderer(self) -> typing.Any: ...
    def Read119_RevNameRule(self) -> typing.Any: ...
    def Read120_RulePattern(self) -> typing.Any: ...
    def Read121_ToolData(self) -> typing.Any: ...
    def Read122_Tool(self) -> typing.Any: ...
    def Read123_TypeL10N(self) -> typing.Any: ...
    def Read124_TypeSchema(self) -> typing.Any: ...
    def Read125_Attrib(self) -> typing.Any: ...
    def Read126_CompoundProperty(self) -> typing.Any: ...
    def Read127_CreateInput(self) -> typing.Any: ...
    def Read128_DisplayProperty(self) -> typing.Any: ...
    def Read129_ErrorStack(self) -> typing.Any: ...
    def Read130_ErrorValue(self) -> typing.Any: ...
    def Read131_ModelClass(self) -> typing.Any: ...
    def Read132_ModelObject(self) -> typing.Any: ...
    def Read133_ModelSchema(self) -> typing.Any: ...
    def Read134_ModelType(self) -> typing.Any: ...
    def Read135_Modifiers(self) -> typing.Any: ...
    def Read136_ObjectMap(self) -> typing.Any: ...
    def Read137_ObjectPropertyPolicy(self) -> typing.Any: ...
    def Read138_PartialErrors(self) -> typing.Any: ...
    def Read139_PolicyProperty(self) -> typing.Any: ...
    def Read140_PolicyType(self) -> typing.Any: ...
    def Read141_Preferences(self) -> typing.Any: ...
    def Read142_PreferenceValue(self) -> typing.Any: ...
    def Read143_Preference(self) -> typing.Any: ...
    def Read144_PropDependant(self) -> typing.Any: ...
    def Read145_PropDescriptor(self) -> typing.Any: ...
    def Read146_PropertyNameValues(self) -> typing.Any: ...
    def Read147_PropertyValue(self) -> typing.Any: ...
    def Read148_Property(self) -> typing.Any: ...
    def Read149_RefId(self) -> typing.Any: ...
    def Read150_ServiceData(self) -> typing.Any: ...
    def Read151_TextInfo(self) -> typing.Any: ...
    def Read152_XJPropertyValue(self) -> typing.Any: ...
    def Read153_XJProperty(self) -> typing.Any: ...

class XmlSerializer1(System.Xml.Serialization.XmlSerializer):
    pass

class SoaConstantsSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class MonitorSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class AnyCredentialsSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class NoDTDResolverSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class AuthUtilsSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PolicyMarshallerSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ExceptionMapperSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class XmlBindingUtilsSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ObjectPropertyPolicySerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ObjectTypeSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PropertySerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class NameBooleanValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class NameIntegerValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class NameStringValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class RequestBodySerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class RequestEnvelopeSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class RequestHeaderSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ActionReferenceSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class AttachedLovSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class BasedOnSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class BoundsSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ConstantSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class DatasetActionSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class DatasetReferenceInfoSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class DatasetReferenceSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class DatasetTypeSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class IndexSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class KeyValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class L10NDataSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class LovDataSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class LovInfoSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class LovL10NSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class LovReferenceSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class LovValueL10NSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class LovValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ModelSchemaSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ModelTypeSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class NamingRuleSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PropertyDescriptorSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PropertyL10NSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class RendererSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class RevNameRuleSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class RulePatternSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ToolDataSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ToolSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class TypeL10NSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class TypeSchemaSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class AttribSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class CompoundPropertySerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class CreateInputSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class DisplayPropertySerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ErrorStackSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ErrorValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ModelClassSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ModelObjectSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ModelSchemaSerializer1(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ModelTypeSerializer1(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ModifiersSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ObjectMapSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ObjectPropertyPolicySerializer1(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PartialErrorsSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PolicyPropertySerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PolicyTypeSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PreferencesSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PreferenceValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PreferenceSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PropDependantSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PropDescriptorSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PropertyNameValuesSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PropertyValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class PropertySerializer1(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class RefIdSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class ServiceDataSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class TextInfoSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class XJPropertyValueSerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class XJPropertySerializer(XmlSerializer1):
    def __init__(self, ) -> None: ...
    def CanDeserialize(self, xmlReader: System.Xml.XmlReader) -> bool: ...

class XmlSerializerContract(System.Xml.Serialization.XmlSerializerImplementation):
    def __init__(self, ) -> None: ...
    Reader: System.Xml.Serialization.XmlSerializationReader
    Writer: System.Xml.Serialization.XmlSerializationWriter
    ReadMethods: System.Collections.Hashtable
    WriteMethods: System.Collections.Hashtable
    TypedSerializers: System.Collections.Hashtable
    def get_Reader(self) -> System.Xml.Serialization.XmlSerializationReader: ...
    def get_Writer(self) -> System.Xml.Serialization.XmlSerializationWriter: ...
    def get_ReadMethods(self) -> System.Collections.Hashtable: ...
    def get_WriteMethods(self) -> System.Collections.Hashtable: ...
    def get_TypedSerializers(self) -> System.Collections.Hashtable: ...
    def CanSerialize(self, type: System.Type) -> bool: ...
    def GetSerializer(self, type: System.Type) -> System.Xml.Serialization.XmlSerializer: ...

