import System
import Teamcenter.Services.Internal.Strong.Cadbomalignment._2009_10.AlignmentManagement
import Teamcenter.Services.Internal.Strong.Cadbomalignment._2012_02.ProxyManagement
import Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_05.QueryManagement
import Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement
import Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement
import Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.QueryManagement
import Teamcenter.Services.Internal.Strong.Cadbomalignment._2015_10.ObjectManagement
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong

class AlignmentManagementRestBindingStub(AlignmentManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def FindAlignedCadForACT(self, InputData: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2009_10.AlignmentManagement.ActLineInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2009_10.AlignmentManagement.FindAlignedCadResponse: ...

class AlignmentManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> AlignmentManagementService: ...
    def FindAlignedCadForACT(self, InputData: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2009_10.AlignmentManagement.ActLineInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2009_10.AlignmentManagement.FindAlignedCadResponse: ...

class ObjectManagementRestBindingStub(ObjectManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateOrUpdateSearchCriteria(self, CriteriaInputVector: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaResponse: ...
    def DeleteSearchCriteria(self, CriteriaInput: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaResponse: ...
    def GetSearchCriteria(self, CriteriaInput: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.GetSearchCriteriaResponse: ...
    def AddCADOccurrencesToLayout(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.AddCADOccToLayoutInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMAddToLayoutResponse: ...
    def CreatePMMSCO(self, Input: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.CreatePMMSCOInputInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.CreatePMMSCOResponse: ...
    def GetPLMXMLFromPMMSCORecipe(self, Input: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMSCORecipeInputInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.GetPLMXMLFromPMMSCORecipeResponse: ...
    def GetPMMSCOInfo(self, PmmscoInputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMSCOInfoInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMSCOInfoResponse: ...
    def PmmAddSelectionToLayout(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.AddSelectionToLayoutInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMAddSelectionToLayoutResponse: ...
    def PmmAddToLayout(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.AddToLayoutInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMAddToLayoutResponse: ...
    def SaveOrClonePMMSCOWithFiles(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.SaveOrClonePMMSCOWithFilesInputInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.SaveOrClonePMMSCOWithFilesResponse: ...
    def UpdatePSFromPMM(self, PsForPMMInput: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2015_10.ObjectManagement.PSForPMMInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class ObjectManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ObjectManagementService: ...
    def CreateOrUpdateSearchCriteria(self, CriteriaInputVector: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaResponse: ...
    def DeleteSearchCriteria(self, CriteriaInput: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaResponse: ...
    def GetSearchCriteria(self, CriteriaInput: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.SearchCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_12.ObjectManagement.GetSearchCriteriaResponse: ...
    def AddCADOccurrencesToLayout(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.AddCADOccToLayoutInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMAddToLayoutResponse: ...
    def CreatePMMSCO(self, Input: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.CreatePMMSCOInputInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.CreatePMMSCOResponse: ...
    def GetPLMXMLFromPMMSCORecipe(self, Input: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMSCORecipeInputInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.GetPLMXMLFromPMMSCORecipeResponse: ...
    def GetPMMSCOInfo(self, PmmscoInputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMSCOInfoInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMSCOInfoResponse: ...
    def PmmAddSelectionToLayout(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.AddSelectionToLayoutInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMAddSelectionToLayoutResponse: ...
    def PmmAddToLayout(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.AddToLayoutInput]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.PMMAddToLayoutResponse: ...
    def SaveOrClonePMMSCOWithFiles(self, Inputs: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.SaveOrClonePMMSCOWithFilesInputInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.ObjectManagement.SaveOrClonePMMSCOWithFilesResponse: ...
    def UpdatePSFromPMM(self, PsForPMMInput: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2015_10.ObjectManagement.PSForPMMInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class ProxyManagementRestBindingStub(ProxyManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreatePMMPersistentProxy(self, InputData: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2012_02.ProxyManagement.PmmObjectInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2012_02.ProxyManagement.PersistentProxyResponse: ...
    def SavePMMPersistentProxy(self, InputData: list[Teamcenter.Soa.Client.Model.Strong.Cba0PersistentProxy]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2012_02.ProxyManagement.PersistentProxyResponse: ...

class ProxyManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ProxyManagementService: ...
    def CreatePMMPersistentProxy(self, InputData: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2012_02.ProxyManagement.PmmObjectInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2012_02.ProxyManagement.PersistentProxyResponse: ...
    def SavePMMPersistentProxy(self, InputData: list[Teamcenter.Soa.Client.Model.Strong.Cba0PersistentProxy]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2012_02.ProxyManagement.PersistentProxyResponse: ...

class QueryManagementRestBindingStub(QueryManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def RefreshProxies(self, ProxyObjectInput: list[Teamcenter.Soa.Client.Model.Strong.TcUsageProxy]) -> bool: ...
    def RefreshProxies2(self, ProxyObjectInput: list[Teamcenter.Soa.Client.Model.Strong.Cba0PersistentProxy]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def PerformMultilevelEngineeringBreakdown(self, InputBreakdownCriteria: Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_05.QueryManagement.BreakDownCriteria) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_05.QueryManagement.MultilevelEngineeringBreakdownResponse: ...
    def GetPMMProxyObjectFromPMMComponent(self, Input: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.QueryManagement.PMMComponentInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.QueryManagement.PMMProxyObjectResponse: ...
    def PerformMultilevelACTBreakdown(self, InputBreakDownCriteria: Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_05.QueryManagement.BreakDownCriteria) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.QueryManagement.MultilevelACTBreakdownResponse: ...

class QueryManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> QueryManagementService: ...
    def RefreshProxies(self, ProxyObjectInput: list[Teamcenter.Soa.Client.Model.Strong.TcUsageProxy]) -> bool: ...
    def RefreshProxies2(self, ProxyObjectInput: list[Teamcenter.Soa.Client.Model.Strong.Cba0PersistentProxy]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def PerformMultilevelEngineeringBreakdown(self, InputBreakdownCriteria: Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_05.QueryManagement.BreakDownCriteria) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_05.QueryManagement.MultilevelEngineeringBreakdownResponse: ...
    def GetPMMProxyObjectFromPMMComponent(self, Input: list[Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.QueryManagement.PMMComponentInfo]) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.QueryManagement.PMMProxyObjectResponse: ...
    def PerformMultilevelACTBreakdown(self, InputBreakDownCriteria: Teamcenter.Services.Internal.Strong.Cadbomalignment._2013_05.QueryManagement.BreakDownCriteria) -> Teamcenter.Services.Internal.Strong.Cadbomalignment._2014_12.QueryManagement.MultilevelACTBreakdownResponse: ...

