import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections
import typing

import System
import System.Collections

import System
import System.Collections

import System
import System.Collections

import System
import System.Collections

import System
import System.Collections

import System
import System.Collections

from System import Array, Boolean, Int32, String, Void
from System.Collections import IEnumerator

from System import Array, Boolean, Int32, String, Void
from System.Collections import IEnumerator

    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: String[], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(fileExtension: str) -> str: ...
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(fileExtension: String) -> String: ...
    def AddExtension(fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: list[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(fileExtension: String) -> String: ...
    def AddExtension(fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(fileExtension: String) -> String: ...
    def AddExtension(fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(fileExtension: String) -> String: ...
    def AddExtension(fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: Int32
    TempDir: String
    BasePath: String
    KeepFiles: Boolean
    def AddExtension(self, fileExtension: String) -> String: ...
    def AddExtension(self, fileExtension: String, keepFile: Boolean) -> String: ...
    def AddFile(self, fileName: String, keepFile: Boolean) -> Void: ...
    def GetEnumerator(self) -> IEnumerator: ...
    def CopyTo(self, fileNames: Array[String], start: Int32) -> Void: ...
    def get_Count(self) -> Int32: ...
    def get_TempDir(self) -> String: ...
    def get_BasePath(self) -> String: ...
    def get_KeepFiles(self) -> Boolean: ...
    def set_KeepFiles(self, value: Boolean) -> Void: ...
    def Delete(self) -> Void: ...

class TempFileCollection:
    Count: System.Int32
    TempDir: System.String
    BasePath: System.String
    KeepFiles: System.Boolean
    def AddExtension(self, fileExtension: System.String) -> System.String: ...
    def AddExtension(self, fileExtension: System.String, keepFile: System.Boolean) -> System.String: ...
    def AddFile(self, fileName: System.String, keepFile: System.Boolean) -> System.Void: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: System.Array[System.String], start: System.Int32) -> System.Void: ...
    def get_Count(self) -> System.Int32: ...
    def get_TempDir(self) -> System.String: ...
    def get_BasePath(self) -> System.String: ...
    def get_KeepFiles(self) -> System.Boolean: ...
    def set_KeepFiles(self, value: System.Boolean) -> System.Void: ...
    def Delete(self) -> System.Void: ...

class TempFileCollection:
    Count: System.Int32
    TempDir: System.String
    BasePath: System.String
    KeepFiles: System.Boolean
    def AddExtension(self, fileExtension: System.String) -> System.String: ...
    def AddExtension(self, fileExtension: System.String, keepFile: System.Boolean) -> System.String: ...
    def AddFile(self, fileName: System.String, keepFile: System.Boolean) -> System.Void: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: System.Array[System.String], start: System.Int32) -> System.Void: ...
    def get_Count(self) -> System.Int32: ...
    def get_TempDir(self) -> System.String: ...
    def get_BasePath(self) -> System.String: ...
    def get_KeepFiles(self) -> System.Boolean: ...
    def set_KeepFiles(self, value: System.Boolean) -> System.Void: ...
    def Delete(self) -> System.Void: ...

class TempFileCollection:
    Count: System.Int32
    TempDir: System.String
    BasePath: System.String
    KeepFiles: System.Boolean
    def AddExtension(self, fileExtension: System.String) -> System.String: ...
    def AddExtension(self, fileExtension: System.String, keepFile: System.Boolean) -> System.String: ...
    def AddFile(self, fileName: System.String, keepFile: System.Boolean) -> System.Void: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[System.String], start: System.Int32) -> System.Void: ...
    def get_Count(self) -> System.Int32: ...
    def get_TempDir(self) -> System.String: ...
    def get_BasePath(self) -> System.String: ...
    def get_KeepFiles(self) -> System.Boolean: ...
    def set_KeepFiles(self, value: System.Boolean) -> System.Void: ...
    def Delete(self) -> System.Void: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(self, fileExtension: str) -> str: ...
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(self, fileExtension: str) -> str: ...
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    def AddExtension(self, fileExtension: str) -> str: ...
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(fileExtension: str, keepFile: bool) -> str: ...
    @staticmethod
    def AddFile(fileName: str, keepFile: bool) -> None: ...
    @staticmethod
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    @staticmethod
    def CopyTo(fileNames: list[str], start: int) -> None: ...
    @staticmethod
    def get_Count(self) -> int: ...
    @staticmethod
    def get_TempDir(self) -> str: ...
    @staticmethod
    def get_BasePath(self) -> str: ...
    @staticmethod
    def get_KeepFiles(self) -> bool: ...
    @staticmethod
    def set_KeepFiles(value: bool) -> None: ...
    @staticmethod
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

class TempFileCollection:
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...
    def __init__(self, ) -> TempFileCollection: ...
    def __init__(self, tempDir: str) -> TempFileCollection: ...
    def __init__(self, tempDir: str, keepFiles: bool) -> TempFileCollection: ...

class TempFileCollection:
    @typing.overload
    def __init__(self, ) -> None: ...
    @typing.overload
    def __init__(self, tempDir: str) -> None: ...
    @typing.overload
    def __init__(self, tempDir: str, keepFiles: bool) -> None: ...
    Count: int
    TempDir: str
    BasePath: str
    KeepFiles: bool
    @typing.overload
    def AddExtension(self, fileExtension: str) -> str: ...
    @typing.overload
    def AddExtension(self, fileExtension: str, keepFile: bool) -> str: ...
    def AddFile(self, fileName: str, keepFile: bool) -> None: ...
    def GetEnumerator(self) -> System.Collections.IEnumerator: ...
    def CopyTo(self, fileNames: list[str], start: int) -> None: ...
    def get_Count(self) -> int: ...
    def get_TempDir(self) -> str: ...
    def get_BasePath(self) -> str: ...
    def get_KeepFiles(self) -> bool: ...
    def set_KeepFiles(self, value: bool) -> None: ...
    def Delete(self) -> None: ...

