import System
import System.Collections
import Teamcenter.Services.Internal.Strong.Manufacturing._2008_12.Core
import Teamcenter.Services.Internal.Strong.Manufacturing._2011_12.DataManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch
import Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.DataManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.IPAManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.IPAManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model
import Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.ResourceManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments
import Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureSearch
import Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureSearch
import Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.ResourceManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureSearch
import Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.DataManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.StructureManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.ResourceManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.ResourceManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor
import Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ResourceManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.StructureSearch
import Teamcenter.Services.Internal.Strong.Manufacturing._2020_01.DataManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2020_01.StructureSearch
import Teamcenter.Services.Internal.Strong.Manufacturing._2020_04.DataManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2020_12.DataManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2021_06.ResourceManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2022_12.ResourceManagement
import Teamcenter.Services.Internal.Strong.Manufacturing._2023_06.ResourceManagement
import Teamcenter.Services.Strong.Manufacturing._2013_12.ResourceManagement
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong
import typing

class AttachmentsRestBindingStub(AttachmentsService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateAttachmentLines(self, AttachmentsInputList: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments.CreateAttachmentsInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments.AttachmentResponse: ...
    def GetAttachmentLines(self, InputList: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments.AttachmentsInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments.AttachmentLines: ...

class AttachmentsService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> AttachmentsService: ...
    def CreateAttachmentLines(self, AttachmentsInputList: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments.CreateAttachmentsInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments.AttachmentResponse: ...
    def GetAttachmentLines(self, InputList: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments.AttachmentsInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.Attachments.AttachmentLines: ...

class ClosureRuleEditorRestBindingStub(ClosureRuleEditorService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetClosureRuleTraversalInfo(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor.ClosureRuleTraversalInput) -> Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor.ClosureRuleTraversalResponse: ...
    def SetClosureRuleTraversalInfo(self, UpdatedTraversalInfo: System.Collections.Hashtable, ClosureRuleName: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class ClosureRuleEditorService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ClosureRuleEditorService: ...
    def GetClosureRuleTraversalInfo(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor.ClosureRuleTraversalInput) -> Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ClosureRuleEditor.ClosureRuleTraversalResponse: ...
    def SetClosureRuleTraversalInfo(self, UpdatedTraversalInfo: System.Collections.Hashtable, ClosureRuleName: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class CoreRestBindingStub(CoreService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CheckinForProcessSimulate(self, RootLines: list[Teamcenter.Soa.Client.Model.ModelObject], Params: Teamcenter.Services.Internal.Strong.Manufacturing._2008_12.Core.CheckinInput) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def CheckoutForProcessSimulate(self, RootLines: list[Teamcenter.Soa.Client.Model.ModelObject], Params: Teamcenter.Services.Internal.Strong.Manufacturing._2008_12.Core.CheckoutInput) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class CoreService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> CoreService: ...
    def CheckinForProcessSimulate(self, RootLines: list[Teamcenter.Soa.Client.Model.ModelObject], Params: Teamcenter.Services.Internal.Strong.Manufacturing._2008_12.Core.CheckinInput) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def CheckoutForProcessSimulate(self, RootLines: list[Teamcenter.Soa.Client.Model.ModelObject], Params: Teamcenter.Services.Internal.Strong.Manufacturing._2008_12.Core.CheckoutInput) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class DataManagementRestBindingStub(DataManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def PostAssignIDICMaker(self, PostAssignInput: list[Teamcenter.Services.Internal.Strong.Manufacturing._2011_12.DataManagement.PostAssignIDICInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2011_12.DataManagement.PostAssignIDICResponse: ...
    def AutomaticMFGFeaturesAssignment(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.DataManagement.AutomaticMFGFeaturesAssignmentInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.DataManagement.AutomaticMFGFeaturesAssignmentResponse: ...
    def LinkPlantBOPtoBOE(self, LinkBOPtoBOEObjectInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.LinkBOPtoBOEObjectInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.LinkPlantBOPtoBOEResponse: ...
    def SynchronizePlantBOPAndBOE(self, SynchronizeBopAndBoeInputInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.SynchronizeBOPAndBOEInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.SynchronizePlantBOPAndBOEResponse: ...
    def CreateBOEfromPlantBOP(self, RootBOPLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.CreateBOEfromPlantBOPResponse: ...
    def GetFutureRevisions(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.DataManagement.GetFutureRevisionsIn]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.DataManagement.GetFutureRevisionsResponse: ...
    def AssociateOrRemoveScopesForProcess(self, AssociateOrRemoveInput: list[Teamcenter.Services.Internal.Strong.Manufacturing._2020_01.DataManagement.AssociateOrRemoveScopeInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetProductScopeForProcess(self, ProcessLine: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2020_04.DataManagement.GetProductScopeForProcessResponse: ...
    def GetReferencedAssemblyFileInfo(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2020_12.DataManagement.ReferencedAssemblyFileInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2020_12.DataManagement.ReferencedAssemblyFileResponse: ...

class DataManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> DataManagementService: ...
    def PostAssignIDICMaker(self, PostAssignInput: list[Teamcenter.Services.Internal.Strong.Manufacturing._2011_12.DataManagement.PostAssignIDICInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2011_12.DataManagement.PostAssignIDICResponse: ...
    def AutomaticMFGFeaturesAssignment(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.DataManagement.AutomaticMFGFeaturesAssignmentInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.DataManagement.AutomaticMFGFeaturesAssignmentResponse: ...
    def LinkPlantBOPtoBOE(self, LinkBOPtoBOEObjectInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.LinkBOPtoBOEObjectInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.LinkPlantBOPtoBOEResponse: ...
    def SynchronizePlantBOPAndBOE(self, SynchronizeBopAndBoeInputInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.SynchronizeBOPAndBOEInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.SynchronizePlantBOPAndBOEResponse: ...
    def CreateBOEfromPlantBOP(self, RootBOPLines: list[Teamcenter.Soa.Client.Model.Strong.BOMLine]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.DataManagement.CreateBOEfromPlantBOPResponse: ...
    def GetFutureRevisions(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.DataManagement.GetFutureRevisionsIn]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.DataManagement.GetFutureRevisionsResponse: ...
    def AssociateOrRemoveScopesForProcess(self, AssociateOrRemoveInput: list[Teamcenter.Services.Internal.Strong.Manufacturing._2020_01.DataManagement.AssociateOrRemoveScopeInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetProductScopeForProcess(self, ProcessLine: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2020_04.DataManagement.GetProductScopeForProcessResponse: ...
    def GetReferencedAssemblyFileInfo(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2020_12.DataManagement.ReferencedAssemblyFileInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2020_12.DataManagement.ReferencedAssemblyFileResponse: ...

class IPAManagementRestBindingStub(IPAManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    @typing.overload
    def CleanDynamicIPALines(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.IPAManagement.CleanDynamicIPALinesInfo) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    @typing.overload
    def CleanDynamicIPALines(self, InputLines: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPAInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.CleanDynamicIPALinesResponse: ...
    def GetDynamicIPALines(self, InputBOPLines: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.IPAManagement.GetDynamicIPALinesResponse: ...
    def SearchDynamicIPAs(self, SearchScopes: list[Teamcenter.Soa.Client.Model.ModelObject], ReturnOnFirstResult: bool) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.IPAManagement.SearchDynamicIPAsResponse: ...
    def CreateDynamicIPALines(self, InputLines: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPAInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPALinesResponse: ...
    def SaveContentOfDynamicIPALines(self, InputDIPALines: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.SaveDynamicIPALinesResponse: ...
    def UpdateDynamicIPALines(self, InputLines: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPAInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPALinesResponse: ...

class IPAManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> IPAManagementService: ...
    @typing.overload
    def CleanDynamicIPALines(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.IPAManagement.CleanDynamicIPALinesInfo) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    @typing.overload
    def CleanDynamicIPALines(self, InputLines: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPAInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.CleanDynamicIPALinesResponse: ...
    def GetDynamicIPALines(self, InputBOPLines: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_06.IPAManagement.GetDynamicIPALinesResponse: ...
    def SearchDynamicIPAs(self, SearchScopes: list[Teamcenter.Soa.Client.Model.ModelObject], ReturnOnFirstResult: bool) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.IPAManagement.SearchDynamicIPAsResponse: ...
    def CreateDynamicIPALines(self, InputLines: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPAInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPALinesResponse: ...
    def SaveContentOfDynamicIPALines(self, InputDIPALines: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.SaveDynamicIPALinesResponse: ...
    def UpdateDynamicIPALines(self, InputLines: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPAInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.IPAManagement.DynamicIPALinesResponse: ...

class ModelRestBindingStub(ModelService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def DeleteScopeFlows(self, ScopeFlowsInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.ScopeFlowInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetUILocations(self, ContextLines: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.UILocationsInfoResponse: ...
    def SaveUILocations(self, UiLocationsInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.UILocationInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ScheduleLAResolve(self, LaResolveData: Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.LAResolveAsyncData, BatchDetails: Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.LABatchDetails) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class ModelService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ModelService: ...
    def DeleteScopeFlows(self, ScopeFlowsInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.ScopeFlowInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetUILocations(self, ContextLines: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.UILocationsInfoResponse: ...
    def SaveUILocations(self, UiLocationsInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.UILocationInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ScheduleLAResolve(self, LaResolveData: Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.LAResolveAsyncData, BatchDetails: Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.Model.LABatchDetails) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class ResourceManagementRestBindingStub(ResourceManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ShowCoordinateSystems(self, BomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow, ShowCoordinateSystems: bool) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ShowGCSConnectionPoints(self, BomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow, ShowGCSConnectionPointsOption: int) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetStepP21FileCounts2(self, ClassIds: list[str], CatalogRootDirectories: list[str]) -> Teamcenter.Services.Strong.Manufacturing._2013_12.ResourceManagement.GetStepP21FileCountsResponse: ...
    def GetVendorCatalogInfo2(self, CatalogTypes: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.ResourceManagement.GetVendorCatalogInfo2Response: ...
    def ImportStepP21Files2(self, ClassId: str, CatalogRootDirectory: str, ImportOptions: int) -> Teamcenter.Services.Strong.Manufacturing._2013_12.ResourceManagement.ImportStepP21FilesResponse: ...
    def ImportStep3DModels2(self, IcoIds: list[str]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement.ImportStep3DModels2Response: ...
    def ImportStepP21Files3(self, ClassId: str, CatalogRootDirectory: str, ImportOption: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement.ImportStepP21Files3Response: ...
    def MapClassificationObject(self, SourceIcoId: str, TargetItemId: str, TargetItemName: str, TargetItemTypeName: str, TargetItemRevId: str, TargetItemDescription: str, TargetClassId: str, Options: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement.MapClassificationObjectResponse: ...
    def UnzipGtcPackage(self, TransientFmsZipFileTicket: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement.UnzipGtcPackageResponse: ...
    def CreateSetupSheets(self, IcoIds: list[str]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ExtractHolderData(self, IcoIds: list[str]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetVendorCatalogInfo3(self, CatalogTypeFilter: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.ResourceManagement.GetVendorCatalogInfo3Response: ...
    def AddMultiToolCutter(self, StrItemRevUID: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.ResourceManagement.AddMultiToolCutterResponse: ...
    def DeleteMultiToolCutter(self, DeleteICOUID: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.ResourceManagement.DeleteMultiToolCutterResponse: ...
    def AutoPositionComponentByCSYS(self, StrSourceBOMLines: list[str], StrTargetBOMLine: str, StrSourceCSYS: str, StrTargetCSYS: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.ResourceManagement.AutoPositionComponentByCSYSResponse: ...
    def GetICOMappingTargets(self, IcoUIDs: list[str], ViewType: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ResourceManagement.GetICOMappingTargetsResponse: ...
    def GuidedComponentSearchForOccurrence(self, OccUID: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2021_06.ResourceManagement.GuidedComponentSearchForOccResponse: ...
    def ImportVendorData(self, ImportVendorDataIn: Teamcenter.Services.Internal.Strong.Manufacturing._2022_12.ResourceManagement.ImportVendorDataIn) -> Teamcenter.Services.Internal.Strong.Manufacturing._2022_12.ResourceManagement.ImportVendorDataResponse: ...
    def ImportVendorData2(self, ImportVendorData2In: Teamcenter.Services.Internal.Strong.Manufacturing._2023_06.ResourceManagement.ImportVendorData2In) -> Teamcenter.Services.Internal.Strong.Manufacturing._2023_06.ResourceManagement.ImportVendorData2Response: ...

class ResourceManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ResourceManagementService: ...
    def ShowCoordinateSystems(self, BomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow, ShowCoordinateSystems: bool) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ShowGCSConnectionPoints(self, BomWindow: Teamcenter.Soa.Client.Model.Strong.BOMWindow, ShowGCSConnectionPointsOption: int) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetStepP21FileCounts2(self, ClassIds: list[str], CatalogRootDirectories: list[str]) -> Teamcenter.Services.Strong.Manufacturing._2013_12.ResourceManagement.GetStepP21FileCountsResponse: ...
    def GetVendorCatalogInfo2(self, CatalogTypes: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2014_12.ResourceManagement.GetVendorCatalogInfo2Response: ...
    def ImportStepP21Files2(self, ClassId: str, CatalogRootDirectory: str, ImportOptions: int) -> Teamcenter.Services.Strong.Manufacturing._2013_12.ResourceManagement.ImportStepP21FilesResponse: ...
    def ImportStep3DModels2(self, IcoIds: list[str]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement.ImportStep3DModels2Response: ...
    def ImportStepP21Files3(self, ClassId: str, CatalogRootDirectory: str, ImportOption: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement.ImportStepP21Files3Response: ...
    def MapClassificationObject(self, SourceIcoId: str, TargetItemId: str, TargetItemName: str, TargetItemTypeName: str, TargetItemRevId: str, TargetItemDescription: str, TargetClassId: str, Options: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement.MapClassificationObjectResponse: ...
    def UnzipGtcPackage(self, TransientFmsZipFileTicket: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.ResourceManagement.UnzipGtcPackageResponse: ...
    def CreateSetupSheets(self, IcoIds: list[str]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ExtractHolderData(self, IcoIds: list[str]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetVendorCatalogInfo3(self, CatalogTypeFilter: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.ResourceManagement.GetVendorCatalogInfo3Response: ...
    def AddMultiToolCutter(self, StrItemRevUID: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.ResourceManagement.AddMultiToolCutterResponse: ...
    def DeleteMultiToolCutter(self, DeleteICOUID: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.ResourceManagement.DeleteMultiToolCutterResponse: ...
    def AutoPositionComponentByCSYS(self, StrSourceBOMLines: list[str], StrTargetBOMLine: str, StrSourceCSYS: str, StrTargetCSYS: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.ResourceManagement.AutoPositionComponentByCSYSResponse: ...
    def GetICOMappingTargets(self, IcoUIDs: list[str], ViewType: int) -> Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.ResourceManagement.GetICOMappingTargetsResponse: ...
    def GuidedComponentSearchForOccurrence(self, OccUID: str) -> Teamcenter.Services.Internal.Strong.Manufacturing._2021_06.ResourceManagement.GuidedComponentSearchForOccResponse: ...
    def ImportVendorData(self, ImportVendorDataIn: Teamcenter.Services.Internal.Strong.Manufacturing._2022_12.ResourceManagement.ImportVendorDataIn) -> Teamcenter.Services.Internal.Strong.Manufacturing._2022_12.ResourceManagement.ImportVendorDataResponse: ...
    def ImportVendorData2(self, ImportVendorData2In: Teamcenter.Services.Internal.Strong.Manufacturing._2023_06.ResourceManagement.ImportVendorData2In) -> Teamcenter.Services.Internal.Strong.Manufacturing._2023_06.ResourceManagement.ImportVendorData2Response: ...

class StructureManagementRestBindingStub(StructureManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def AlignAssemblies(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.AlignAssemblyData]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ConfigureMultipleStructures(self, ConfigurationsInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.ConfigurationsInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.ConfigureMultipleStructuresResponse: ...
    def CreateReuseAssemblies(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.CreateReuseAssembly]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.CreateReuseAssemblyResp: ...
    def GetClusterDetails(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.GetClusterDetails]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SearchForClusters(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.SearchForClusters]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.SearchForClustersResponse: ...
    def AlignLinesInBOM(self, AlignInputs: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.AlignLinesInBOMData]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.AlignLinesInBOMResponse: ...
    def GetEquivalentPropertyValues(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.GetEquivalentPropValuesElement]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.GetEquivalentPropValuesResp: ...
    def PasteOrReplaceAssemblyInContext(self, AssemblyInContextInput: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.PasteOrReplaceAssemblyInContextInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.PasteOrReplaceAssemblyInContextResponse: ...
    def CompletenessCheckPartStructure(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.ObjectAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.CompletenessCheckPartStructureResp: ...
    def CreateOrUpdateDesignPartAlignment(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.CreateDesignPartAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentResponse: ...
    def FindRelatedDesignOrPartStructures(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.ObjectAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentResponse: ...
    def LinkOrUnlinkStructures(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.LinkStructuresInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.LinkStructuresResponse: ...
    def RemoveDesignPartAlignment(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.ObjectAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentResponse: ...
    def VerifyDesignPartAlignment(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentResponse: ...
    def SyncMasterAndAlternative(self, SyncMasterAndAlternativeInputInfo: Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.StructureManagement.SyncMasterAndAlternativeInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.StructureManagement.SyncMasterAndAlternativeResponse: ...
    def CreateAlternativeScopeForProduct(self, AltenativeScpForProdInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement.AlternativeScopeForProductInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement.AlternativeScopeForProductResponse: ...
    def PasteByRule(self, InputInfo: Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement.PasteByRuleInfoInput) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement.PasteByRuleResponse: ...
    def EvaluateLinks(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.EvaluateLinksData]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.EvaluateLinksResponse: ...
    def FindBrokenPartsInProductView(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.FindBrokenPartsInPVInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.FindBrokenPartsInPVResponse: ...
    def FindBrokenProductViews(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.FindBrokenProductViewsInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.FindBrokenProductViewsResponse: ...

class StructureManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureManagementService: ...
    def AlignAssemblies(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.AlignAssemblyData]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ConfigureMultipleStructures(self, ConfigurationsInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.ConfigurationsInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.ConfigureMultipleStructuresResponse: ...
    def CreateReuseAssemblies(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.CreateReuseAssembly]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.CreateReuseAssemblyResp: ...
    def GetClusterDetails(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.GetClusterDetails]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SearchForClusters(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.SearchForClusters]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureManagement.SearchForClustersResponse: ...
    def AlignLinesInBOM(self, AlignInputs: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.AlignLinesInBOMData]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.AlignLinesInBOMResponse: ...
    def GetEquivalentPropertyValues(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.GetEquivalentPropValuesElement]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.GetEquivalentPropValuesResp: ...
    def PasteOrReplaceAssemblyInContext(self, AssemblyInContextInput: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.PasteOrReplaceAssemblyInContextInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureManagement.PasteOrReplaceAssemblyInContextResponse: ...
    def CompletenessCheckPartStructure(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.ObjectAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.CompletenessCheckPartStructureResp: ...
    def CreateOrUpdateDesignPartAlignment(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.CreateDesignPartAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentResponse: ...
    def FindRelatedDesignOrPartStructures(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.ObjectAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentResponse: ...
    def LinkOrUnlinkStructures(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.LinkStructuresInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.LinkStructuresResponse: ...
    def RemoveDesignPartAlignment(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.ObjectAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentResponse: ...
    def VerifyDesignPartAlignment(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureManagement.DesignPartAlignmentResponse: ...
    def SyncMasterAndAlternative(self, SyncMasterAndAlternativeInputInfo: Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.StructureManagement.SyncMasterAndAlternativeInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_05.StructureManagement.SyncMasterAndAlternativeResponse: ...
    def CreateAlternativeScopeForProduct(self, AltenativeScpForProdInfo: list[Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement.AlternativeScopeForProductInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement.AlternativeScopeForProductResponse: ...
    def PasteByRule(self, InputInfo: Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement.PasteByRuleInfoInput) -> Teamcenter.Services.Internal.Strong.Manufacturing._2017_11.StructureManagement.PasteByRuleResponse: ...
    def EvaluateLinks(self, Input: list[Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.EvaluateLinksData]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.EvaluateLinksResponse: ...
    def FindBrokenPartsInProductView(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.FindBrokenPartsInPVInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.FindBrokenPartsInPVResponse: ...
    def FindBrokenProductViews(self, Input: Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.FindBrokenProductViewsInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2018_11.StructureManagement.FindBrokenProductViewsResponse: ...

class StructureSearchRestBindingStub(StructureSearchService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def MapSrchCriteriaToLines(self, Inputs: list[Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.MapSrchCriteriaToLinesInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.MapSrchCriteriaToLinesResponse: ...
    def SaveOGLinesInSrchCriteria(self, Inputs: list[Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.SaveOGLinesInSrchCriteriaInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.SaveOGLinesInSrchCriteriaResponse: ...
    def GetSearchCriteriaFromRecipe(self, Recipes: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureSearch.GetSearchCrieriaFromRecipeResp: ...
    def FindCollabPlanningContext(self, InputScopes: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureSearch.FindCPCResponse: ...
    def FindEquivalentLines(self, SearchInputs: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureSearch.FindEquivalentLinesIn]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureSearch.FindEquivalentLinesResp: ...
    def GetBOEForPlantBOPScope(self, SearchInput: Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureSearch.SearchBOEInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureSearch.SearchBOEResponse: ...
    def SearchPartsInProximityOfMFGFeatures(self, CriteriaInput: list[Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.StructureSearch.ProximityCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.StructureSearch.PartsInProximityResponse: ...
    def SearchScopedStructure(self, SearchScopedStructureInput: Teamcenter.Services.Internal.Strong.Manufacturing._2020_01.StructureSearch.SearchScopedStructureInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2020_01.StructureSearch.SearchScopedStructureResponse: ...

class StructureSearchService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureSearchService: ...
    def MapSrchCriteriaToLines(self, Inputs: list[Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.MapSrchCriteriaToLinesInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.MapSrchCriteriaToLinesResponse: ...
    def SaveOGLinesInSrchCriteria(self, Inputs: list[Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.SaveOGLinesInSrchCriteriaInputInfo]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2012_09.StructureSearch.SaveOGLinesInSrchCriteriaResponse: ...
    def GetSearchCriteriaFromRecipe(self, Recipes: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_03.StructureSearch.GetSearchCrieriaFromRecipeResp: ...
    def FindCollabPlanningContext(self, InputScopes: list[Teamcenter.Soa.Client.Model.ModelObject]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureSearch.FindCPCResponse: ...
    def FindEquivalentLines(self, SearchInputs: list[Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureSearch.FindEquivalentLinesIn]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2015_10.StructureSearch.FindEquivalentLinesResp: ...
    def GetBOEForPlantBOPScope(self, SearchInput: Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureSearch.SearchBOEInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2016_09.StructureSearch.SearchBOEResponse: ...
    def SearchPartsInProximityOfMFGFeatures(self, CriteriaInput: list[Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.StructureSearch.ProximityCriteriaInput]) -> Teamcenter.Services.Internal.Strong.Manufacturing._2019_06.StructureSearch.PartsInProximityResponse: ...
    def SearchScopedStructure(self, SearchScopedStructureInput: Teamcenter.Services.Internal.Strong.Manufacturing._2020_01.StructureSearch.SearchScopedStructureInputInfo) -> Teamcenter.Services.Internal.Strong.Manufacturing._2020_01.StructureSearch.SearchScopedStructureResponse: ...

