import System
import Teamcenter.Services.Internal.Strong.Vendormanagement._2008_05.VendorManagement
import Teamcenter.Services.Internal.Strong.Vendormanagement._2008_06.VendorManagement
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class VendorManagementRestBindingStub(VendorManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateOrUpdateLineItems(self, Properties: list[Teamcenter.Services.Internal.Strong.Vendormanagement._2008_05.VendorManagement.LineItemPropsWithType], BidPackage: Teamcenter.Soa.Client.Model.ModelObject) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetItemIDwithContext(self, Input: list[Teamcenter.Services.Internal.Strong.Vendormanagement._2008_05.VendorManagement.ItemIDInput]) -> Teamcenter.Services.Internal.Strong.Vendormanagement._2008_05.VendorManagement.ItemIDResponse: ...
    def GetVPSRConditions(self) -> Teamcenter.Services.Internal.Strong.Vendormanagement._2008_06.VendorManagement.GetVPSRConditionsResponse: ...

class VendorManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> VendorManagementService: ...
    def CreateOrUpdateLineItems(self, Properties: list[Teamcenter.Services.Internal.Strong.Vendormanagement._2008_05.VendorManagement.LineItemPropsWithType], BidPackage: Teamcenter.Soa.Client.Model.ModelObject) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetItemIDwithContext(self, Input: list[Teamcenter.Services.Internal.Strong.Vendormanagement._2008_05.VendorManagement.ItemIDInput]) -> Teamcenter.Services.Internal.Strong.Vendormanagement._2008_05.VendorManagement.ItemIDResponse: ...
    def GetVPSRConditions(self) -> Teamcenter.Services.Internal.Strong.Vendormanagement._2008_06.VendorManagement.GetVPSRConditionsResponse: ...

