import Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement
import Teamcenter.Soa.Client

class StructureManagementRestBindingStub(StructureManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetAlignedDesigns(self, Input: Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement.GetAlignDesignsInput) -> Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement.GetAlignedDesignsResp: ...
    def GetAlignedPartsCsidChain(self, Input: Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement.GetAlignedPartsInput) -> Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement.GetAlignedPartsCsidChainResp: ...

class StructureManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureManagementService: ...
    def GetAlignedDesigns(self, Input: Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement.GetAlignDesignsInput) -> Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement.GetAlignedDesignsResp: ...
    def GetAlignedPartsCsidChain(self, Input: Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement.GetAlignedPartsInput) -> Teamcenter.Services.Internal.Strong.Bom._2021_12.StructureManagement.GetAlignedPartsCsidChainResp: ...

