import System
import Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong
import typing

class StructureManagement:
    def __init__(self , *args: typing.Any) -> None: ...
    def CreateNewModelByDM(self, ProductBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelParentBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelExistingBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, Domain: str) -> Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement.ExecuteRuleResponse: ...
    def ExecuteMarkUpToDate(self, InputItemRevList: list[Teamcenter.Soa.Client.Model.Strong.CAEItemRevision]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def UpdateModelAttsByDM(self, ProductBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelParentBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelRevTag: Teamcenter.Soa.Client.Model.Strong.ItemRevision, ModelExistingBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, Domain: str, BomlineAttribsOnly: bool, DoRevise: bool) -> Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement.ExecuteRuleResponse: ...

