import System
import Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport
import Teamcenter.Services.Internal.Strong.Importexport._2017_11.FileImportExport
import Teamcenter.Services.Internal.Strong.Importexport._2018_06.L10NImportExport
import Teamcenter.Services.Strong.Importexport._2011_06.FileImportExport
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class FileImportExportRestBindingStub(FileImportExportService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ImportDocumentOffline(self, Inputs: list[Teamcenter.Services.Internal.Strong.Importexport._2017_11.FileImportExport.ImportDocumentInputData]) -> Teamcenter.Services.Strong.Importexport._2011_06.FileImportExport.ImportFromApplicationResponse1: ...

class FileImportExportService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> FileImportExportService: ...
    def ImportDocumentOffline(self, Inputs: list[Teamcenter.Services.Internal.Strong.Importexport._2017_11.FileImportExport.ImportDocumentInputData]) -> Teamcenter.Services.Strong.Importexport._2011_06.FileImportExport.ImportFromApplicationResponse1: ...

class L10NImportExportRestBindingStub(L10NImportExportService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ExportObjectsForTranslation(self, InpuInfo: Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ObjectsInfo) -> Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ExportObjectsForTranslationResponse: ...
    def FilterObjectsForTranslation(self, InputInfo: Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ObjectsInfo) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ImportTranslations(self, FileInfo: list[Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.TransientFileTicketStatusInfo]) -> Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ExportObjectsForTranslationResponse: ...
    def ExportObjectsForTranslation2(self, InputObjectsInfo: Teamcenter.Services.Internal.Strong.Importexport._2018_06.L10NImportExport.ObjectsInfo2) -> Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ExportObjectsForTranslationResponse: ...

class L10NImportExportService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> L10NImportExportService: ...
    def ExportObjectsForTranslation(self, InpuInfo: Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ObjectsInfo) -> Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ExportObjectsForTranslationResponse: ...
    def FilterObjectsForTranslation(self, InputInfo: Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ObjectsInfo) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def ImportTranslations(self, FileInfo: list[Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.TransientFileTicketStatusInfo]) -> Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ExportObjectsForTranslationResponse: ...
    def ExportObjectsForTranslation2(self, InputObjectsInfo: Teamcenter.Services.Internal.Strong.Importexport._2018_06.L10NImportExport.ObjectsInfo2) -> Teamcenter.Services.Internal.Strong.Importexport._2010_04.L10NImportExport.ExportObjectsForTranslationResponse: ...

