import System
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation
import Val0.Services.Internal.Strong.Nxvalidation._2017_11.NXValidation

class NXValidationRestBindingStub(NXValidationService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateOrUpdateValidationResults(self, CreateOrUpdateInputs: list[Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation.CreateInput], GetResultsInputs: list[Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation.GetResultsInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def DeleteValidationResults(self, DeleteResultsInputs: list[Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation.DeleteResultsInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetValidationResults(self, GetResultsInputs: list[Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation.GetResultsInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def RunValidations(self, ValidationContextList: list[Val0.Services.Internal.Strong.Nxvalidation._2017_11.NXValidation.ValidationContext]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class NXValidationService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> NXValidationService: ...
    def CreateOrUpdateValidationResults(self, CreateOrUpdateInputs: list[Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation.CreateInput], GetResultsInputs: list[Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation.GetResultsInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def DeleteValidationResults(self, DeleteResultsInputs: list[Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation.DeleteResultsInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetValidationResults(self, GetResultsInputs: list[Val0.Services.Internal.Strong.Nxvalidation._2016_10.NXValidation.GetResultsInput]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def RunValidations(self, ValidationContextList: list[Val0.Services.Internal.Strong.Nxvalidation._2017_11.NXValidation.ValidationContext]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

