import System.Configuration

import System.Configuration

import System.Configuration

import System.Configuration

import System.Configuration

import System.Configuration

import System.Configuration
import typing

import System.Configuration
import typing

import System.Configuration
import typing

import System.Configuration
import typing

import System.Configuration
import typing

import System.Configuration
import typing

import System.Configuration
import typing

import System.Configuration

import System.Configuration

import System.Configuration

import System
import System.Configuration

import System
import System.Configuration

import System
import System.Configuration

from System import String, Void
from System.Configuration import ConfigurationSection

from System import String, Void
from System.Configuration import ConfigurationSection

    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(ConfigurationSection):
    BitmapSuffix: String
    def get_BitmapSuffix(self) -> String: ...
    def set_BitmapSuffix(self, value: String) -> Void: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: System.String
    def get_BitmapSuffix(self) -> System.String: ...
    def set_BitmapSuffix(self, value: System.String) -> System.Void: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: System.String
    def get_BitmapSuffix(self) -> System.String: ...
    def set_BitmapSuffix(self, value: System.String) -> System.Void: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: System.String
    def get_BitmapSuffix(self) -> System.String: ...
    def set_BitmapSuffix(self, value: System.String) -> System.Void: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    @staticmethod
    def get_BitmapSuffix(self) -> str: ...
    @staticmethod
    def set_BitmapSuffix(value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...
    def __init__(self, ) -> SystemDrawingSection: ...

class SystemDrawingSection(System.Configuration.ConfigurationSection):
    def __init__(self, ) -> None: ...
    BitmapSuffix: str
    def get_BitmapSuffix(self) -> str: ...
    def set_BitmapSuffix(self, value: str) -> None: ...

