import System
import System.Collections
import System.Globalization
import System.IO
import System.Net
import Teamcenter.Soa.Internal.Client
import typing

class Helpers:
    def __init__(self, ) -> None: ...
    MIN_RADIX: int
    MAX_RADIX: int
    @staticmethod
    def ForDigit(digit: int, radix: int) -> System.Char: ...
    @staticmethod
    def String2Bool(s: str) -> bool: ...
    @staticmethod
    def Array2ArrayList(inp: list[typing.Any]) -> System.Collections.ArrayList: ...
    @staticmethod
    def SetTimeInMillis(timetoAdd: int) -> System.Globalization.GregorianCalendar: ...

class HttpClient:
    @typing.overload
    def __init__(self, cookies: System.Net.CookieCollection) -> None: ...
    @typing.overload
    def __init__(self, httpConfiguration: Teamcenter.Soa.Internal.Client.HttpConfiguration) -> None: ...
    Configuration: Teamcenter.Soa.Internal.Client.HttpConfiguration
    ResponseContentType: str
    ResponseServerHeader: str
    ResponseStatusCode: System.Net.HttpStatusCode
    Cookies: System.Net.CookieCollection
    @staticmethod
    def SetAllSecurityProtocols() -> System.Net.SecurityProtocolType: ...
    def get_Configuration(self) -> Teamcenter.Soa.Internal.Client.HttpConfiguration: ...
    def get_ResponseContentType(self) -> str: ...
    def get_ResponseServerHeader(self) -> str: ...
    def get_ResponseStatusCode(self) -> System.Net.HttpStatusCode: ...
    def get_Cookies(self) -> System.Net.CookieCollection: ...
    def MakeWebRequest(self, URL: System.Uri, method: str, postData: list[System.Byte]) -> System.IO.Stream: ...

class HttpMethods:
    def __init__(self, ) -> None: ...
    POST: str
    GET: str

