import Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.DataManagement
import Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch
import Fdp0.Services.Internal.Strong.Fourdplanning._2013_12.DataManagement
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class DataManagementRestBindingStub(DataManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def AutomaticProcessCreation(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.DataManagement.AutomaticProcessCreationInfo) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.DataManagement.AutomaticProcessCreationResponse: ...
    def CompareProcessWithScheduleTask(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_12.DataManagement.CompareProcessWithScheduleTaskInfo) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_12.DataManagement.CompareProcessWithScheduleTaskResponse: ...
    def PropagateScheduleChanges(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_12.DataManagement.PropagateScheduleChangesInfo) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class DataManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> DataManagementService: ...
    def AutomaticProcessCreation(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.DataManagement.AutomaticProcessCreationInfo) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.DataManagement.AutomaticProcessCreationResponse: ...
    def CompareProcessWithScheduleTask(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_12.DataManagement.CompareProcessWithScheduleTaskInfo) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_12.DataManagement.CompareProcessWithScheduleTaskResponse: ...
    def PropagateScheduleChanges(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_12.DataManagement.PropagateScheduleChangesInfo) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class StructureSearchRestBindingStub(StructureSearchService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def NextFourDSearch(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchInputInfo, FindLinesInProcStructure: bool, SearchCursor: Teamcenter.Soa.Client.Model.ModelObject) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchResultResponse: ...
    def StartFourDSearch(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchInputInfo) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchResultResponse: ...
    def StopFourDSearch(self, SearchCursor: Teamcenter.Soa.Client.Model.ModelObject) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchResultResponse: ...

class StructureSearchService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureSearchService: ...
    def NextFourDSearch(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchInputInfo, FindLinesInProcStructure: bool, SearchCursor: Teamcenter.Soa.Client.Model.ModelObject) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchResultResponse: ...
    def StartFourDSearch(self, Input: Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchInputInfo) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchResultResponse: ...
    def StopFourDSearch(self, SearchCursor: Teamcenter.Soa.Client.Model.ModelObject) -> Fdp0.Services.Internal.Strong.Fourdplanning._2013_05.StructureSearch.FourDSearchResultResponse: ...

