import Lis0.Services.Internal.Strong.Ldf._2017_05.LinkedDataRequest
import Lis0.Services.Internal.Strong.Ldf._2018_06.LinkedDataRequest
import Lis0.Services.Strong.Ldf._2015_03.LinkedDataRequest
import Lis0.Services.Strong.Ldf._2016_03.LinkedDataRequest
import System
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class LinkedDataRequestRestBindingStub(LinkedDataRequestService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GenerateJsonForRequest(self, ObjectStringAsUid: str, ServiceProviderStringAsUid: str, LdfLinkObjects: list[str]) -> Lis0.Services.Strong.Ldf._2015_03.LinkedDataRequest.LinkedResourceResponse: ...
    def GetOAuthRequestToken(self, UidServiceProvider: str) -> str: ...
    def RequestServerToFetchAccessToken(self, UidServiceProvider: str) -> bool: ...
    def SignURLForOAuth(self, UrlString: str, UidServiceProvider: str) -> str: ...
    def GetLDFPropertiesAndRelationTypes(self, UidContextObject: str, Url: str, UidServiceProvider: str) -> Lis0.Services.Internal.Strong.Ldf._2017_05.LinkedDataRequest.PropertiesRelationTypesStructure: ...
    def GetLDFServiceProviderList(self, UidContextObject: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetTCTypesFromSemanticTypes(self, SemanticType: str) -> Lis0.Services.Internal.Strong.Ldf._2017_05.LinkedDataRequest.LdfTcTypesNames: ...
    def GetLDFServicesForObject(self, UidServiceProvider: str, UidContextObject: str, FactoryOrUIService: int) -> Lis0.Services.Strong.Ldf._2016_03.LinkedDataRequest.LDFResponseInfoVec: ...
    def GetLDFSupportedDatasetTypes(self, LdfListFileExtensions: list[str]) -> Lis0.Services.Internal.Strong.Ldf._2018_06.LinkedDataRequest.LdfSupportedDatasetTypesResponse: ...

class LinkedDataRequestService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> LinkedDataRequestService: ...
    def GenerateJsonForRequest(self, ObjectStringAsUid: str, ServiceProviderStringAsUid: str, LdfLinkObjects: list[str]) -> Lis0.Services.Strong.Ldf._2015_03.LinkedDataRequest.LinkedResourceResponse: ...
    def GetOAuthRequestToken(self, UidServiceProvider: str) -> str: ...
    def RequestServerToFetchAccessToken(self, UidServiceProvider: str) -> bool: ...
    def SignURLForOAuth(self, UrlString: str, UidServiceProvider: str) -> str: ...
    def GetLDFPropertiesAndRelationTypes(self, UidContextObject: str, Url: str, UidServiceProvider: str) -> Lis0.Services.Internal.Strong.Ldf._2017_05.LinkedDataRequest.PropertiesRelationTypesStructure: ...
    def GetLDFServiceProviderList(self, UidContextObject: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetTCTypesFromSemanticTypes(self, SemanticType: str) -> Lis0.Services.Internal.Strong.Ldf._2017_05.LinkedDataRequest.LdfTcTypesNames: ...
    def GetLDFServicesForObject(self, UidServiceProvider: str, UidContextObject: str, FactoryOrUIService: int) -> Lis0.Services.Strong.Ldf._2016_03.LinkedDataRequest.LDFResponseInfoVec: ...
    def GetLDFSupportedDatasetTypes(self, LdfListFileExtensions: list[str]) -> Lis0.Services.Internal.Strong.Ldf._2018_06.LinkedDataRequest.LdfSupportedDatasetTypesResponse: ...

