import Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints
import System
import Teamcenter.Soa.Client

class GeometricconstraintsRestBindingStub(GeometricconstraintsService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetContainersUpToDateStatus(self, Containers: list[Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.ContainerToCheckInputInfo], NavOptions: Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.NavigationOptions, LinearTolerance: float, AngularTolerance: float) -> Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.GetContainersUpToDateStatusResponse: ...
    def GetUpToDateStatus(self, Inputs: list[Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.ElementToCheckInputInfo], NavOptions: Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.NavigationOptions, LinearTolerance: float, AngularTolerance: float) -> Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.GetUpToDateStatusResponse: ...

class GeometricconstraintsService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> GeometricconstraintsService: ...
    def GetContainersUpToDateStatus(self, Containers: list[Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.ContainerToCheckInputInfo], NavOptions: Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.NavigationOptions, LinearTolerance: float, AngularTolerance: float) -> Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.GetContainersUpToDateStatusResponse: ...
    def GetUpToDateStatus(self, Inputs: list[Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.ElementToCheckInputInfo], NavOptions: Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.NavigationOptions, LinearTolerance: float, AngularTolerance: float) -> Nxc0.Services.Internal.Strong.Tcincpd._2015_07.Geometricconstraints.GetUpToDateStatusResponse: ...

