import System

class AbstractSSOAppSession:
    METHOD: str
    APP_ID: str
    SESSION_HANDLE: str
    NEW_HANDLE: str
    SESSION_KEY: str
    SSO_SESSION_INFO: str
    SSO_LOGIN_STATUS: str
    APP_SESSION: str
    TARGET_APP_ID: str
    REQUESTED_APP_ID: str
    PSEUDO_APP_ID: str
    SSO_LOGIN_INPUT: str
    USER_ID: str
    USER_ATTRS: str
    USER_ATTRIBUTES: str
    TOKENS: str
    KEY_STATUS: str
    KEY_MESSAGE: str
    SUCCESS_STATUS: str
    FAILED_STATUS: str
    SSO_SESSION_KEY: str
    APP_USER_ID: str
    APP_URL: str

class AppSessionMethods(System.Enum, int):
    Authenticate: AppSessionMethods = ...
    AppLogout: AppSessionMethods = ...
    ResetSessionHandle: AppSessionMethods = ...
    GetSessionHandle: AppSessionMethods = ...
    GenerateTokens: AppSessionMethods = ...
    GenerateTrustedTokens: AppSessionMethods = ...
    GenerateAsyncTrustedTokens: AppSessionMethods = ...
    GenerateAsyncTrustedTokensWithTimeout: AppSessionMethods = ...
    Reauthenticate: AppSessionMethods = ...
    ValidateAppToken: AppSessionMethods = ...
    GetUserAttributes: AppSessionMethods = ...
    GetAppInfo: AppSessionMethods = ...
    GetSessionInfo: AppSessionMethods = ...
    MakeUniqueHandle: AppSessionMethods = ...
    GetState: AppSessionMethods = ...
    AuthenticateSigner: AppSessionMethods = ...

class AppSessionMethodsExtensions:
    @staticmethod
    def GetName(method: AppSessionMethods) -> str: ...

