import System
import Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup
import Teamcenter.Soa.Client

class BOMRollupRestBindingStub(BOMRollupService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CloneRollupTemplates(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateResponse: ...
    def CreateRollupCalculationTemplates(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.CreateRollupCalculationTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.CreateRollupCalculationTemplateResponse: ...
    def CreateRollupTemplates(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.CreateRollupTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateResponse: ...
    def GenerateRollupReports(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.CreateRollupReportInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupReportResponse: ...
    def GetRollupTemplateCalculations(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateCalculationResponse: ...
    def GetRollupTemplates(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.GetRollupTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateResponse: ...
    def ReviseRollupReports(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.ReviseRollupReportInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupReportResponse: ...

class BOMRollupService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> BOMRollupService: ...
    def CloneRollupTemplates(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateResponse: ...
    def CreateRollupCalculationTemplates(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.CreateRollupCalculationTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.CreateRollupCalculationTemplateResponse: ...
    def CreateRollupTemplates(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.CreateRollupTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateResponse: ...
    def GenerateRollupReports(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.CreateRollupReportInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupReportResponse: ...
    def GetRollupTemplateCalculations(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateCalculationResponse: ...
    def GetRollupTemplates(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.GetRollupTemplateInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupTemplateResponse: ...
    def ReviseRollupReports(self, Input: list[Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.ReviseRollupReportInput]) -> Teamcenter.Services.Internal.Strong.Reports._2007_06.BOMRollup.RollupReportResponse: ...

