import System
import Teamcenter.Services.Internal.Strong.Classification._2009_10.Classification
import Teamcenter.Services.Internal.Strong.Classification._2017_05.Classification
import Teamcenter.Services.Internal.Strong.Classification._2018_11.Classification
import Teamcenter.Services.Internal.Strong.Classification._2020_04.Classification
import Teamcenter.Services.Strong.Classification._2007_01.Classification
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model.Strong

class ClassificationRestBindingStub(ClassificationService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def GetClassificationHierarchies(self, Wsos: list[Teamcenter.Soa.Client.Model.Strong.WorkspaceObject]) -> Teamcenter.Services.Internal.Strong.Classification._2009_10.Classification.GetClassificationHierarchiesResponse: ...
    def GetClassificationProperties(self, Wsos: list[Teamcenter.Soa.Client.Model.Strong.WorkspaceObject]) -> Teamcenter.Services.Internal.Strong.Classification._2009_10.Classification.GetClassificationPropertiesResponse: ...
    def GetClassDefinitionsNX(self, ClassIDs: list[str]) -> Teamcenter.Services.Internal.Strong.Classification._2017_05.Classification.GetClassDefinitionsResponseNX: ...
    def SaveClassificationObjects(self, ClassificationObjects: list[Teamcenter.Services.Strong.Classification._2007_01.Classification.ClassificationObject]) -> Teamcenter.Services.Internal.Strong.Classification._2018_11.Classification.SaveClassificationObjectsResponse: ...
    def FindClassificationInfo(self, Request: list[Teamcenter.Services.Internal.Strong.Classification._2020_04.Classification.FindClassificationInfoRequest], Options: int) -> Teamcenter.Services.Internal.Strong.Classification._2020_04.Classification.FindClassificationInfoResponse: ...

class ClassificationService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ClassificationService: ...
    def GetClassificationHierarchies(self, Wsos: list[Teamcenter.Soa.Client.Model.Strong.WorkspaceObject]) -> Teamcenter.Services.Internal.Strong.Classification._2009_10.Classification.GetClassificationHierarchiesResponse: ...
    def GetClassificationProperties(self, Wsos: list[Teamcenter.Soa.Client.Model.Strong.WorkspaceObject]) -> Teamcenter.Services.Internal.Strong.Classification._2009_10.Classification.GetClassificationPropertiesResponse: ...
    def GetClassDefinitionsNX(self, ClassIDs: list[str]) -> Teamcenter.Services.Internal.Strong.Classification._2017_05.Classification.GetClassDefinitionsResponseNX: ...
    def SaveClassificationObjects(self, ClassificationObjects: list[Teamcenter.Services.Strong.Classification._2007_01.Classification.ClassificationObject]) -> Teamcenter.Services.Internal.Strong.Classification._2018_11.Classification.SaveClassificationObjectsResponse: ...
    def FindClassificationInfo(self, Request: list[Teamcenter.Services.Internal.Strong.Classification._2020_04.Classification.FindClassificationInfoRequest], Options: int) -> Teamcenter.Services.Internal.Strong.Classification._2020_04.Classification.FindClassificationInfoResponse: ...

