import System
import Teamcenter.Services.Internal.Strong.Query._2008_06.Finder
import Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery
import Teamcenter.Services.Internal.Strong.Query._2013_05.SavedQuery
import Teamcenter.Services.Internal.Strong.Query._2014_10.SavedQuery
import Teamcenter.Soa.Client

class FinderRestBindingStub(FinderService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def FindObjectsByClassAndAttributes(self, Input: Teamcenter.Services.Internal.Strong.Query._2008_06.Finder.FindObjectsInput) -> Teamcenter.Services.Internal.Strong.Query._2008_06.Finder.FindObjectsResponse: ...

class FinderService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> FinderService: ...
    def FindObjectsByClassAndAttributes(self, Input: Teamcenter.Services.Internal.Strong.Query._2008_06.Finder.FindObjectsInput) -> Teamcenter.Services.Internal.Strong.Query._2008_06.Finder.FindObjectsResponse: ...

class SavedQueryRestBindingStub(SavedQueryService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def DescribeSavedQueryDefinitions(self, RequestedQueries: list[Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery.DescribeSavedQueryDefinitionInput]) -> Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery.DescribeSavedQueryDefinitionsResponse: ...
    def DescribeSavedQueryDefinitions2(self, RequestedQueries: list[Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery.DescribeSavedQueryDefinitionInput]) -> Teamcenter.Services.Internal.Strong.Query._2013_05.SavedQuery.DescribeSavedQueryDefinitionsResponse2: ...
    def DescribeSavedQueryDefinitions3(self, RequestedQueries: list[Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery.DescribeSavedQueryDefinitionInput]) -> Teamcenter.Services.Internal.Strong.Query._2014_10.SavedQuery.DescribeSavedQueryDefnResponse3: ...

class SavedQueryService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> SavedQueryService: ...
    def DescribeSavedQueryDefinitions(self, RequestedQueries: list[Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery.DescribeSavedQueryDefinitionInput]) -> Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery.DescribeSavedQueryDefinitionsResponse: ...
    def DescribeSavedQueryDefinitions2(self, RequestedQueries: list[Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery.DescribeSavedQueryDefinitionInput]) -> Teamcenter.Services.Internal.Strong.Query._2013_05.SavedQuery.DescribeSavedQueryDefinitionsResponse2: ...
    def DescribeSavedQueryDefinitions3(self, RequestedQueries: list[Teamcenter.Services.Internal.Strong.Query._2012_02.SavedQuery.DescribeSavedQueryDefinitionInput]) -> Teamcenter.Services.Internal.Strong.Query._2014_10.SavedQuery.DescribeSavedQueryDefnResponse3: ...

