import System
import Teamcenter.Services.Internal.Strong.Contmgmtbase._2021_06.ContentManagement
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class ContentManagementRestBindingStub(ContentManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ImportTranslation(self, FileTickets: list[str]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetTopicTypesAndRelatedTopics(self, TopicType: Teamcenter.Soa.Client.Model.ModelObject, TopicTypeNameFilter: str, IncludeReferencedTopics: bool) -> Teamcenter.Services.Internal.Strong.Contmgmtbase._2021_06.ContentManagement.TopicTypesOutput: ...

class ContentManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ContentManagementService: ...
    def ImportTranslation(self, FileTickets: list[str]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetTopicTypesAndRelatedTopics(self, TopicType: Teamcenter.Soa.Client.Model.ModelObject, TopicTypeNameFilter: str, IncludeReferencedTopics: bool) -> Teamcenter.Services.Internal.Strong.Contmgmtbase._2021_06.ContentManagement.TopicTypesOutput: ...

