import Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification
import Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification
import Cla0.Services.Internal.Strong.Classificationcommon._2021_12.Classification
import Cla0.Services.Internal.Strong.Classificationcommon._2023_06.Classification
import System
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class ClassificationRestBindingStub(ClassificationService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def DeleteClassificationObjects(self, Context: Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.Context, ObjectIDs: list[str]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetClassDescriptor(self, NodeIDs: list[str], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.GetClassDescriptorResponse: ...
    def GetClassificationObjects(self, Context: Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.Context, ObjectIDs: list[str]) -> Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.GetClassificationObjectsResponse: ...
    def SaveClassificationObjects(self, Context: Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.Context, ClassificationObjects: list[Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.ClassificationObject]) -> Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.SaveClassificationObjectsResponse: ...
    def FindValues(self, FindValueInputs: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.FindValueInput]) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.FindValuesResponse: ...
    def GetGraphicsTemplateInfo(self, ClassificationObjects: list[str], ClassificationClasses: list[str]) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.GetGraphicsTemplateInfoResponse: ...
    def SaveGraphicsMember(self, RequestObjects: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SaveGraphicsMemberRequest]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SearchClassDescriptor(self, SearchCriteria: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchCriteria], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchClassDescriptorResponse: ...
    def SearchClassificationObjects(self, SearchCriteria: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchIcoCriteria], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchIcoResponse: ...
    def ListClassificationDataFiles(self, FileTicket: str) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_12.Classification.ClassificationDataFilesResponse: ...
    def SearchClassDescriptor2(self, SearchCriteria: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchCriteria], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_12.Classification.SearchClassDescriptorResponse2: ...
    def SearchClassDescriptor3(self, SearchCriteria: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchCriteria], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2023_06.Classification.SearchClassDescriptorResponse3: ...

class ClassificationService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> ClassificationService: ...
    def DeleteClassificationObjects(self, Context: Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.Context, ObjectIDs: list[str]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def GetClassDescriptor(self, NodeIDs: list[str], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.GetClassDescriptorResponse: ...
    def GetClassificationObjects(self, Context: Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.Context, ObjectIDs: list[str]) -> Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.GetClassificationObjectsResponse: ...
    def SaveClassificationObjects(self, Context: Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.Context, ClassificationObjects: list[Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.ClassificationObject]) -> Cla0.Services.Internal.Strong.Classificationcommon._2020_12.Classification.SaveClassificationObjectsResponse: ...
    def FindValues(self, FindValueInputs: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.FindValueInput]) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.FindValuesResponse: ...
    def GetGraphicsTemplateInfo(self, ClassificationObjects: list[str], ClassificationClasses: list[str]) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.GetGraphicsTemplateInfoResponse: ...
    def SaveGraphicsMember(self, RequestObjects: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SaveGraphicsMemberRequest]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SearchClassDescriptor(self, SearchCriteria: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchCriteria], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchClassDescriptorResponse: ...
    def SearchClassificationObjects(self, SearchCriteria: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchIcoCriteria], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchIcoResponse: ...
    def ListClassificationDataFiles(self, FileTicket: str) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_12.Classification.ClassificationDataFilesResponse: ...
    def SearchClassDescriptor2(self, SearchCriteria: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchCriteria], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2021_12.Classification.SearchClassDescriptorResponse2: ...
    def SearchClassDescriptor3(self, SearchCriteria: list[Cla0.Services.Internal.Strong.Classificationcommon._2021_06.Classification.SearchCriteria], Options: int) -> Cla0.Services.Internal.Strong.Classificationcommon._2023_06.Classification.SearchClassDescriptorResponse3: ...

