import System
import Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model

class BudgetRestBindingStub(BudgetService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def EditBudget(self, EditBudgetInfo: list[Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.EditBudgetInfo]) -> Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.EditBudgetResponse: ...
    def GetBudgetData(self, InputInfo: list[Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.BudgetDataInfo]) -> Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.BudgetDataResponse: ...
    def RemoveBudget(self, RemoveBudgetInfo: list[Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.RemoveBudgetInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class BudgetService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> BudgetService: ...
    def EditBudget(self, EditBudgetInfo: list[Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.EditBudgetInfo]) -> Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.EditBudgetResponse: ...
    def GetBudgetData(self, InputInfo: list[Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.BudgetDataInfo]) -> Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.BudgetDataResponse: ...
    def RemoveBudget(self, RemoveBudgetInfo: list[Teamcenter.Services.Internal.Strong.Systemsengineering._2011_06.Budget.RemoveBudgetInfo]) -> Teamcenter.Soa.Client.Model.ServiceData: ...

