import System.Collections
import System.Xml
import System.Xml.Schema

class NameBooleanValue:
    def __init__(self, ) -> None: ...
    Name: str
    Value: bool
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Value(self) -> bool: ...
    def set_Value(self, value: bool) -> None: ...
    def getValue(self) -> bool: ...
    def setValue(self, val: bool) -> None: ...

class NameIntegerValue:
    def __init__(self, ) -> None: ...
    Name: str
    Value: int
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Value(self) -> int: ...
    def set_Value(self, value: int) -> None: ...
    def getValue(self) -> int: ...
    def setValue(self, val: int) -> None: ...

class NameStringValue:
    def __init__(self, ) -> None: ...
    Name: str
    Value: str
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Value(self) -> str: ...
    def set_Value(self, value: str) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, val: str) -> None: ...

class RequestBody:
    def __init__(self, ) -> None: ...
    Bodystring: str
    def get_Bodystring(self) -> str: ...
    def set_Bodystring(self, value: str) -> None: ...
    def getBodystring(self) -> str: ...
    def setBodystring(self, val: str) -> None: ...
    def GetSchema(self) -> System.Xml.Schema.XmlSchema: ...
    def ReadXml(self, reader: System.Xml.XmlReader) -> None: ...
    def WriteXml(self, writer: System.Xml.XmlWriter) -> None: ...

class RequestEnvelope:
    def __init__(self, ) -> None: ...
    Header: RequestHeader
    IsHeaderSet: bool
    Body: RequestBody
    def get_Header(self) -> RequestHeader: ...
    def set_Header(self, value: RequestHeader) -> None: ...
    def getHeader(self) -> RequestHeader: ...
    def setHeader(self, val: RequestHeader) -> None: ...
    def get_IsHeaderSet(self) -> bool: ...
    def get_Body(self) -> RequestBody: ...
    def set_Body(self, value: RequestBody) -> None: ...
    def getBody(self) -> RequestBody: ...
    def setBody(self, val: RequestBody) -> None: ...

class RequestHeader:
    def __init__(self, ) -> None: ...
    StringState: list[NameStringValue]
    IntegerState: list[NameIntegerValue]
    BooleanState: list[NameBooleanValue]
    def get_StringState(self) -> list[NameStringValue]: ...
    def set_StringState(self, value: list[NameStringValue]) -> None: ...
    def getStringState(self) -> System.Collections.ArrayList: ...
    def setStringState(self, val: System.Collections.ArrayList) -> None: ...
    def get_IntegerState(self) -> list[NameIntegerValue]: ...
    def set_IntegerState(self, value: list[NameIntegerValue]) -> None: ...
    def getIntegerState(self) -> System.Collections.ArrayList: ...
    def setIntegerState(self, val: System.Collections.ArrayList) -> None: ...
    def get_BooleanState(self) -> list[NameBooleanValue]: ...
    def set_BooleanState(self, value: list[NameBooleanValue]) -> None: ...
    def getBooleanState(self) -> System.Collections.ArrayList: ...
    def setBooleanState(self, val: System.Collections.ArrayList) -> None: ...

