import Pdm0.Services.Internal.Strong.Plantdatamgmt._2018_06.PdmCore
import Pdm0.Services.Internal.Strong.Plantdatamgmt._2019_06.PdmCore
import Pdm0.Services.Internal.Strong.Plantdatamgmt._2020_12.PdmCore
import Pdm0.Services.Internal.Strong.Plantdatamgmt._2022_06.PdmCore
import System
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong

class PdmCoreRestBindingStub(PdmCoreService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def FindCondlMdlElementsAndRltdWSObjs(self, Model: Teamcenter.Soa.Client.Model.Strong.Mdl0ApplicationModel, ConfigurationContext: Teamcenter.Soa.Client.Model.Strong.ConfigurationContext) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2018_06.PdmCore.FindCondElementsAndRltdObjsResponse: ...
    def SetReleaseStatusInBulk(self, WorkspaceObjs: list[Teamcenter.Soa.Client.Model.Strong.WorkspaceObject], ReleaseStatus: str, ReleaseDate: System.DateTime, SkipIfAlreadyHasStatus: bool, ReleaseStatusListToSkip: list[str], RevisionRuleName: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def IsMilestoneActivityInProgress(self, Plants: list[Teamcenter.Soa.Client.Model.Strong.Mdl0ApplicationModel]) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2019_06.PdmCore.IsMilestoneActivityInProgressRes: ...
    def CreateChangesetAndUpdateIModelData(self, Pdm0IModel: Teamcenter.Soa.Client.Model.Strong.Pdm0IModel, Pdm0ParentChangeSetId: str, ChangesetName: str, ChangesetFileName: str, Pdm0Id: str) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2020_12.PdmCore.ChangesetResponse: ...
    def GetIModelData(self, IModelID: str, ContextID: str) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2020_12.PdmCore.IModelData: ...
    def GetIncrementalUpdates(self, RootObject: Teamcenter.Soa.Client.Model.Strong.WorkspaceObject, ExternalIds: list[str]) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2020_12.PdmCore.IncrementalUpdateResponse: ...
    def IsMilestoneActivityInProgress2(self, CapitalAssetRoots: list[Teamcenter.Soa.Client.Model.Strong.Pdm0CARoot]) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2022_06.PdmCore.IsMilestoneActivityInProgressRes2: ...

class PdmCoreService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> PdmCoreService: ...
    def FindCondlMdlElementsAndRltdWSObjs(self, Model: Teamcenter.Soa.Client.Model.Strong.Mdl0ApplicationModel, ConfigurationContext: Teamcenter.Soa.Client.Model.Strong.ConfigurationContext) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2018_06.PdmCore.FindCondElementsAndRltdObjsResponse: ...
    def SetReleaseStatusInBulk(self, WorkspaceObjs: list[Teamcenter.Soa.Client.Model.Strong.WorkspaceObject], ReleaseStatus: str, ReleaseDate: System.DateTime, SkipIfAlreadyHasStatus: bool, ReleaseStatusListToSkip: list[str], RevisionRuleName: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def IsMilestoneActivityInProgress(self, Plants: list[Teamcenter.Soa.Client.Model.Strong.Mdl0ApplicationModel]) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2019_06.PdmCore.IsMilestoneActivityInProgressRes: ...
    def CreateChangesetAndUpdateIModelData(self, Pdm0IModel: Teamcenter.Soa.Client.Model.Strong.Pdm0IModel, Pdm0ParentChangeSetId: str, ChangesetName: str, ChangesetFileName: str, Pdm0Id: str) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2020_12.PdmCore.ChangesetResponse: ...
    def GetIModelData(self, IModelID: str, ContextID: str) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2020_12.PdmCore.IModelData: ...
    def GetIncrementalUpdates(self, RootObject: Teamcenter.Soa.Client.Model.Strong.WorkspaceObject, ExternalIds: list[str]) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2020_12.PdmCore.IncrementalUpdateResponse: ...
    def IsMilestoneActivityInProgress2(self, CapitalAssetRoots: list[Teamcenter.Soa.Client.Model.Strong.Pdm0CARoot]) -> Pdm0.Services.Internal.Strong.Plantdatamgmt._2022_06.PdmCore.IsMilestoneActivityInProgressRes2: ...

