import System
import typing

class UnreadMessages:
    def __init__(self, ) -> None: ...
    Messages: list[str]

class MessageManagement:
    def __init__(self , *args: typing.Any) -> None: ...
    def GetUnreadMessages(self) -> UnreadMessages: ...
    def InitializeAsynchMessaging(self) -> str: ...

