import Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement
import Cpd0.Services.Internal.Strong.Cpdcore._2017_11.DataManagement
import System
import Teamcenter.Soa.Client

class DataManagementRestBindingStub(DataManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ProductContextSearch(self, ProductContextSearchInfos: list[Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement.ProductContextSearchInfo]) -> Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement.ProductContextResponse: ...
    def GenerateDesignContext(self, DesignContextInfos: list[Cpd0.Services.Internal.Strong.Cpdcore._2017_11.DataManagement.GenerateDesignContextInfo]) -> Cpd0.Services.Internal.Strong.Cpdcore._2017_11.DataManagement.GenerateDesignContextResponse: ...

class DataManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> DataManagementService: ...
    def ProductContextSearch(self, ProductContextSearchInfos: list[Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement.ProductContextSearchInfo]) -> Cpd0.Services.Internal.Strong.Cpdcore._2017_05.DataManagement.ProductContextResponse: ...
    def GenerateDesignContext(self, DesignContextInfos: list[Cpd0.Services.Internal.Strong.Cpdcore._2017_11.DataManagement.GenerateDesignContextInfo]) -> Cpd0.Services.Internal.Strong.Cpdcore._2017_11.DataManagement.GenerateDesignContextResponse: ...

