import System
import Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt
import Teamcenter.Soa.Client

class AsBuiltRestBindingStub(AsBuiltService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def CreateMROBOMWindows(self, Info: list[Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.CreateMROBOMWindowsInfo]) -> Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.CreateMROBOMWindowsResponse: ...
    def GetAllOpenUsages(self, GetAllOpenUsageInput: list[Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.GetAllOpenUsageInput]) -> Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.GetAllOpenUsageResponse: ...
    def MroBomCompare(self, Info: list[Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.MROBomCompareInfo]) -> Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.MROBomCompareResponse: ...

class AsBuiltService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> AsBuiltService: ...
    def CreateMROBOMWindows(self, Info: list[Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.CreateMROBOMWindowsInfo]) -> Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.CreateMROBOMWindowsResponse: ...
    def GetAllOpenUsages(self, GetAllOpenUsageInput: list[Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.GetAllOpenUsageInput]) -> Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.GetAllOpenUsageResponse: ...
    def MroBomCompare(self, Info: list[Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.MROBomCompareInfo]) -> Teamcenter.Services.Internal.Strong.Asbuilt._2008_06.AsBuilt.MROBomCompareResponse: ...

