import System.Collections
import typing

class TcSSOCookieManager:
    def __init__(self , *args: typing.Any) -> None: ...
    def processFormChallenge(self, destUrl: str, tcSSOLoginUrl: str, requestHeaders: System.Collections.IDictionary, replyHeaders: System.Collections.IDictionary) -> System.Collections.IList: ...
    def setCookies(self, destUrl: str, newCookies: System.Collections.IList) -> None: ...
    def getCookies(self, destUrl: str) -> System.Collections.IList: ...

class TcSSOCookieManagerFactory:
    def __init__(self, ) -> None: ...
    @staticmethod
    def getTcSSOCookieManager() -> TcSSOCookieManager: ...

