import Teamcenter.Soa.Common
import typing

class RegisterIndex:
    def __init__(self, ) -> None: ...
    RegistryIndex: int

class SetPolicyResponse:
    def __init__(self, ) -> None: ...
    PolicyId: str
    Policy: Teamcenter.Soa.Common.ObjectPropertyPolicy

class Session:
    def __init__(self , *args: typing.Any) -> None: ...
    def RegisterState(self, Level: str) -> RegisterIndex: ...
    def SetObjectPropertyPolicy(self, PolicyName: str, UseRefCounting: bool) -> SetPolicyResponse: ...
    def UnregisterState(self, Index: int) -> bool: ...

