import System
import Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement
import Teamcenter.Services.Internal.Strong.Cae._2013_05.StructureManagement
import Teamcenter.Services.Internal.Strong.Cae._2014_06.StructureManagement
import Teamcenter.Soa.Client
import Teamcenter.Soa.Client.Model
import Teamcenter.Soa.Client.Model.Strong

class SimulationProcessManagementRestBindingStub(SimulationProcessManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def NotifyUser(self, Message: str, Users: str, Groups: str) -> bool: ...
    def ImportSimulationObjects2(self, ProcessHierarchy: str, WorkingDirectory: str, ItemID: str, ObjectUID: str, RevisionID: str, XmlFileName: str, ItemCreationSetting: str, DatasetCreationSetting: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class SimulationProcessManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> SimulationProcessManagementService: ...
    def NotifyUser(self, Message: str, Users: str, Groups: str) -> bool: ...
    def ImportSimulationObjects2(self, ProcessHierarchy: str, WorkingDirectory: str, ItemID: str, ObjectUID: str, RevisionID: str, XmlFileName: str, ItemCreationSetting: str, DatasetCreationSetting: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...

class StructureManagementRestBindingStub(StructureManagementService):
    def __init__(self, connection: Teamcenter.Soa.Client.Connection) -> None: ...
    def ExecuteDatamap(self, RootBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine) -> Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement.ExecuteRuleResponse: ...
    def CreateNewModelByDM(self, ProductBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelParentBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelExistingBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, Domain: str) -> Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement.ExecuteRuleResponse: ...
    def ExecuteMarkUpToDate(self, InputItemRevList: list[Teamcenter.Soa.Client.Model.Strong.CAEItemRevision]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def UpdateModelAttsByDM(self, ProductBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelParentBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelRevTag: Teamcenter.Soa.Client.Model.Strong.ItemRevision, ModelExistingBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, Domain: str, BomlineAttribsOnly: bool, DoRevise: bool) -> Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement.ExecuteRuleResponse: ...
    def GetCAEPropertyComparisonDetails(self, TargetBomline: Teamcenter.Soa.Client.Model.Strong.BOMLine) -> Teamcenter.Services.Internal.Strong.Cae._2013_05.StructureManagement.GetCAEPropertyComparisonDetailsResponse: ...
    def PropagateCAEModelAttributes(self) -> bool: ...
    def LoadSimulationDataMonitor(self, Rootbomline: Teamcenter.Soa.Client.Model.Strong.BOMLine) -> Teamcenter.Services.Internal.Strong.Cae._2014_06.StructureManagement.MonitorResponse: ...
    def RefreshSimulationDataMonitor(self, Itemrevisions: list[Teamcenter.Soa.Client.Model.Strong.ItemRevision]) -> Teamcenter.Services.Internal.Strong.Cae._2014_06.StructureManagement.MonitorResponse: ...

class StructureManagementService:
    @staticmethod
    def getService(connection: Teamcenter.Soa.Client.Connection) -> StructureManagementService: ...
    def ExecuteDatamap(self, RootBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine) -> Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement.ExecuteRuleResponse: ...
    def CreateNewModelByDM(self, ProductBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelParentBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelExistingBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, Domain: str) -> Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement.ExecuteRuleResponse: ...
    def ExecuteMarkUpToDate(self, InputItemRevList: list[Teamcenter.Soa.Client.Model.Strong.CAEItemRevision]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def UpdateModelAttsByDM(self, ProductBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelParentBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, ModelRevTag: Teamcenter.Soa.Client.Model.Strong.ItemRevision, ModelExistingBOMLine: Teamcenter.Soa.Client.Model.Strong.BOMLine, Domain: str, BomlineAttribsOnly: bool, DoRevise: bool) -> Teamcenter.Services.Internal.Strong.Cae._2011_06.StructureManagement.ExecuteRuleResponse: ...
    def GetCAEPropertyComparisonDetails(self, TargetBomline: Teamcenter.Soa.Client.Model.Strong.BOMLine) -> Teamcenter.Services.Internal.Strong.Cae._2013_05.StructureManagement.GetCAEPropertyComparisonDetailsResponse: ...
    def PropagateCAEModelAttributes(self) -> bool: ...
    def LoadSimulationDataMonitor(self, Rootbomline: Teamcenter.Soa.Client.Model.Strong.BOMLine) -> Teamcenter.Services.Internal.Strong.Cae._2014_06.StructureManagement.MonitorResponse: ...
    def RefreshSimulationDataMonitor(self, Itemrevisions: list[Teamcenter.Soa.Client.Model.Strong.ItemRevision]) -> Teamcenter.Services.Internal.Strong.Cae._2014_06.StructureManagement.MonitorResponse: ...

