import Teamcenter.Soa.Client.Model
import typing

class MeasurementDataLoad:
    def __init__(self , *args: typing.Any) -> None: ...
    def PopulateDBLocatorTable(self, PlantId: str, DbKey: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def PopulateLinkLocatorTable(self, DbKey: str, DbName: str, TargetDbType: str, ServerName: str, UserName: str, Password: str) -> Teamcenter.Soa.Client.Model.ServiceData: ...

