import System
import System.Collections

class Attrib:
    def __init__(self, ) -> None: ...
    MaxLength: int
    IsMaxLengthSet: bool
    Name: str
    Uid: str
    Descriptors: int
    Type: int
    RefClassUid: str
    IsRefClassUidSet: bool
    UiName: str
    IsUiNameSet: bool
    def get_MaxLength(self) -> int: ...
    def set_MaxLength(self, value: int) -> None: ...
    def getMaxLength(self) -> int: ...
    def setMaxLength(self, val: int) -> None: ...
    def get_IsMaxLengthSet(self) -> bool: ...
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...
    def get_Descriptors(self) -> int: ...
    def set_Descriptors(self, value: int) -> None: ...
    def getDescriptors(self) -> int: ...
    def setDescriptors(self, val: int) -> None: ...
    def get_Type(self) -> int: ...
    def set_Type(self, value: int) -> None: ...
    def getType(self) -> int: ...
    def setType(self, val: int) -> None: ...
    def get_RefClassUid(self) -> str: ...
    def set_RefClassUid(self, value: str) -> None: ...
    def getRefClassUid(self) -> str: ...
    def setRefClassUid(self, val: str) -> None: ...
    def get_IsRefClassUidSet(self) -> bool: ...
    def get_UiName(self) -> str: ...
    def set_UiName(self, value: str) -> None: ...
    def getUiName(self) -> str: ...
    def setUiName(self, val: str) -> None: ...
    def get_IsUiNameSet(self) -> bool: ...

class CompoundProperty:
    def __init__(self, ) -> None: ...
    Key: str
    Value: list[CreateInput]
    def get_Key(self) -> str: ...
    def set_Key(self, value: str) -> None: ...
    def getKey(self) -> str: ...
    def setKey(self, val: str) -> None: ...
    def get_Value(self) -> list[CreateInput]: ...
    def set_Value(self, value: list[CreateInput]) -> None: ...
    def getValue(self) -> System.Collections.ArrayList: ...
    def setValue(self, val: System.Collections.ArrayList) -> None: ...

class CreateInput:
    def __init__(self, ) -> None: ...
    BoName: str
    PropertyNameValues: list[PropertyNameValues]
    CompoundCreateInput: list[CompoundProperty]
    def get_BoName(self) -> str: ...
    def set_BoName(self, value: str) -> None: ...
    def getBoName(self) -> str: ...
    def setBoName(self, val: str) -> None: ...
    def get_PropertyNameValues(self) -> list[PropertyNameValues]: ...
    def set_PropertyNameValues(self, value: list[PropertyNameValues]) -> None: ...
    def getPropertyNameValues(self) -> System.Collections.ArrayList: ...
    def setPropertyNameValues(self, val: System.Collections.ArrayList) -> None: ...
    def get_CompoundCreateInput(self) -> list[CompoundProperty]: ...
    def set_CompoundCreateInput(self, value: list[CompoundProperty]) -> None: ...
    def getCompoundCreateInput(self) -> System.Collections.ArrayList: ...
    def setCompoundCreateInput(self, val: System.Collections.ArrayList) -> None: ...

class DisplayProperty:
    def __init__(self, ) -> None: ...
    Name: str
    UiValues: list[str]
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_UiValues(self) -> list[str]: ...
    def set_UiValues(self, value: list[str]) -> None: ...
    def getUiValues(self) -> System.Collections.ArrayList: ...
    def setUiValues(self, val: System.Collections.ArrayList) -> None: ...

class ErrorStack:
    def __init__(self, ) -> None: ...
    ClientId: str
    IsClientIdSet: bool
    Uid: str
    IsUidSet: bool
    ClientIndex: int
    IsClientIndexSet: bool
    ErrorValues: list[ErrorValue]
    def get_ClientId(self) -> str: ...
    def set_ClientId(self, value: str) -> None: ...
    def getClientId(self) -> str: ...
    def setClientId(self, val: str) -> None: ...
    def get_IsClientIdSet(self) -> bool: ...
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...
    def get_IsUidSet(self) -> bool: ...
    def get_ClientIndex(self) -> int: ...
    def set_ClientIndex(self, value: int) -> None: ...
    def getClientIndex(self) -> int: ...
    def setClientIndex(self, val: int) -> None: ...
    def get_IsClientIndexSet(self) -> bool: ...
    def get_ErrorValues(self) -> list[ErrorValue]: ...
    def set_ErrorValues(self, value: list[ErrorValue]) -> None: ...
    def getErrorValues(self) -> System.Collections.ArrayList: ...
    def setErrorValues(self, val: System.Collections.ArrayList) -> None: ...

class ErrorValue:
    def __init__(self, ) -> None: ...
    Message: str
    IsMessageSet: bool
    Code: int
    Level: int
    def get_Message(self) -> str: ...
    def set_Message(self, value: str) -> None: ...
    def getMessage(self) -> str: ...
    def setMessage(self, val: str) -> None: ...
    def get_IsMessageSet(self) -> bool: ...
    def get_Code(self) -> int: ...
    def set_Code(self, value: int) -> None: ...
    def getCode(self) -> int: ...
    def setCode(self, val: int) -> None: ...
    def get_Level(self) -> int: ...
    def set_Level(self, value: int) -> None: ...
    def getLevel(self) -> int: ...
    def setLevel(self, val: int) -> None: ...

class ModelClass:
    def __init__(self, ) -> None: ...
    ParentClassName: str
    IsParentClassNameSet: bool
    Name: str
    Attributes: list[Attrib]
    def get_ParentClassName(self) -> str: ...
    def set_ParentClassName(self, value: str) -> None: ...
    def getParentClassName(self) -> str: ...
    def setParentClassName(self, val: str) -> None: ...
    def get_IsParentClassNameSet(self) -> bool: ...
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Attributes(self) -> list[Attrib]: ...
    def set_Attributes(self, value: list[Attrib]) -> None: ...
    def getAttributes(self) -> System.Collections.ArrayList: ...
    def setAttributes(self, val: System.Collections.ArrayList) -> None: ...

class ModelObject:
    def __init__(self, ) -> None: ...
    ObjectID: str
    IsObjectIDSet: bool
    ClassUid: str
    IsClassUidSet: bool
    CParamID: str
    IsCParamIDSet: bool
    IsObsolete: bool
    IsIsObsoleteSet: bool
    Jbt_addition: str
    IsJbt_additionSet: bool
    Uid: str
    ClassName: str
    IsClassNameSet: bool
    Type: str
    IsTypeSet: bool
    UpdateDesc: bool
    IsUpdateDescSet: bool
    IsHistorical: bool
    IsIsHistoricalSet: bool
    Properties: list[Property]
    Uiproperties: list[DisplayProperty]
    Props: list[XJProperty]
    def get_ObjectID(self) -> str: ...
    def set_ObjectID(self, value: str) -> None: ...
    def getObjectID(self) -> str: ...
    def setObjectID(self, val: str) -> None: ...
    def get_IsObjectIDSet(self) -> bool: ...
    def get_ClassUid(self) -> str: ...
    def set_ClassUid(self, value: str) -> None: ...
    def getClassUid(self) -> str: ...
    def setClassUid(self, val: str) -> None: ...
    def get_IsClassUidSet(self) -> bool: ...
    def get_CParamID(self) -> str: ...
    def set_CParamID(self, value: str) -> None: ...
    def getCParamID(self) -> str: ...
    def setCParamID(self, val: str) -> None: ...
    def get_IsCParamIDSet(self) -> bool: ...
    def get_IsObsolete(self) -> bool: ...
    def set_IsObsolete(self, value: bool) -> None: ...
    def getIsObsolete(self) -> bool: ...
    def setIsObsolete(self, val: bool) -> None: ...
    def get_IsIsObsoleteSet(self) -> bool: ...
    def get_Jbt_addition(self) -> str: ...
    def set_Jbt_addition(self, value: str) -> None: ...
    def getJbt_addition(self) -> str: ...
    def setJbt_addition(self, val: str) -> None: ...
    def get_IsJbt_additionSet(self) -> bool: ...
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...
    def get_ClassName(self) -> str: ...
    def set_ClassName(self, value: str) -> None: ...
    def getClassName(self) -> str: ...
    def setClassName(self, val: str) -> None: ...
    def get_IsClassNameSet(self) -> bool: ...
    def get_Type(self) -> str: ...
    def set_Type(self, value: str) -> None: ...
    def getType(self) -> str: ...
    def setType(self, val: str) -> None: ...
    def get_IsTypeSet(self) -> bool: ...
    def get_UpdateDesc(self) -> bool: ...
    def set_UpdateDesc(self, value: bool) -> None: ...
    def getUpdateDesc(self) -> bool: ...
    def setUpdateDesc(self, val: bool) -> None: ...
    def get_IsUpdateDescSet(self) -> bool: ...
    def get_IsHistorical(self) -> bool: ...
    def set_IsHistorical(self, value: bool) -> None: ...
    def getIsHistorical(self) -> bool: ...
    def setIsHistorical(self, val: bool) -> None: ...
    def get_IsIsHistoricalSet(self) -> bool: ...
    def get_Properties(self) -> list[Property]: ...
    def set_Properties(self, value: list[Property]) -> None: ...
    def getProperties(self) -> System.Collections.ArrayList: ...
    def setProperties(self, val: System.Collections.ArrayList) -> None: ...
    def get_Uiproperties(self) -> list[DisplayProperty]: ...
    def set_Uiproperties(self, value: list[DisplayProperty]) -> None: ...
    def getUiproperties(self) -> System.Collections.ArrayList: ...
    def setUiproperties(self, val: System.Collections.ArrayList) -> None: ...
    def get_Props(self) -> list[XJProperty]: ...
    def set_Props(self, value: list[XJProperty]) -> None: ...
    def getProps(self) -> System.Collections.ArrayList: ...
    def setProps(self, val: System.Collections.ArrayList) -> None: ...

class ModelSchema:
    def __init__(self, ) -> None: ...
    Types: list[ModelType]
    Classes: list[ModelClass]
    def get_Types(self) -> list[ModelType]: ...
    def set_Types(self, value: list[ModelType]) -> None: ...
    def getTypes(self) -> System.Collections.ArrayList: ...
    def setTypes(self, val: System.Collections.ArrayList) -> None: ...
    def get_Classes(self) -> list[ModelClass]: ...
    def set_Classes(self, value: list[ModelClass]) -> None: ...
    def getClasses(self) -> System.Collections.ArrayList: ...
    def setClasses(self, val: System.Collections.ArrayList) -> None: ...

class ModelType:
    def __init__(self, ) -> None: ...
    TransientType: bool
    ParentTypeName: str
    IsParentTypeNameSet: bool
    ExternalObject: bool
    UifName: str
    IsUifNameSet: bool
    Name: str
    Uid: str
    ClassName: str
    TypeUid: str
    PropDescriptor: list[PropDescriptor]
    def get_TransientType(self) -> bool: ...
    def set_TransientType(self, value: bool) -> None: ...
    def getTransientType(self) -> bool: ...
    def setTransientType(self, val: bool) -> None: ...
    def get_ParentTypeName(self) -> str: ...
    def set_ParentTypeName(self, value: str) -> None: ...
    def getParentTypeName(self) -> str: ...
    def setParentTypeName(self, val: str) -> None: ...
    def get_IsParentTypeNameSet(self) -> bool: ...
    def get_ExternalObject(self) -> bool: ...
    def set_ExternalObject(self, value: bool) -> None: ...
    def getExternalObject(self) -> bool: ...
    def setExternalObject(self, val: bool) -> None: ...
    def get_UifName(self) -> str: ...
    def set_UifName(self, value: str) -> None: ...
    def getUifName(self) -> str: ...
    def setUifName(self, val: str) -> None: ...
    def get_IsUifNameSet(self) -> bool: ...
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...
    def get_ClassName(self) -> str: ...
    def set_ClassName(self, value: str) -> None: ...
    def getClassName(self) -> str: ...
    def setClassName(self, val: str) -> None: ...
    def get_TypeUid(self) -> str: ...
    def set_TypeUid(self, value: str) -> None: ...
    def getTypeUid(self) -> str: ...
    def setTypeUid(self, val: str) -> None: ...
    def get_PropDescriptor(self) -> list[PropDescriptor]: ...
    def set_PropDescriptor(self, value: list[PropDescriptor]) -> None: ...
    def getPropDescriptor(self) -> System.Collections.ArrayList: ...
    def setPropDescriptor(self, val: System.Collections.ArrayList) -> None: ...

class Modifiers:
    def __init__(self, ) -> None: ...
    Value: str
    Name: str
    def get_Value(self) -> str: ...
    def set_Value(self, value: str) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, val: str) -> None: ...
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...

class ObjectMap:
    def __init__(self, ) -> None: ...
    Uid: str
    Bo: ModelObject
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...
    def get_Bo(self) -> ModelObject: ...
    def set_Bo(self, value: ModelObject) -> None: ...
    def getBo(self) -> ModelObject: ...
    def setBo(self, val: ModelObject) -> None: ...

class ObjectPropertyPolicy:
    def __init__(self, ) -> None: ...
    UseRefCount: bool
    IsUseRefCountSet: bool
    Modifiers: list[Modifiers]
    Types: list[PolicyType]
    def get_UseRefCount(self) -> bool: ...
    def set_UseRefCount(self, value: bool) -> None: ...
    def getUseRefCount(self) -> bool: ...
    def setUseRefCount(self, val: bool) -> None: ...
    def get_IsUseRefCountSet(self) -> bool: ...
    def get_Modifiers(self) -> list[Modifiers]: ...
    def set_Modifiers(self, value: list[Modifiers]) -> None: ...
    def getModifiers(self) -> System.Collections.ArrayList: ...
    def setModifiers(self, val: System.Collections.ArrayList) -> None: ...
    def get_Types(self) -> list[PolicyType]: ...
    def set_Types(self, value: list[PolicyType]) -> None: ...
    def getTypes(self) -> System.Collections.ArrayList: ...
    def setTypes(self, val: System.Collections.ArrayList) -> None: ...

class PartialErrors:
    def __init__(self, ) -> None: ...
    Errors: list[ErrorStack]
    def get_Errors(self) -> list[ErrorStack]: ...
    def set_Errors(self, value: list[ErrorStack]) -> None: ...
    def getErrors(self) -> System.Collections.ArrayList: ...
    def setErrors(self, val: System.Collections.ArrayList) -> None: ...

class PolicyProperty:
    def __init__(self, ) -> None: ...
    Name: str
    Modifiers: list[Modifiers]
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Modifiers(self) -> list[Modifiers]: ...
    def set_Modifiers(self, value: list[Modifiers]) -> None: ...
    def getModifiers(self) -> System.Collections.ArrayList: ...
    def setModifiers(self, val: System.Collections.ArrayList) -> None: ...

class PolicyType:
    def __init__(self, ) -> None: ...
    Name: str
    Modifiers: list[Modifiers]
    Properties: list[PolicyProperty]
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Modifiers(self) -> list[Modifiers]: ...
    def set_Modifiers(self, value: list[Modifiers]) -> None: ...
    def getModifiers(self) -> System.Collections.ArrayList: ...
    def setModifiers(self, val: System.Collections.ArrayList) -> None: ...
    def get_Properties(self) -> list[PolicyProperty]: ...
    def set_Properties(self, value: list[PolicyProperty]) -> None: ...
    def getProperties(self) -> System.Collections.ArrayList: ...
    def setProperties(self, val: System.Collections.ArrayList) -> None: ...

class Preferences:
    def __init__(self, ) -> None: ...
    Prefs: list[Preference]
    def get_Prefs(self) -> list[Preference]: ...
    def set_Prefs(self, value: list[Preference]) -> None: ...
    def getPrefs(self) -> System.Collections.ArrayList: ...
    def setPrefs(self, val: System.Collections.ArrayList) -> None: ...

class PreferenceValue:
    def __init__(self, ) -> None: ...
    Value: str
    def get_Value(self) -> str: ...
    def set_Value(self, value: str) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, val: str) -> None: ...

class Preference:
    def __init__(self, ) -> None: ...
    Name: str
    Scope: str
    Values: list[PreferenceValue]
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Scope(self) -> str: ...
    def set_Scope(self, value: str) -> None: ...
    def getScope(self) -> str: ...
    def setScope(self, val: str) -> None: ...
    def get_Values(self) -> list[PreferenceValue]: ...
    def set_Values(self, value: list[PreferenceValue]) -> None: ...
    def getValues(self) -> System.Collections.ArrayList: ...
    def setValues(self, val: System.Collections.ArrayList) -> None: ...

class PropDependant:
    def __init__(self, ) -> None: ...
    Name: str
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...

class PropDescriptor:
    def __init__(self, ) -> None: ...
    Name: str
    MaxLength: int
    IsMaxLengthSet: bool
    LovUid: str
    IsLovUidSet: bool
    LovTypeUid: str
    IsLovTypeUidSet: bool
    Displayable: bool
    MaxArraySize: int
    IsMaxArraySizeSet: bool
    AttachedSpecifier: int
    IsAttachedSpecifierSet: bool
    TypeUid: str
    Enabled: bool
    IsEnabledSet: bool
    Required: bool
    IsRequiredSet: bool
    Type: int
    AnArray: bool
    Uiname: str
    Ptype: int
    Modifiable: bool
    PropDependants: list[PropDependant]
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_MaxLength(self) -> int: ...
    def set_MaxLength(self, value: int) -> None: ...
    def getMaxLength(self) -> int: ...
    def setMaxLength(self, val: int) -> None: ...
    def get_IsMaxLengthSet(self) -> bool: ...
    def get_LovUid(self) -> str: ...
    def set_LovUid(self, value: str) -> None: ...
    def getLovUid(self) -> str: ...
    def setLovUid(self, val: str) -> None: ...
    def get_IsLovUidSet(self) -> bool: ...
    def get_LovTypeUid(self) -> str: ...
    def set_LovTypeUid(self, value: str) -> None: ...
    def getLovTypeUid(self) -> str: ...
    def setLovTypeUid(self, val: str) -> None: ...
    def get_IsLovTypeUidSet(self) -> bool: ...
    def get_Displayable(self) -> bool: ...
    def set_Displayable(self, value: bool) -> None: ...
    def getDisplayable(self) -> bool: ...
    def setDisplayable(self, val: bool) -> None: ...
    def get_MaxArraySize(self) -> int: ...
    def set_MaxArraySize(self, value: int) -> None: ...
    def getMaxArraySize(self) -> int: ...
    def setMaxArraySize(self, val: int) -> None: ...
    def get_IsMaxArraySizeSet(self) -> bool: ...
    def get_AttachedSpecifier(self) -> int: ...
    def set_AttachedSpecifier(self, value: int) -> None: ...
    def getAttachedSpecifier(self) -> int: ...
    def setAttachedSpecifier(self, val: int) -> None: ...
    def get_IsAttachedSpecifierSet(self) -> bool: ...
    def get_TypeUid(self) -> str: ...
    def set_TypeUid(self, value: str) -> None: ...
    def getTypeUid(self) -> str: ...
    def setTypeUid(self, val: str) -> None: ...
    def get_Enabled(self) -> bool: ...
    def set_Enabled(self, value: bool) -> None: ...
    def getEnabled(self) -> bool: ...
    def setEnabled(self, val: bool) -> None: ...
    def get_IsEnabledSet(self) -> bool: ...
    def get_Required(self) -> bool: ...
    def set_Required(self, value: bool) -> None: ...
    def getRequired(self) -> bool: ...
    def setRequired(self, val: bool) -> None: ...
    def get_IsRequiredSet(self) -> bool: ...
    def get_Type(self) -> int: ...
    def set_Type(self, value: int) -> None: ...
    def getType(self) -> int: ...
    def setType(self, val: int) -> None: ...
    def get_AnArray(self) -> bool: ...
    def set_AnArray(self, value: bool) -> None: ...
    def getAnArray(self) -> bool: ...
    def setAnArray(self, val: bool) -> None: ...
    def get_Uiname(self) -> str: ...
    def set_Uiname(self, value: str) -> None: ...
    def getUiname(self) -> str: ...
    def setUiname(self, val: str) -> None: ...
    def get_Ptype(self) -> int: ...
    def set_Ptype(self, value: int) -> None: ...
    def getPtype(self) -> int: ...
    def setPtype(self, val: int) -> None: ...
    def get_Modifiable(self) -> bool: ...
    def set_Modifiable(self, value: bool) -> None: ...
    def getModifiable(self) -> bool: ...
    def setModifiable(self, val: bool) -> None: ...
    def get_PropDependants(self) -> list[PropDependant]: ...
    def set_PropDependants(self, value: list[PropDependant]) -> None: ...
    def getPropDependants(self) -> System.Collections.ArrayList: ...
    def setPropDependants(self, val: System.Collections.ArrayList) -> None: ...

class PropertyNameValues:
    def __init__(self, ) -> None: ...
    Key: str
    Value: list[str]
    def get_Key(self) -> str: ...
    def set_Key(self, value: str) -> None: ...
    def getKey(self) -> str: ...
    def setKey(self, val: str) -> None: ...
    def get_Value(self) -> list[str]: ...
    def set_Value(self, value: list[str]) -> None: ...
    def getValue(self) -> System.Collections.ArrayList: ...
    def setValue(self, val: System.Collections.ArrayList) -> None: ...

class PropertyValue:
    def __init__(self, ) -> None: ...
    IsNull: bool
    IsIsNullSet: bool
    Value: str
    def get_IsNull(self) -> bool: ...
    def set_IsNull(self, value: bool) -> None: ...
    def getIsNull(self) -> bool: ...
    def setIsNull(self, val: bool) -> None: ...
    def get_IsIsNullSet(self) -> bool: ...
    def get_Value(self) -> str: ...
    def set_Value(self, value: str) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, val: str) -> None: ...

class Property:
    def __init__(self, ) -> None: ...
    Modifiable: bool
    IsModifiableSet: bool
    Name: str
    HasReadAccess: bool
    IsHasReadAccessSet: bool
    UiValue: str
    IsUiValueSet: bool
    Values: list[PropertyValue]
    UiValues: list[str]
    def get_Modifiable(self) -> bool: ...
    def set_Modifiable(self, value: bool) -> None: ...
    def getModifiable(self) -> bool: ...
    def setModifiable(self, val: bool) -> None: ...
    def get_IsModifiableSet(self) -> bool: ...
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_HasReadAccess(self) -> bool: ...
    def set_HasReadAccess(self, value: bool) -> None: ...
    def getHasReadAccess(self) -> bool: ...
    def setHasReadAccess(self, val: bool) -> None: ...
    def get_IsHasReadAccessSet(self) -> bool: ...
    def get_UiValue(self) -> str: ...
    def set_UiValue(self, value: str) -> None: ...
    def getUiValue(self) -> str: ...
    def setUiValue(self, val: str) -> None: ...
    def get_IsUiValueSet(self) -> bool: ...
    def get_Values(self) -> list[PropertyValue]: ...
    def set_Values(self, value: list[PropertyValue]) -> None: ...
    def getValues(self) -> System.Collections.ArrayList: ...
    def setValues(self, val: System.Collections.ArrayList) -> None: ...
    def get_UiValues(self) -> list[str]: ...
    def set_UiValues(self, value: list[str]) -> None: ...
    def getUiValues(self) -> System.Collections.ArrayList: ...
    def setUiValues(self, val: System.Collections.ArrayList) -> None: ...

class RefId:
    def __init__(self, ) -> None: ...
    Uid: str
    def get_Uid(self) -> str: ...
    def set_Uid(self, value: str) -> None: ...
    def getUid(self) -> str: ...
    def setUid(self, val: str) -> None: ...

class ServiceData:
    def __init__(self, ) -> None: ...
    UpdatedObjs: list[RefId]
    DeletedObjs: list[RefId]
    CreatedObjs: list[RefId]
    ChildChangeObjs: list[RefId]
    PlainObjs: list[RefId]
    Updated: list[str]
    Deleted: list[str]
    Created: list[str]
    ChildChange: list[str]
    Plain: list[str]
    DataObjects: list[ModelObject]
    ModelObjects: list[ObjectMap]
    PartialErrors: list[ErrorStack]
    def get_UpdatedObjs(self) -> list[RefId]: ...
    def set_UpdatedObjs(self, value: list[RefId]) -> None: ...
    def getUpdatedObjs(self) -> System.Collections.ArrayList: ...
    def setUpdatedObjs(self, val: System.Collections.ArrayList) -> None: ...
    def get_DeletedObjs(self) -> list[RefId]: ...
    def set_DeletedObjs(self, value: list[RefId]) -> None: ...
    def getDeletedObjs(self) -> System.Collections.ArrayList: ...
    def setDeletedObjs(self, val: System.Collections.ArrayList) -> None: ...
    def get_CreatedObjs(self) -> list[RefId]: ...
    def set_CreatedObjs(self, value: list[RefId]) -> None: ...
    def getCreatedObjs(self) -> System.Collections.ArrayList: ...
    def setCreatedObjs(self, val: System.Collections.ArrayList) -> None: ...
    def get_ChildChangeObjs(self) -> list[RefId]: ...
    def set_ChildChangeObjs(self, value: list[RefId]) -> None: ...
    def getChildChangeObjs(self) -> System.Collections.ArrayList: ...
    def setChildChangeObjs(self, val: System.Collections.ArrayList) -> None: ...
    def get_PlainObjs(self) -> list[RefId]: ...
    def set_PlainObjs(self, value: list[RefId]) -> None: ...
    def getPlainObjs(self) -> System.Collections.ArrayList: ...
    def setPlainObjs(self, val: System.Collections.ArrayList) -> None: ...
    def get_Updated(self) -> list[str]: ...
    def set_Updated(self, value: list[str]) -> None: ...
    def getUpdated(self) -> System.Collections.ArrayList: ...
    def setUpdated(self, val: System.Collections.ArrayList) -> None: ...
    def get_Deleted(self) -> list[str]: ...
    def set_Deleted(self, value: list[str]) -> None: ...
    def getDeleted(self) -> System.Collections.ArrayList: ...
    def setDeleted(self, val: System.Collections.ArrayList) -> None: ...
    def get_Created(self) -> list[str]: ...
    def set_Created(self, value: list[str]) -> None: ...
    def getCreated(self) -> System.Collections.ArrayList: ...
    def setCreated(self, val: System.Collections.ArrayList) -> None: ...
    def get_ChildChange(self) -> list[str]: ...
    def set_ChildChange(self, value: list[str]) -> None: ...
    def getChildChange(self) -> System.Collections.ArrayList: ...
    def setChildChange(self, val: System.Collections.ArrayList) -> None: ...
    def get_Plain(self) -> list[str]: ...
    def set_Plain(self, value: list[str]) -> None: ...
    def getPlain(self) -> System.Collections.ArrayList: ...
    def setPlain(self, val: System.Collections.ArrayList) -> None: ...
    def get_DataObjects(self) -> list[ModelObject]: ...
    def set_DataObjects(self, value: list[ModelObject]) -> None: ...
    def getDataObjects(self) -> System.Collections.ArrayList: ...
    def setDataObjects(self, val: System.Collections.ArrayList) -> None: ...
    def get_ModelObjects(self) -> list[ObjectMap]: ...
    def set_ModelObjects(self, value: list[ObjectMap]) -> None: ...
    def getModelObjects(self) -> System.Collections.ArrayList: ...
    def setModelObjects(self, val: System.Collections.ArrayList) -> None: ...
    def get_PartialErrors(self) -> list[ErrorStack]: ...
    def set_PartialErrors(self, value: list[ErrorStack]) -> None: ...
    def getPartialErrors(self) -> System.Collections.ArrayList: ...
    def setPartialErrors(self, val: System.Collections.ArrayList) -> None: ...

class TextInfo:
    def __init__(self, ) -> None: ...
    Name: str
    DisplayValue: str
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_DisplayValue(self) -> str: ...
    def set_DisplayValue(self, value: str) -> None: ...
    def getDisplayValue(self) -> str: ...
    def setDisplayValue(self, val: str) -> None: ...

class XJPropertyValue:
    def __init__(self, ) -> None: ...
    Modifiable: bool
    IsModifiableSet: bool
    HasReadAccess: bool
    IsHasReadAccessSet: bool
    DbValues: list[str]
    UiValues: list[str]
    IsNulls: list[bool]
    def get_Modifiable(self) -> bool: ...
    def set_Modifiable(self, value: bool) -> None: ...
    def getModifiable(self) -> bool: ...
    def setModifiable(self, val: bool) -> None: ...
    def get_IsModifiableSet(self) -> bool: ...
    def get_HasReadAccess(self) -> bool: ...
    def set_HasReadAccess(self, value: bool) -> None: ...
    def getHasReadAccess(self) -> bool: ...
    def setHasReadAccess(self, val: bool) -> None: ...
    def get_IsHasReadAccessSet(self) -> bool: ...
    def get_DbValues(self) -> list[str]: ...
    def set_DbValues(self, value: list[str]) -> None: ...
    def getDbValues(self) -> System.Collections.ArrayList: ...
    def setDbValues(self, val: System.Collections.ArrayList) -> None: ...
    def get_UiValues(self) -> list[str]: ...
    def set_UiValues(self, value: list[str]) -> None: ...
    def getUiValues(self) -> System.Collections.ArrayList: ...
    def setUiValues(self, val: System.Collections.ArrayList) -> None: ...
    def get_IsNulls(self) -> list[bool]: ...
    def set_IsNulls(self, value: list[bool]) -> None: ...
    def getIsNulls(self) -> System.Collections.ArrayList: ...
    def setIsNulls(self, val: System.Collections.ArrayList) -> None: ...

class XJProperty:
    def __init__(self, ) -> None: ...
    Name: str
    Value: XJPropertyValue
    def get_Name(self) -> str: ...
    def set_Name(self, value: str) -> None: ...
    def getName(self) -> str: ...
    def setName(self, val: str) -> None: ...
    def get_Value(self) -> XJPropertyValue: ...
    def set_Value(self, value: XJPropertyValue) -> None: ...
    def getValue(self) -> XJPropertyValue: ...
    def setValue(self, val: XJPropertyValue) -> None: ...

