import System
import Teamcenter.Services.Strong.Query._2007_09.SavedQuery
import Teamcenter.Services.Strong.Query._2010_09.SavedQuery
import typing

class AttributeSortOption:
    """
    Structure for attribute sort option.
    """
    def __init__(self, ) -> None: ...
    SortAttribute: str
    """Attribute of the type being searched based on which the results will be sorted."""
    SortOrder: str
    """Order in which results are sorted AscendingOrder or DescendingOrder."""

class BusinessObjectQueryInput3:
    """
    Input structure for executeBOQueriesWithSort operation.
    """
    def __init__(self, ) -> None: ...
    BoTypeName: str
    """Name of business object type. Supports BusinessObject and all subtypes."""
    Clauses: list[Teamcenter.Services.Strong.Query._2010_09.SavedQuery.BusinessObjectQueryClause]
    """
            Query clauses in search criteria. Each clause consists of property name, property
            value, logic and math operators.
            """
    SortOptions: list[AttributeSortOption]
    """
            A list of attribute sort options based on which the results will be sorted. The first
            element of the list is the primary sort field, second is the secondary sort field
            and so on.
            """
    MaxNumToReturn: int
    """Specified maximum number of objects to return."""
    RequestId: str
    """
            Unique ID used to register the query execution task. This can be used by the caller
            to cancel the time consuming query, the value can be generated by any unique string
            generator. The query can be cancelled by calling: TcSoaFrameworkCore.Session.cancelOperations
            (requestId).
            """
    ClientId: str
    """
            This unique ID is used to identify return data elements and partial errors associated
            with this input structure. This is currently not yet used by the return data elements,
            the caller can leave it empty.
            """

class SavedQuery:
    """
    Interface SavedQuery
    """
    def __init__(self , *args: typing.Any) -> None: ...
    def ExecuteBOQueriesWithSort(self, Inputs: list[BusinessObjectQueryInput3]) -> Teamcenter.Services.Strong.Query._2007_09.SavedQuery.SavedQueriesResponse:
        """    
             This operation executes business object queries with sorting options.
             

Teamcenter Component:

             Search - The capabilities to allow searching objects using the business object symantics
             that have been persisted via the persistence management.
             
        :param Inputs: 
                         Business object query inputs.
             
        :return: 
        """
        ...

