import System
import System.Collections
import Teamcenter.Schemas.Soa._2011_06.Metamodel
import Teamcenter.Services.Loose.Core._2006_03.Session
import Teamcenter.Services.Loose.Core._2007_12.Session
import Teamcenter.Soa.Client.Model
import typing

class Session:
    def __init__(self , *args: typing.Any) -> None: ...
    def GetTypeDescriptions2(self, TypeNames: list[str], Options: System.Collections.Hashtable) -> Teamcenter.Schemas.Soa._2011_06.Metamodel.TypeSchema: ...
    def SetUserSessionStateAndUpdateDefaults(self, Pairs: list[Teamcenter.Services.Loose.Core._2007_12.Session.StateNameValue]) -> Teamcenter.Soa.Client.Model.ServiceData: ...
    def SponsoredLogin(self, SponsoringUser: str, Password: str, SponsoredUser: str, SponsoredGroup: str, SponsoredRole: str, Locale: str, SessionDiscriminator: str) -> Teamcenter.Services.Loose.Core._2006_03.Session.LoginResponse: ...
    def SponsoredLoginSSO(self, SponsoringUser: str, SsoCredentials: str, SponsoredUser: str, SponsoredGroup: str, SponsoredRole: str, Locale: str, SessionDiscriminator: str) -> Teamcenter.Services.Loose.Core._2006_03.Session.LoginResponse: ...

